//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSString, UILabel, UISwitch;

@interface AccountAndPasswordViewController : UITableViewController
{
    _Bool _switch_mark;
    _Bool _haveEmail;
    _Bool _havePassword;
    UILabel *_emailAddress;
    UILabel *_weixinLabel;
    UILabel *_weiboLabel;
    UILabel *_githubLabel;
    UILabel *_twitterLabel;
    UISwitch *_weixinSwitch;
    UISwitch *_weiboSwitch;
    UISwitch *_githubSwitch;
    UISwitch *_twitterSwitch;
    NSString *_weixinID;
    NSString *_weiboID;
    NSString *_githubID;
    NSString *_twitterID;
}

- (void).cxx_destruct;
- (void)bindingGitHubAccount;
- (void)bindingSinaAccount;
- (void)bindingTwitterAccount;
- (void)bindingWeChatAccount;
- (void)deleteThirdPlatformWithID:(id)arg1 sender:(id)arg2;
- (void)didReceiveMemoryWarning;
@property(nonatomic) __weak UILabel *emailAddress; // @synthesize emailAddress=_emailAddress;
@property(copy, nonatomic) NSString *githubID; // @synthesize githubID=_githubID;
@property(nonatomic) __weak UILabel *githubLabel; // @synthesize githubLabel=_githubLabel;
@property(nonatomic) __weak UISwitch *githubSwitch; // @synthesize githubSwitch=_githubSwitch;
- (void)githubSwitchValueChange:(id)arg1;
@property(nonatomic) _Bool haveEmail; // @synthesize haveEmail=_haveEmail;
@property(nonatomic) _Bool havePassword; // @synthesize havePassword=_havePassword;
- (void)refreshUserinfo;
@property(nonatomic) _Bool switch_mark; // @synthesize switch_mark=_switch_mark;
@property(copy, nonatomic) NSString *twitterID; // @synthesize twitterID=_twitterID;
@property(nonatomic) __weak UILabel *twitterLabel; // @synthesize twitterLabel=_twitterLabel;
@property(nonatomic) __weak UISwitch *twitterSwitch; // @synthesize twitterSwitch=_twitterSwitch;
@property(copy, nonatomic) NSString *weiboID; // @synthesize weiboID=_weiboID;
@property(nonatomic) __weak UILabel *weiboLabel; // @synthesize weiboLabel=_weiboLabel;
@property(nonatomic) __weak UISwitch *weiboSwitch; // @synthesize weiboSwitch=_weiboSwitch;
@property(copy, nonatomic) NSString *weixinID; // @synthesize weixinID=_weixinID;
@property(nonatomic) __weak UILabel *weixinLabel; // @synthesize weixinLabel=_weixinLabel;
@property(nonatomic) __weak UISwitch *weixinSwitch; // @synthesize weixinSwitch=_weixinSwitch;
- (void)setupAlertController;
- (void)showVerifyAlertWithMessage:(id)arg1 andTitle:(id)arg2;
- (void)showVerifyFaileAlertWith:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)twitterSwitchValueChange:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)wechatLoginSuccess:(id)arg1;
- (void)weiboSwitchValueChange:(id)arg1;
- (void)weixinSwitchValueChange:(id)arg1;

@end

