//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class ActivityModel, AuthorModel, UIImageView, UILabel;

@interface ActivityCell : UITableViewCell
{
    _Bool _isColumn;
    ActivityModel *_model;
    CDUnknownBlockType _turnToStandard;
    CDUnknownBlockType _turnToHome;
    CDUnknownBlockType _turnToMatrix;
    CDUnknownBlockType _feedback;
    CDUnknownBlockType _turnToArticle;
    CDUnknownBlockType _turnToComment;
    CDUnknownBlockType _turnToUser;
    UIImageView *_markImage;
    UILabel *_actionTitleLabel;
    UILabel *_descLabel;
    UILabel *_timeLabel;
    long long _articleIntex;
    AuthorModel *_author;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *actionTitleLabel; // @synthesize actionTitleLabel=_actionTitleLabel;
- (void)addButtonWithFrame:(struct CGRect)arg1 action:(SEL)arg2;
@property(nonatomic) long long articleIntex; // @synthesize articleIntex=_articleIntex;
- (void)articleViewController:(id)arg1;
@property(retain, nonatomic) AuthorModel *author; // @synthesize author=_author;
- (void)awakeFromNib;
- (struct CGRect)calculateFrameWith:(id)arg1 from:(id)arg2;
- (void)commentViewController;
@property(nonatomic) __weak UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(copy, nonatomic) CDUnknownBlockType feedback; // @synthesize feedback=_feedback;
- (void)feedbackView;
- (void)homeView;
@property(nonatomic) _Bool isColumn; // @synthesize isColumn=_isColumn;
@property(nonatomic) __weak UIImageView *markImage; // @synthesize markImage=_markImage;
- (void)matrixView;
@property(retain, nonatomic) ActivityModel *model; // @synthesize model=_model;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(copy, nonatomic) CDUnknownBlockType turnToArticle; // @synthesize turnToArticle=_turnToArticle;
@property(copy, nonatomic) CDUnknownBlockType turnToComment; // @synthesize turnToComment=_turnToComment;
@property(copy, nonatomic) CDUnknownBlockType turnToHome; // @synthesize turnToHome=_turnToHome;
@property(copy, nonatomic) CDUnknownBlockType turnToMatrix; // @synthesize turnToMatrix=_turnToMatrix;
@property(copy, nonatomic) CDUnknownBlockType turnToStandard; // @synthesize turnToStandard=_turnToStandard;
@property(copy, nonatomic) CDUnknownBlockType turnToUser; // @synthesize turnToUser=_turnToUser;
- (void)standardView;
- (void)userHomeViewController;

@end

