//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AFImageRequestCache.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface AFAutoPurgingImageCache : NSObject <AFImageRequestCache>
{
    unsigned long long _memoryCapacity;
    unsigned long long _preferredMemoryUsageAfterPurge;
    NSMutableDictionary *_cachedImages;
    unsigned long long _currentMemoryUsage;
    NSObject<OS_dispatch_queue> *_synchronizationQueue;
}

- (void).cxx_destruct;
- (void)addImage:(id)arg1 forRequest:(id)arg2 withAdditionalIdentifier:(id)arg3;
- (void)addImage:(id)arg1 withIdentifier:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *cachedImages; // @synthesize cachedImages=_cachedImages;
@property(nonatomic) unsigned long long currentMemoryUsage; // @synthesize currentMemoryUsage=_currentMemoryUsage;
- (void)dealloc;
- (id)imageCacheKeyFromURLRequest:(id)arg1 withAdditionalIdentifier:(id)arg2;
- (id)imageWithIdentifier:(id)arg1;
- (id)imageforRequest:(id)arg1 withAdditionalIdentifier:(id)arg2;
- (id)init;
- (id)initWithMemoryCapacity:(unsigned long long)arg1 preferredMemoryCapacity:(unsigned long long)arg2;
@property(nonatomic) unsigned long long memoryCapacity; // @synthesize memoryCapacity=_memoryCapacity;
@property(readonly, nonatomic) unsigned long long memoryUsage;
@property(nonatomic) unsigned long long preferredMemoryUsageAfterPurge; // @synthesize preferredMemoryUsageAfterPurge=_preferredMemoryUsageAfterPurge;
- (_Bool)removeAllImages;
- (_Bool)removeImageWithIdentifier:(id)arg1;
- (_Bool)removeImageforRequest:(id)arg1 withAdditionalIdentifier:(id)arg2;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *synchronizationQueue; // @synthesize synchronizationQueue=_synchronizationQueue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

