//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AliSecXLocalStorage : NSObject
{
}

+ (_Bool)createFile:(id)arg1;
+ (_Bool)createFile:(id)arg1 fromFolder:(long long)arg2 withPath:(id)arg3 error:(id *)arg4;
+ (_Bool)deleteItemFromKeychain:(id)arg1;
+ (_Bool)deleteItemFromKeychain:(id)arg1 error:(id *)arg2;
+ (_Bool)deleteItemFromKeychain:(id)arg1 service:(id)arg2;
+ (id)getDocumentsFolderFileListFromFolder:(long long)arg1 withPath:(id)arg2 error:(id *)arg3;
+ (unsigned long long)getFileSize:(id)arg1 error:(id *)arg2;
+ (unsigned long long)getFileSize:(id)arg1 fromFolder:(long long)arg2 withPath:(id)arg3 error:(id *)arg4;
+ (id)getFirstLevelFolderPath:(long long)arg1;
+ (_Bool)isFileExist:(id)arg1;
+ (_Bool)isFileExist:(id)arg1 fromFolder:(long long)arg2 withPath:(id)arg3;
+ (id)loadDataFromFile:(id)arg1 fromFolder:(long long)arg2 withPath:(id)arg3;
+ (id)loadDataFromKeychain:(id)arg1;
+ (id)loadStringFromKeychain:(id)arg1;
+ (id)loadStringFromKeychain:(id)arg1 error:(id *)arg2;
+ (id)loadStringFromKeychain:(id)arg1 service:(id)arg2;
+ (_Bool)removeFile:(id)arg1 error:(id *)arg2;
+ (_Bool)removeFile:(id)arg1 fromFolder:(long long)arg2 withPath:(id)arg3 error:(id *)arg4;
+ (long long)saveDataToFile:(id)arg1 Value:(id)arg2 fromFolder:(long long)arg3 withPath:(id)arg4;
+ (long long)saveDataToKeychain:(id)arg1 Value:(id)arg2;
+ (long long)saveStringToKeychain:(id)arg1 Value:(id)arg2;
+ (_Bool)saveStringToKeychain:(id)arg1 Value:(id)arg2 error:(id *)arg3;

@end

