//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class NSString, UIAlertView, UIViewController;

@interface APAlertView : NSObject <UIAlertViewDelegate>
{
    long long _totalIndex;
    long long _cancelButtonIndex;
    id <APAlertViewDelegate> _delegate;
    UIAlertView *_alertView;
    UIViewController *_alertContrller;
    UIViewController *_bottomContrller;
}

- (void).cxx_destruct;
- (long long)actionWithTitle:(id)arg1 style:(long long)arg2;
@property(retain, nonatomic) UIViewController *alertContrller; // @synthesize alertContrller=_alertContrller;
@property(retain, nonatomic) UIAlertView *alertView; // @synthesize alertView=_alertView;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)applicationEnterBackground:(id)arg1;
@property(retain, nonatomic) UIViewController *bottomContrller; // @synthesize bottomContrller=_bottomContrller;
@property(nonatomic) long long cancelButtonIndex; // @synthesize cancelButtonIndex=_cancelButtonIndex;
- (void)dealloc;
@property(nonatomic) __weak id <APAlertViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dismissWithClickedButtonIndex:(long long)arg1 animated:(_Bool)arg2;
- (id)init;
- (id)initWithTitle:(id)arg1 message:(id)arg2 delegate:(id)arg3 cancelButtonTitle:(id)arg4 otherButtonTitles:(id)arg5;
- (void)internal_init;
- (void)show;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

