//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIWebViewDelegate.h"

@class APayH5WapViewToolbar, APayH5WebViewProgressView, NSString, NSTimer, UIWebView;

@interface APayWapPayViewController : UIViewController <UIWebViewDelegate>
{
    float _statusbarHeight;
    _Bool _exStatusbarHidden;
    NSString *_urlStr;
    UIWebView *_wapPayView;
    NSString *_paramsStr;
    CDUnknownBlockType _resultBlock;
    APayH5WebViewProgressView *_progressView;
    NSTimer *_timer;
    long long _statusBarStyle;
    APayH5WapViewToolbar *_toolbar;
}

- (void).cxx_destruct;
- (void)completeProgress;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
@property(nonatomic) _Bool exStatusbarHidden; // @synthesize exStatusbarHidden=_exStatusbarHidden;
- (void)handleTimer:(id)arg1;
- (void)hideToolbar;
- (id)initWithUrl:(id)arg1 params:(id)arg2 result:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) NSString *paramsStr; // @synthesize paramsStr=_paramsStr;
@property(retain, nonatomic) APayH5WebViewProgressView *progressView; // @synthesize progressView=_progressView;
- (void)quitWapCashier;
- (void)quitWithResult:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reset;
@property(copy, nonatomic) CDUnknownBlockType resultBlock; // @synthesize resultBlock=_resultBlock;
- (id)resultDicWithQuery:(id)arg1;
- (void)rotateAccordingToStatusBarOrientationAndSupportedOrientations;
- (void)rotateSelfViewWithOrientation:(long long)arg1;
@property(nonatomic) long long statusBarStyle; // @synthesize statusBarStyle=_statusBarStyle;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) APayH5WapViewToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(copy, nonatomic) NSString *urlStr; // @synthesize urlStr=_urlStr;
@property(retain, nonatomic) UIWebView *wapPayView; // @synthesize wapPayView=_wapPayView;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)showToolbar;
- (void)startProgress;
- (void)statusBarFrameOrOrientationChanged:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

