//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface APHTTPCookieStorage : NSObject
{
    NSMutableArray *_cookies;
    id <NSLocking> _locker;
}

+ (id)sharedHTTPCookieStorage;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *cookies; // @synthesize cookies=_cookies;
- (id)cookiesForURL:(id)arg1;
- (void)deleteAllCookies;
- (void)deleteCookie:(id)arg1;
- (id)httpCookieHeaderStrForUrl:(id)arg1;
- (long long)indexOfCookie:(id)arg1;
- (id)init;
- (void)lock;
@property(retain, nonatomic) id <NSLocking> locker; // @synthesize locker=_locker;
- (void)setCookie:(id)arg1;
- (void)setCookies:(id)arg1 forURL:(id)arg2 mainDocumentURL:(id)arg3;
- (void)tryToAddCookie:(id)arg1 ToArray:(id)arg2;
- (void)unlock;

@end

