//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APURLConnectionOperation.h"

@class NSError, NSHTTPURLResponse, NSObject<OS_dispatch_queue>, NSRecursiveLock, NSURLRequest;

@interface APHTTPRequestOperation : APURLConnectionOperation
{
    NSError *_HTTPError;
    NSObject<OS_dispatch_queue> *_successCallbackQueue;
    NSObject<OS_dispatch_queue> *_failureCallbackQueue;
}

+ (id)acceptableContentTypes;
+ (id)acceptableStatusCodes;
+ (void)addAcceptableContentTypes:(id)arg1;
+ (void)addAcceptableStatusCodes:(id)arg1;
+ (_Bool)canProcessRequest:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSError *HTTPError; // @synthesize HTTPError=_HTTPError;
- (void)dealloc;
- (id)error;
@property(nonatomic) NSObject<OS_dispatch_queue> *failureCallbackQueue; // @synthesize failureCallbackQueue=_failureCallbackQueue;
@property(readonly, nonatomic) _Bool hasAcceptableContentType;
@property(readonly, nonatomic) _Bool hasAcceptableStatusCode;
- (void)pause;
- (unsigned long long)responseStringEncoding;
- (void)setCompletionBlockWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
@property(nonatomic) NSObject<OS_dispatch_queue> *successCallbackQueue; // @synthesize successCallbackQueue=_successCallbackQueue;

// Remaining properties
@property(retain, nonatomic) NSRecursiveLock *lock; // @dynamic lock;
@property(retain, nonatomic) NSURLRequest *request; // @dynamic request;
@property(retain, nonatomic) NSHTTPURLResponse *response; // @dynamic response;

@end

