//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AdminModel, AdvertisementModel, AuthorModel, NSArray, NSString, UIImage;

@interface ArticleModel : NSObject
{
    _Bool _free;
    _Bool _allow_comment;
    _Bool _blocked;
    _Bool _is_matrix;
    _Bool _deleted_status;
    _Bool _liked;
    _Bool _favorited;
    _Bool _password;
    UIImage *_image;
    NSString *_banner;
    NSString *_banner_id;
    NSString *_title;
    NSString *_body;
    NSString *_advertisement_url;
    NSString *_custom_tags;
    NSString *_promote_title;
    NSString *_promote_intro;
    NSString *_promote_image;
    NSString *_promote_image_id;
    NSString *_corner_id;
    NSString *_ID;
    NSString *_created_at;
    NSString *_views_count;
    NSString *_comment_total;
    NSString *_like_total;
    NSString *_favorites_count;
    NSString *_released_at;
    NSString *_tips_count;
    NSString *_tips_total;
    NSString *_type;
    NSString *_recommend_to_home_at;
    NSString *_matrix_at;
    NSString *_deleted_at;
    NSString *_words_count;
    NSString *_summary;
    AuthorModel *_author;
    AdminModel *_follow_up_admin;
    NSArray *_special_columns;
    NSArray *_tags;
    NSArray *_topics;
    AdvertisementModel *_advertisement;
}

+ (void)loadAppCardArticleWithParameters:(id)arg1 Finished:(CDUnknownBlockType)arg2;
+ (void)loadHomeArticleWithParameters:(id)arg1 Finished:(CDUnknownBlockType)arg2;
+ (void)loadModelWithParameters:(id)arg1 Finished:(CDUnknownBlockType)arg2;
+ (void)loadNewAppCardArticleWithParameters:(id)arg1 Finished:(CDUnknownBlockType)arg2;
+ (void)loadNewHomeArticleWithParameters:(id)arg1 Finished:(CDUnknownBlockType)arg2;
+ (id)modelContainerPropertyGenericClass;
+ (id)modelCustomPropertyMapper;
+ (void)requestArticleWith:(id)arg1 Finished:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
@property(retain, nonatomic) AdvertisementModel *advertisement; // @synthesize advertisement=_advertisement;
@property(copy, nonatomic) NSString *advertisement_url; // @synthesize advertisement_url=_advertisement_url;
@property(nonatomic) _Bool allow_comment; // @synthesize allow_comment=_allow_comment;
@property(retain, nonatomic) AuthorModel *author; // @synthesize author=_author;
@property(copy, nonatomic) NSString *banner; // @synthesize banner=_banner;
@property(copy, nonatomic) NSString *banner_id; // @synthesize banner_id=_banner_id;
@property(nonatomic) _Bool blocked; // @synthesize blocked=_blocked;
@property(copy, nonatomic) NSString *body; // @synthesize body=_body;
@property(copy, nonatomic) NSString *comment_total; // @synthesize comment_total=_comment_total;
@property(copy, nonatomic) NSString *corner_id; // @synthesize corner_id=_corner_id;
@property(copy, nonatomic) NSString *created_at; // @synthesize created_at=_created_at;
@property(copy, nonatomic) NSString *custom_tags; // @synthesize custom_tags=_custom_tags;
@property(copy, nonatomic) NSString *deleted_at; // @synthesize deleted_at=_deleted_at;
@property(nonatomic) _Bool deleted_status; // @synthesize deleted_status=_deleted_status;
@property(nonatomic) _Bool favorited; // @synthesize favorited=_favorited;
@property(copy, nonatomic) NSString *favorites_count; // @synthesize favorites_count=_favorites_count;
@property(retain, nonatomic) AdminModel *follow_up_admin; // @synthesize follow_up_admin=_follow_up_admin;
@property(nonatomic) _Bool free; // @synthesize free=_free;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) _Bool is_matrix; // @synthesize is_matrix=_is_matrix;
@property(copy, nonatomic) NSString *like_total; // @synthesize like_total=_like_total;
@property(nonatomic) _Bool liked; // @synthesize liked=_liked;
@property(copy, nonatomic) NSString *matrix_at; // @synthesize matrix_at=_matrix_at;
@property(nonatomic) _Bool password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *promote_image; // @synthesize promote_image=_promote_image;
@property(copy, nonatomic) NSString *promote_image_id; // @synthesize promote_image_id=_promote_image_id;
@property(copy, nonatomic) NSString *promote_intro; // @synthesize promote_intro=_promote_intro;
@property(copy, nonatomic) NSString *promote_title; // @synthesize promote_title=_promote_title;
@property(copy, nonatomic) NSString *recommend_to_home_at; // @synthesize recommend_to_home_at=_recommend_to_home_at;
@property(copy, nonatomic) NSString *released_at; // @synthesize released_at=_released_at;
@property(retain, nonatomic) NSArray *special_columns; // @synthesize special_columns=_special_columns;
@property(copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(copy, nonatomic) NSString *tips_count; // @synthesize tips_count=_tips_count;
@property(copy, nonatomic) NSString *tips_total; // @synthesize tips_total=_tips_total;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSArray *topics; // @synthesize topics=_topics;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *views_count; // @synthesize views_count=_views_count;
@property(copy, nonatomic) NSString *words_count; // @synthesize words_count=_words_count;

@end

