//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ASSStorageAccesser : NSObject
{
}

+ (void)clearStorage;
+ (id)getApdidcFromFile;
+ (id)getFromFile;
+ (id)getNewRadomizedID;
+ (id)getRandomizedID;
+ (id)loadApdidc;
+ (id)loadGID;
+ (id)loadJBErrorHistory;
+ (id)loadLastLoginTime;
+ (id)loadPreviousApdid;
+ (id)loadStorageModelFromKeychain;
+ (id)loadTrustData;
+ (void)saveApdidc:(id)arg1;
+ (void)saveCurrentLoginTime:(id)arg1;
+ (void)saveGID:(id)arg1;
+ (void)saveJBErrorHistory:(id)arg1;
+ (void)saveStorageModel:(id)arg1;
+ (void)saveTrustData:(id)arg1;

@end

