//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class BTNText, NSString, NSURL;

@interface BTNAuthChallenge : BTNModelObject
{
    NSString *_type;
    NSURL *_authURL;
    NSURL *_authProcessingURL;
    NSURL *_authResultURL;
    NSString *_resultQueryKey;
    NSString *_webViewCustomizationScript;
    BTNText *_loadingText;
    BTNText *_authProcessingText;
    BTNText *_accessDeniedText;
    BTNText *_generalErrorText;
}

+ (_Bool)canInitWithDictionary:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) BTNText *accessDeniedText; // @synthesize accessDeniedText=_accessDeniedText;
@property(readonly, nonatomic) BTNText *authProcessingText; // @synthesize authProcessingText=_authProcessingText;
@property(readonly, nonatomic) NSURL *authProcessingURL; // @synthesize authProcessingURL=_authProcessingURL;
@property(readonly, nonatomic) NSURL *authResultURL; // @synthesize authResultURL=_authResultURL;
@property(readonly, nonatomic) NSURL *authURL; // @synthesize authURL=_authURL;
- (id)dictionaryRepresentation;
@property(readonly, nonatomic) BTNText *generalErrorText; // @synthesize generalErrorText=_generalErrorText;
@property(readonly, nonatomic) BTNText *loadingText; // @synthesize loadingText=_loadingText;
@property(readonly, nonatomic) NSString *resultQueryKey; // @synthesize resultQueryKey=_resultQueryKey;
@property(readonly, nonatomic) NSString *type; // @synthesize type=_type;
- (void)updateWithRepresentation:(id)arg1;
@property(readonly, nonatomic) NSString *webViewCustomizationScript; // @synthesize webViewCustomizationScript=_webViewCustomizationScript;

@end

