//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class BTNImage, BTNPreferredActionType, NSDate, NSNumber, NSString, NSURL;

@interface BTNAppActionMeta : BTNModelObject
{
    NSString *_appActionId;
    NSString *_storeId;
    NSString *_sourceToken;
    NSNumber *_maxAgeSeconds;
    NSURL *_deepLinkScheme;
    NSString *_appDisplayName;
    BTNImage *_appIcon;
    NSDate *_expireDate;
    BTNPreferredActionType *_preferredAction;
}

+ (_Bool)canInitWithDictionary:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *appActionId; // @synthesize appActionId=_appActionId;
@property(readonly, copy, nonatomic) NSString *appDisplayName; // @synthesize appDisplayName=_appDisplayName;
@property(readonly, copy, nonatomic) BTNImage *appIcon; // @synthesize appIcon=_appIcon;
@property(readonly, copy, nonatomic) NSURL *deepLinkScheme; // @synthesize deepLinkScheme=_deepLinkScheme;
- (id)dictionaryRepresentation;
@property(copy, nonatomic) NSDate *expireDate; // @synthesize expireDate=_expireDate;
- (_Bool)isExpired;
@property(readonly, copy, nonatomic) NSNumber *maxAgeSeconds; // @synthesize maxAgeSeconds=_maxAgeSeconds;
@property(readonly, copy, nonatomic) BTNPreferredActionType *preferredAction; // @synthesize preferredAction=_preferredAction;
@property(readonly, copy, nonatomic) NSString *sourceToken; // @synthesize sourceToken=_sourceToken;
@property(readonly, copy, nonatomic) NSString *storeId; // @synthesize storeId=_storeId;
- (void)updateComputedValues;
- (void)updateWithRepresentation:(id)arg1;

@end

