//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BTNAutomaticURLHandler : NSObject
{
}

+ (void)addMethodToAppDelegateClass:(Class)arg1 selector:(SEL)arg2 imp:(CDUnknownFunctionPointerType)arg3;
+ (void)clearOriginalFunctions;
+ (void)configureAutomaticAttributionForAppDelegate:(id)arg1;
+ (_Bool)isEnabled;
+ (void)load;
+ (id)notificationCenter;
+ (void)postNotificationWithReceivedURL:(id)arg1;
+ (void)replaceApplicationContinueUserActivityRestorationHandlerForAppDelegateClass:(Class)arg1;
+ (void)replaceApplicationHandleOpenURLForAppDelegateClass:(Class)arg1;
+ (void)replaceApplicationOpenURLOptionsForAppDelegateClass:(Class)arg1;
+ (void)replaceApplicationOpenURLSourceApplicationAnnotationForAppDelegateClass:(Class)arg1;
+ (void)replaceSetAppDelegateForApplicationClass:(Class)arg1;
+ (void)setEnabled:(_Bool)arg1;
+ (void)setNotificationCenter:(id)arg1;

@end

