//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class BTNText, BTNWebViewSheet, NSArray, NSString;

@interface BTNBrowser : BTNModelObject
{
    NSString *_primaryColor;
    BTNText *_titleText;
    BTNText *_actionText;
    BTNWebViewSheet *_installSheet;
    BTNWebViewSheet *_dismissSheet;
    NSArray *_checkpoints;
}

+ (_Bool)canInitWithDictionary:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) BTNText *actionText; // @synthesize actionText=_actionText;
@property(readonly, nonatomic) NSArray *checkpoints; // @synthesize checkpoints=_checkpoints;
- (id)dictionaryRepresentation;
@property(readonly, nonatomic) BTNWebViewSheet *dismissSheet; // @synthesize dismissSheet=_dismissSheet;
@property(readonly, nonatomic) BTNWebViewSheet *installSheet; // @synthesize installSheet=_installSheet;
@property(readonly, nonatomic) NSString *primaryColor; // @synthesize primaryColor=_primaryColor;
@property(readonly, nonatomic) BTNText *titleText; // @synthesize titleText=_titleText;
- (void)updateWithRepresentation:(id)arg1;

@end

