//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNBaseViewController.h"

#import "BTNMutableResourceConsumer.h"
#import "BTNResourceConsumer.h"
#import "UIViewControllerTransitioningDelegate.h"

@class BTNResourceProvider, NSLayoutConstraint, NSString, UIButton, UIView;

@interface BTNBaseModalController : BTNBaseViewController <BTNMutableResourceConsumer, UIViewControllerTransitioningDelegate, BTNResourceConsumer>
{
    BTNResourceProvider *_resources;
    UIView *_modalView;
    UIView *_containerView;
    UIView *_contentWrapperView;
    NSLayoutConstraint *_containerTopConstraint;
    NSLayoutConstraint *_containerLeadingConstraint;
    NSLayoutConstraint *_containerTrailingConstraint;
    NSLayoutConstraint *_containerBottomConstraint;
    NSLayoutConstraint *_contentWidthConstraint;
    NSLayoutConstraint *_dismissButtonHeightConstraint;
    NSLayoutConstraint *_contentWrapperToDismissButtonConstraint;
    NSString *_trackingName;
    UIView *_blurredSnapshotView;
    UIView *_contentView;
    UIButton *_dismissButton;
    CDUnknownBlockType _actionHandlerBlock;
    CDUnknownBlockType _dismissHandlerBlock;
}

+ (id)modalWindow;
+ (void)setModalWindow:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType actionHandlerBlock; // @synthesize actionHandlerBlock=_actionHandlerBlock;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
@property(retain, nonatomic) UIView *blurredSnapshotView; // @synthesize blurredSnapshotView=_blurredSnapshotView;
@property(nonatomic) __weak NSLayoutConstraint *containerBottomConstraint; // @synthesize containerBottomConstraint=_containerBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *containerLeadingConstraint; // @synthesize containerLeadingConstraint=_containerLeadingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *containerTopConstraint; // @synthesize containerTopConstraint=_containerTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *containerTrailingConstraint; // @synthesize containerTrailingConstraint=_containerTrailingConstraint;
@property(nonatomic) __weak UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak NSLayoutConstraint *contentWidthConstraint; // @synthesize contentWidthConstraint=_contentWidthConstraint;
@property(nonatomic) __weak NSLayoutConstraint *contentWrapperToDismissButtonConstraint; // @synthesize contentWrapperToDismissButtonConstraint=_contentWrapperToDismissButtonConstraint;
@property(nonatomic) __weak UIView *contentWrapperView; // @synthesize contentWrapperView=_contentWrapperView;
- (void)dismiss;
@property(retain, nonatomic) UIButton *dismissButton; // @synthesize dismissButton=_dismissButton;
- (void)dismissButtonAction:(id)arg1;
@property(nonatomic) __weak NSLayoutConstraint *dismissButtonHeightConstraint; // @synthesize dismissButtonHeightConstraint=_dismissButtonHeightConstraint;
- (void)dismissGestureHandler:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType dismissHandlerBlock; // @synthesize dismissHandlerBlock=_dismissHandlerBlock;
- (void)dismissWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithResources:(id)arg1;
- (double)maximumContentHeight;
- (double)maximumContentWidth;
- (void)modalDidAppear;
@property(retain, nonatomic) UIView *modalView; // @synthesize modalView=_modalView;
- (long long)preferredStatusBarStyle;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources;
- (void)setResources:(id)arg1;
@property(copy, nonatomic) NSString *trackingName; // @synthesize trackingName=_trackingName;
- (void)show;
- (void)userTriggeredDismiss;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

