//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNBaseEntity.h"

@interface BTNContext : BTNBaseEntity
{
}

+ (id)context;
+ (id)contextWithArtist:(id)arg1;
+ (id)contextWithEvent:(id)arg1;
+ (id)contextWithItem:(id)arg1;
+ (id)contextWithItems:(id)arg1;
+ (id)contextWithJourney:(id)arg1;
+ (id)contextWithSubjectLocation:(id)arg1;
+ (id)contextWithURL:(id)arg1;
+ (id)contextWithUserLocation:(id)arg1;
- (void)addCustomValue:(id)arg1 forContextKey:(id)arg2;
- (void)addItem:(id)arg1;
- (void)addItems:(id)arg1;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (void)setArtist:(id)arg1;
- (void)setDate:(id)arg1;
- (void)setDateRangeWithStartDate:(id)arg1 endDate:(id)arg2;
- (void)setEvent:(id)arg1;
- (void)setJourney:(id)arg1;
- (void)setSubjectLocation:(id)arg1;
- (void)setURL:(id)arg1;
- (void)setUserLocation:(id)arg1;
- (void)updateWithRepresentation:(id)arg1;

@end

