//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class NSString;

@interface BTNCustomer : BTNModelObject
{
    NSString *_customerId;
    NSString *_applicationId;
    NSString *_organizationId;
}

+ (_Bool)canInitWithDictionary:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *applicationId; // @synthesize applicationId=_applicationId;
@property(copy, nonatomic) NSString *customerId; // @synthesize customerId=_customerId;
- (id)dictionaryRepresentation;
- (_Bool)isEqualToCustomer:(id)arg1;
@property(copy, nonatomic) NSString *organizationId; // @synthesize organizationId=_organizationId;
- (void)updateWithRepresentation:(id)arg1;

@end

