//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "Button.h"
#import "ButtonDeprecated.h"

@class BAFNetworkReachabilityManager, BTNDebugLogger, BTNResourceProvider, BTNSession, NSCache, NSString;

@interface BTNCore : NSObject <Button, ButtonDeprecated>
{
    BTNResourceProvider *_resources;
    BTNDebugLogger *_logger;
    long long _environmentType;
    NSCache *_appActionCache;
    BAFNetworkReachabilityManager *_reachabilityManager;
    long long _networkStatus;
    long long _sessionRegistrationErrorCount;
    NSString *_preConfigurationUserIdentifier;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSCache *appActionCache; // @synthesize appActionCache=_appActionCache;
- (void)cacheAppAction:(id)arg1 forButtonId:(id)arg2 pubRef:(id)arg3 context:(id)arg4;
- (void)cacheCurrentSession;
- (id)cacheKeyWithButtonId:(id)arg1 pubRef:(id)arg2 context:(id)arg3;
- (id)cachedAppActionForButtonId:(id)arg1 pubRef:(id)arg2 context:(id)arg3;
- (_Bool)canFetchAppActionWithURL:(id)arg1;
- (id)capabilities;
- (void)captureURL:(id)arg1;
- (void)changeToEnvironmentType:(long long)arg1 applicationId:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)configureResourceProvider:(id)arg1 applicationId:(id)arg2;
- (void)configureWithApplicationId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)configureWithApplicationId:(id)arg1 userId:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)configureWithApplicationId:(id)arg1 userId:(id)arg2 resourceProvider:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)configureWithSession:(id)arg1;
- (_Bool)continueUserActivity:(id)arg1;
- (void)createNewSessionWithApplicationId:(id)arg1 userId:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (void)dispatchAppDetector;
@property(nonatomic) long long environmentType; // @synthesize environmentType=_environmentType;
- (void)fetchAppActionForButtonId:(id)arg1 context:(id)arg2 pubRef:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)fetchAppActionForMerchantId:(id)arg1 pubRef:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchAppActionForURL:(id)arg1 pubRef:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchAppActionWithButtonId:(id)arg1 context:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchAppActionWithButtonId:(id)arg1 context:(id)arg2 publisherReference:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)fetchAppActionWithMerchantId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchAppActionWithMerchantId:(id)arg1 publisherReference:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchAppActionWithURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchAppActionWithURL:(id)arg1 publisherReference:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)handleApplicationDidBecomeActiveNotification:(id)arg1;
- (void)handleApplicationDidReceiveIncomingURLNotification:(id)arg1;
- (void)handleClientNotAuthorizedNotification:(id)arg1;
- (void)handleLink:(id)arg1 appAction:(id)arg2;
- (void)handleNetworkBecameAvailableNotification:(id)arg1;
- (void)handleNewSessionWithCompletedRequests:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)handleURL:(id)arg1;
- (id)init;
- (_Bool)isAppToAppFlowPreferredForAppAction:(id)arg1;
- (_Bool)isInteractiveSetupEnabled;
- (_Bool)isValidApplicationId:(id)arg1;
- (void)loadRequiredAssetsForAppAction:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)logOut;
- (void)logOutWithCompletion:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) BTNDebugLogger *logger; // @synthesize logger=_logger;
- (void)networkBecameAvailable;
- (void)networkBecameUnavailable;
@property(nonatomic) long long networkStatus; // @synthesize networkStatus=_networkStatus;
- (void)openLink:(id)arg1 withAppAction:(id)arg2;
- (id)parametersWithButtonId:(id)arg1 context:(id)arg2 pubRef:(id)arg3;
- (void)persistUserIdentifier:(id)arg1;
@property(copy, nonatomic) NSString *preConfigurationUserIdentifier; // @synthesize preConfigurationUserIdentifier=_preConfigurationUserIdentifier;
- (void)presentAuthChallengeForAppAction:(id)arg1 link:(id)arg2;
- (void)presentCommerceCardWithAppAction:(id)arg1;
- (void)presentWebViewControllerWithLink:(id)arg1 appAction:(id)arg2;
- (void)putUserIdentifier;
@property(retain, nonatomic) BAFNetworkReachabilityManager *reachabilityManager; // @synthesize reachabilityManager=_reachabilityManager;
- (void)reconfigureWithCompletion:(CDUnknownBlockType)arg1;
- (id)referrerToken;
- (void)registerForSessionWithCompletion:(CDUnknownBlockType)arg1;
- (void)removeCachedSession;
- (void)reportEventWithName:(id)arg1 properties:(id)arg2;
- (void)reportOrderWithId:(id)arg1 currencyCode:(id)arg2 lineItems:(id)arg3;
- (void)reportOrderWithValue:(long long)arg1 orderId:(id)arg2 currencyCode:(id)arg3;
- (void)reportOrderWithValue:(long long)arg1 orderId:(id)arg2 currencyCode:(id)arg3 lineItems:(id)arg4;
- (void)resetButton;
@property(retain, nonatomic) BTNResourceProvider *resources; // @synthesize resources=_resources;
- (void)restoreCachedSession;
@property(readonly, copy, nonatomic) BTNSession *session;
@property(nonatomic) long long sessionRegistrationErrorCount; // @synthesize sessionRegistrationErrorCount=_sessionRegistrationErrorCount;
- (void)setDebugLoggingEnabled:(_Bool)arg1;
- (void)setUserIdentifier:(id)arg1;
- (void)setupNetworkReachability;
- (_Bool)shouldUpdateUserIdentifier:(id)arg1;
- (void)showBannerForMissingScheme:(id)arg1;
- (void)startObservingNotifications;
- (void)stopObservingNotifications;
- (void)updateLocalConfigurationWithCompletion:(CDUnknownBlockType)arg1;
- (id)userIdentifier;
- (void)willDisplayButtonWithId:(id)arg1 context:(id)arg2 completion:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

