//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNCardBody.h"

@class NSArray, NSNumber;

@interface BTNCardBodyList : BTNCardBody
{
    NSArray *_groups;
    NSNumber *_showGroupTitles;
}

+ (void)load;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
@property(readonly, copy, nonatomic) NSArray *groups; // @synthesize groups=_groups;
@property(readonly, copy, nonatomic) NSNumber *showGroupTitles; // @synthesize showGroupTitles=_showGroupTitles;
- (void)updateWithRepresentation:(id)arg1;

@end

