//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface BTNDebugLogger : NSObject
{
    long long _logLevel;
}

+ (id)sharedLogger;
- (id)assembledLogForMessage:(id)arg1 atLevel:(long long)arg2;
- (void)logInfoMessage:(id)arg1;
@property(nonatomic) long long logLevel; // @synthesize logLevel=_logLevel;
@property(readonly, nonatomic) NSDictionary *logLevelStringToType;
- (void)logPublicMessage:(id)arg1;
- (void)logStringToConsole:(id)arg1;
- (void)logVerboseMessage:(id)arg1;
- (void)logWithLevel:(long long)arg1 format:(id)arg2 arguments:(char *)arg3;
- (void)setLogLevelWithString:(id)arg1;

@end

