//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor, UIFont;

@protocol BTNDropinButtonAppearance <NSObject>

@optional
@property(retain, nonatomic) UIColor *borderColor;
@property(nonatomic) double borderWidth;
@property(nonatomic) unsigned long long contentAlignment;
@property(nonatomic) struct UIEdgeInsets contentInsets;
@property(nonatomic) double cornerRadius;
@property(retain, nonatomic) UIFont *font;
@property(retain, nonatomic) UIColor *highlightedBackgroundColor;
@property(retain, nonatomic) UIColor *highlightedTextColor;
@property(retain, nonatomic) UIColor *highlightedTintColor;
@property(nonatomic) double iconLabelSpacing;
@property(nonatomic) double iconSize;
@property(retain, nonatomic) UIColor *normalBackgroundColor;
@property(retain, nonatomic) UIFont *subtitleFont;
@property(nonatomic) unsigned long long subtitleTextCase;
@property(retain, nonatomic) UIColor *subtitleTextColor;
@property(nonatomic) unsigned long long textCase;
@property(retain, nonatomic) UIColor *textColor;
@property(retain, nonatomic) UIColor *tintColor;
@property(retain, nonatomic) UIFont *titleFont;
@property(nonatomic) unsigned long long titleTextCase;
@property(retain, nonatomic) UIColor *titleTextColor;
@end

