//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNRequestOperation.h"

@interface BTNEventRequest : BTNRequestOperation
{
}

+ (id)requestWithEvents:(id)arg1 resources:(id)arg2;
- (id)events;
- (void)main;
- (id)parametersForComparison;

@end

