//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BTNNotificationObserver.h"
#import "BTNResourceConsumer.h"

@class BTNResourceProvider, NSArray, NSString;

@interface BTNEventTrackingPolicy : NSObject <BTNResourceConsumer, BTNNotificationObserver>
{
    BTNResourceProvider *_resources;
    unsigned long long _maxQueuedEvents;
    double _flushDelay;
    double _minimumFlushInterval;
    NSArray *_triggerEvents;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) double flushDelay; // @synthesize flushDelay=_flushDelay;
- (void)handleConfigurationChange:(id)arg1;
- (id)initWithResources:(id)arg1;
@property(nonatomic) unsigned long long maxQueuedEvents; // @synthesize maxQueuedEvents=_maxQueuedEvents;
@property(nonatomic) double minimumFlushInterval; // @synthesize minimumFlushInterval=_minimumFlushInterval;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources; // @synthesize resources=_resources;
@property(copy, nonatomic) NSArray *triggerEvents; // @synthesize triggerEvents=_triggerEvents;
- (_Bool)shouldScheduleFlushForEvent:(id)arg1 lastFlushTime:(double)arg2;
- (void)startObservingNotifications;
- (void)stopObservingNotifications;
- (void)updateTriggerEvents;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

