//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class BTNBackground, BTNText;

@interface BTNHeader : BTNModelObject
{
    BTNText *_titleText;
    BTNText *_subtitleText;
    BTNBackground *_background;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) BTNBackground *background; // @synthesize background=_background;
- (id)dictionaryRepresentation;
@property(readonly, copy, nonatomic) BTNText *subtitleText; // @synthesize subtitleText=_subtitleText;
@property(readonly, copy, nonatomic) BTNText *titleText; // @synthesize titleText=_titleText;
- (void)updateWithRepresentation:(id)arg1;

@end

