//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIColor;

@interface BTNHighlightableButton : UIButton
{
    UIColor *_normalBackgroundColor;
    UIColor *_highlightedBackgroundColor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *highlightedBackgroundColor; // @synthesize highlightedBackgroundColor=_highlightedBackgroundColor;
@property(retain, nonatomic) UIColor *normalBackgroundColor; // @synthesize normalBackgroundColor=_normalBackgroundColor;
- (void)setBackgroundColor:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;

@end

