//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class BTNText, NSString, NSURL;

@interface BTNImage : BTNModelObject
{
    NSURL *_URL;
    BTNText *_altText;
    NSString *_fillModeString;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(readonly, copy, nonatomic) BTNText *altText; // @synthesize altText=_altText;
- (id)dictionaryRepresentation;
@property(readonly, nonatomic) long long fillMode;
@property(copy, nonatomic) NSString *fillModeString; // @synthesize fillModeString=_fillModeString;
- (void)updateWithRepresentation:(id)arg1;

@end

