//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNView.h"

@class UIImageView, UILabel;

@interface BTNInstallBannerView : BTNView
{
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_actionLabel;
}

+ (id)installBannerView;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *actionLabel; // @synthesize actionLabel=_actionLabel;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

