//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "BTNResourceConsumer.h"
#import "SKStoreProductViewControllerDelegate.h"

@class BTNExternalAction, BTNExternalActionPolicy, BTNInstallViewController, BTNResourceProvider, NSString;

@interface BTNInstallOperation : NSOperation <SKStoreProductViewControllerDelegate, BTNResourceConsumer>
{
    _Bool _isExecuting;
    _Bool _isFinished;
    _Bool _isBackgroundDetecting;
    BTNResourceProvider *_resources;
    BTNInstallViewController *_installViewController;
    double _currentDetectionInterval;
    unsigned long long _backgroundTaskIdentifier;
    CDUnknownBlockType _installCompletionHandler;
    BTNExternalAction *_externalAction;
    BTNExternalActionPolicy *_policy;
}

- (void).cxx_destruct;
- (void)attemptOpenURL;
@property(nonatomic) unsigned long long backgroundTaskIdentifier; // @synthesize backgroundTaskIdentifier=_backgroundTaskIdentifier;
- (_Bool)canPerformOperationWithError:(id *)arg1;
- (void)cancel;
@property(nonatomic) double currentDetectionInterval; // @synthesize currentDetectionInterval=_currentDetectionInterval;
- (void)dealloc;
- (void)endExecution;
@property(retain, nonatomic) BTNExternalAction *externalAction; // @synthesize externalAction=_externalAction;
- (void)finishWithError:(id)arg1;
- (void)forceCancelInstallDetectionIfNeeded;
- (void)handleUserAppStoreCancel;
- (void)handleUserDismiss;
- (id)initWithExternalAction:(id)arg1 policy:(id)arg2 resources:(id)arg3;
@property(copy, nonatomic) CDUnknownBlockType installCompletionHandler; // @synthesize installCompletionHandler=_installCompletionHandler;
@property(retain, nonatomic) BTNInstallViewController *installViewController; // @synthesize installViewController=_installViewController;
- (void)invokeAction;
- (_Bool)isAsynchronous;
@property(nonatomic) _Bool isBackgroundDetecting; // @synthesize isBackgroundDetecting=_isBackgroundDetecting;
- (_Bool)isExecuting;
- (_Bool)isFinished;
- (double)launchDelay;
@property(retain, nonatomic) BTNExternalActionPolicy *policy; // @synthesize policy=_policy;
- (void)presentAppStoreSheetWithCompletion:(CDUnknownBlockType)arg1;
- (void)presentInstallViewControllerWithCompletion:(CDUnknownBlockType)arg1;
- (void)queryCanOpenURL;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources; // @synthesize resources=_resources;
- (void)start;
- (void)startExecution;
- (void)startInstallDetection;
- (void)stopInstallDetection;
- (void)trackDeepLinkWithStatus:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

