//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, UIImageView, UILabel, UIView;

@interface BTNInventoryItemCell : UITableViewCell
{
    UIImageView *_iconView;
    UILabel *_primaryTextLabel;
    UILabel *_secondaryTextLabel;
    UILabel *_iconTextLabel;
    UIView *_contentWrapperView;
    NSLayoutConstraint *_primaryTextToIconConstraint;
    NSLayoutConstraint *_iconViewWidthConstraint;
}

+ (double)cellHeight;
+ (id)cellIdentifier;
+ (id)inventoryItemCell;
- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)configureWithInventoryItem:(id)arg1 loadIcon:(_Bool)arg2;
@property(nonatomic) __weak UIView *contentWrapperView; // @synthesize contentWrapperView=_contentWrapperView;
@property(retain, nonatomic) UILabel *iconTextLabel; // @synthesize iconTextLabel=_iconTextLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) __weak NSLayoutConstraint *iconViewWidthConstraint; // @synthesize iconViewWidthConstraint=_iconViewWidthConstraint;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)initializeCell;
@property(retain, nonatomic) UILabel *primaryTextLabel; // @synthesize primaryTextLabel=_primaryTextLabel;
@property(nonatomic) __weak NSLayoutConstraint *primaryTextToIconConstraint; // @synthesize primaryTextToIconConstraint=_primaryTextToIconConstraint;
@property(retain, nonatomic) UILabel *secondaryTextLabel; // @synthesize secondaryTextLabel=_secondaryTextLabel;

@end

