//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNBaseViewController.h"

#import "BTNResourceConsumer.h"
#import "SKStoreProductViewControllerDelegate.h"

@class BTNAppActionMeta, BTNAppInstallView, BTNResourceProvider, BTNSimulatorInstallView, BTNStorePresentationController, NSString, SKStoreProductViewController, UIView, UIWindow;

@interface BTNInstallViewController : BTNBaseViewController <BTNResourceConsumer, SKStoreProductViewControllerDelegate>
{
    _Bool _isCancelled;
    BTNResourceProvider *_resources;
    SKStoreProductViewController *_storeController;
    BTNAppActionMeta *_meta;
    UIWindow *_installWindow;
    UIView *_blurView;
    UIView *_contentView;
    BTNAppInstallView *_installView;
    BTNSimulatorInstallView *_simulatorView;
    BTNStorePresentationController *_storePresentationController;
    CDUnknownBlockType _userDismissActionHandler;
}

+ (void)reset;
+ (void)setStoreClass:(Class)arg1;
+ (id)visibleInstallViewController;
- (void).cxx_destruct;
- (void)attribute;
@property(retain, nonatomic) UIView *blurView; // @synthesize blurView=_blurView;
- (void)configureContentView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void)controllerDidDismiss;
- (void)controllerWillShow;
- (void)dealloc;
- (void)dismissAppStoreWithCompletion:(CDUnknownBlockType)arg1;
- (void)dismissViewOnlyWithCompletion:(CDUnknownBlockType)arg1;
- (void)dismissWithCompletion:(CDUnknownBlockType)arg1;
- (void)handleAppStoreCancel;
- (void)handleUserInitiatedDismiss;
- (id)initWithMetadata:(id)arg1 resources:(id)arg2;
@property(retain, nonatomic) BTNAppInstallView *installView; // @synthesize installView=_installView;
@property(retain, nonatomic) UIWindow *installWindow; // @synthesize installWindow=_installWindow;
@property(nonatomic) _Bool isCancelled; // @synthesize isCancelled=_isCancelled;
- (_Bool)isUsingLiveBlur;
- (void)loadAppStoreWithCompletion:(CDUnknownBlockType)arg1;
- (void)loadView;
@property(retain, nonatomic) BTNAppActionMeta *meta; // @synthesize meta=_meta;
- (long long)preferredStatusBarStyle;
- (void)presentAppStoreSheetWithCompletion:(CDUnknownBlockType)arg1;
- (void)productViewControllerDidFinish:(id)arg1;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources; // @synthesize resources=_resources;
@property(retain, nonatomic) BTNSimulatorInstallView *simulatorView; // @synthesize simulatorView=_simulatorView;
@property(retain, nonatomic) SKStoreProductViewController *storeController; // @synthesize storeController=_storeController;
@property(retain, nonatomic) BTNStorePresentationController *storePresentationController; // @synthesize storePresentationController=_storePresentationController;
@property(copy, nonatomic) CDUnknownBlockType userDismissActionHandler; // @synthesize userDismissActionHandler=_userDismissActionHandler;
- (void)showWithCompletion:(CDUnknownBlockType)arg1;
- (void)viewWillLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

