//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSLayoutConstraint, NSString, UIImageView, UILabel, UIView;

@interface BTNInteractiveButtonInventoryCell : UICollectionViewCell
{
    NSString *_fontName;
    long long _relativeFontPointSize;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIImageView *_imageView;
    UILabel *_iconLabel;
    double _titleLabelDefaultPointSize;
    double _subtitleLabelDefaultPointSize;
    double _iconTextLabelDefaultPointSize;
    UIView *_titleLoadingView;
    UIView *_subtitleLoadingView;
    NSLayoutConstraint *_titleLabelTopToSuperviewConstraint;
    double _iconViewToIconLabelSpacingDefault;
    NSLayoutConstraint *_iconViewToIconLabelSpacingConstraint;
}

+ (id)reuseIdentifier;
- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)clearData;
- (void)configureWithListItem:(id)arg1;
@property(copy, nonatomic) NSString *fontName; // @synthesize fontName=_fontName;
@property(nonatomic) __weak UILabel *iconLabel; // @synthesize iconLabel=_iconLabel;
@property(nonatomic) double iconTextLabelDefaultPointSize; // @synthesize iconTextLabelDefaultPointSize=_iconTextLabelDefaultPointSize;
@property(nonatomic) __weak NSLayoutConstraint *iconViewToIconLabelSpacingConstraint; // @synthesize iconViewToIconLabelSpacingConstraint=_iconViewToIconLabelSpacingConstraint;
@property(nonatomic) double iconViewToIconLabelSpacingDefault; // @synthesize iconViewToIconLabelSpacingDefault=_iconViewToIconLabelSpacingDefault;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
- (void)prepareForReuse;
@property(nonatomic) long long relativeFontPointSize; // @synthesize relativeFontPointSize=_relativeFontPointSize;
- (void)setHighlighted:(_Bool)arg1;
@property(nonatomic) __weak UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(nonatomic) double subtitleLabelDefaultPointSize; // @synthesize subtitleLabelDefaultPointSize=_subtitleLabelDefaultPointSize;
@property(nonatomic) __weak UIView *subtitleLoadingView; // @synthesize subtitleLoadingView=_subtitleLoadingView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) double titleLabelDefaultPointSize; // @synthesize titleLabelDefaultPointSize=_titleLabelDefaultPointSize;
@property(nonatomic) __weak NSLayoutConstraint *titleLabelTopToSuperviewConstraint; // @synthesize titleLabelTopToSuperviewConstraint=_titleLabelTopToSuperviewConstraint;
@property(nonatomic) __weak UIView *titleLoadingView; // @synthesize titleLoadingView=_titleLoadingView;
- (void)transitionFromLoadingState;
- (void)transitionToLoadingState;

@end

