//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class BTNHeader, NSArray, NSLayoutConstraint, NSString, UICollectionView, UIImageView, UILabel, UIPageControl;

@interface BTNInventoryHeaderView : BTNView <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
{
    UIImageView *_backgroundImageView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UICollectionView *_groupNameCollectionView;
    UIPageControl *_pageIndicator;
    NSArray *_groupTitles;
    BTNHeader *_headerData;
    CDUnknownBlockType _selectedGroupChangedBlock;
    NSLayoutConstraint *_pageControlHeight;
    NSLayoutConstraint *_labelTopToSuperviewTop;
    NSLayoutConstraint *_labelBottomToPageControlTop;
    NSArray *_computedCellWidths;
    double _maxCellWidth;
    long long _currentSelectedIndex;
}

+ (id)inventoryHeaderView;
- (void).cxx_destruct;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)computeCellWidthsForGroupTitles:(id)arg1;
@property(retain, nonatomic) NSArray *computedCellWidths; // @synthesize computedCellWidths=_computedCellWidths;
@property(nonatomic) long long currentSelectedIndex; // @synthesize currentSelectedIndex=_currentSelectedIndex;
@property(nonatomic) __weak UICollectionView *groupNameCollectionView; // @synthesize groupNameCollectionView=_groupNameCollectionView;
@property(copy, nonatomic) NSArray *groupTitles; // @synthesize groupTitles=_groupTitles;
@property(retain, nonatomic) BTNHeader *headerData; // @synthesize headerData=_headerData;
@property(nonatomic) __weak NSLayoutConstraint *labelBottomToPageControlTop; // @synthesize labelBottomToPageControlTop=_labelBottomToPageControlTop;
@property(nonatomic) __weak NSLayoutConstraint *labelTopToSuperviewTop; // @synthesize labelTopToSuperviewTop=_labelTopToSuperviewTop;
@property(nonatomic) double maxCellWidth; // @synthesize maxCellWidth=_maxCellWidth;
@property(nonatomic) __weak NSLayoutConstraint *pageControlHeight; // @synthesize pageControlHeight=_pageControlHeight;
@property(nonatomic) __weak UIPageControl *pageIndicator; // @synthesize pageIndicator=_pageIndicator;
- (void)scrollToGroupAtIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
@property(copy, nonatomic) CDUnknownBlockType selectedGroupChangedBlock; // @synthesize selectedGroupChangedBlock=_selectedGroupChangedBlock;
@property(nonatomic) __weak UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)swipeGestureHandler:(id)arg1;
- (void)tapGestureHandler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

