//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNBaseEntity.h"

@class NSDictionary;

@interface BTNJourney : BTNBaseEntity
{
}

- (id)dictionaryRepresentation;
- (void)setDestinationLocation:(id)arg1;
- (void)setEndTime:(id)arg1;
- (void)setStartLocation:(id)arg1;
- (void)setStartTime:(id)arg1;
- (void)setTransportType:(long long)arg1;
@property(readonly, nonatomic) NSDictionary *transportTypeStringMap;
- (void)updateWithRepresentation:(id)arg1;

@end

