//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class NSURL;

@interface BTNLink : BTNModelObject
{
    NSURL *_appLink;
    NSURL *_webLink;
}

+ (_Bool)canInitWithDictionary:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSURL *appLink; // @synthesize appLink=_appLink;
- (id)dictionaryRepresentation;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (void)updateWithRepresentation:(id)arg1;
@property(readonly, copy, nonatomic) NSURL *webLink; // @synthesize webLink=_webLink;

@end

