//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNBaseEntity.h"

@interface BTNLocation : BTNBaseEntity
{
}

+ (id)locationWithLatitude:(double)arg1 longitude:(double)arg2;
+ (id)locationWithName:(id)arg1 latitude:(double)arg2 longitude:(double)arg3;
- (id)dictionaryRepresentation;
- (void)setAddressLine:(id)arg1;
- (void)setCity:(id)arg1;
- (void)setCountry:(id)arg1;
- (void)setLatitude:(double)arg1;
- (void)setLongitude:(double)arg1;
- (void)setState:(id)arg1;
- (void)setZip:(id)arg1;
- (void)updateWithRepresentation:(id)arg1;

@end

