//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BTNResourceConsumer.h"
#import "CLLocationManagerDelegate.h"

@class BTNLocationRequestController, BTNResourceProvider, CLLocationManager, NSMutableArray, NSString, UIColor;

@interface BTNLocationManager : NSObject <CLLocationManagerDelegate, BTNResourceConsumer>
{
    int _currentAuthorizationStatus;
    BTNResourceProvider *_resources;
    double _locationStalenessThreshold;
    double _locationUpdateTimeout;
    CLLocationManager *_locationManager;
    NSMutableArray *_completionHandlers;
    UIColor *_primaryColor;
    BTNLocationRequestController *_requestController;
}

+ (void)allowButtonToRequestLocationPermission:(_Bool)arg1;
+ (_Bool)isPermissionDenied;
+ (_Bool)isPermissionGranted;
+ (_Bool)isPermissionRequested;
- (void).cxx_destruct;
- (void)activateWithLocationManager:(id)arg1;
- (void)beginLocatingDevice;
- (id)buttonPermissionError;
- (void)completeWithLocation:(id)arg1 error:(id)arg2;
@property(retain, nonatomic) NSMutableArray *completionHandlers; // @synthesize completionHandlers=_completionHandlers;
@property(nonatomic) int currentAuthorizationStatus; // @synthesize currentAuthorizationStatus=_currentAuthorizationStatus;
- (void)deactivate;
- (void)dealloc;
- (void)deleteLocationManager;
- (void)handleTimeout;
- (id)initWithLocationManager:(id)arg1 resources:(id)arg2;
- (id)initWithResources:(id)arg1;
- (void)locateDeviceWithCompletion:(CDUnknownBlockType)arg1;
- (void)locateDeviceWithCompletion:(CDUnknownBlockType)arg1 allowPermissionModal:(_Bool)arg2;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManagerDidPauseLocationUpdates:(id)arg1;
@property(nonatomic) double locationStalenessThreshold; // @synthesize locationStalenessThreshold=_locationStalenessThreshold;
@property(nonatomic) double locationUpdateTimeout; // @synthesize locationUpdateTimeout=_locationUpdateTimeout;
@property(retain, nonatomic) UIColor *primaryColor; // @synthesize primaryColor=_primaryColor;
@property(retain, nonatomic) BTNLocationRequestController *requestController; // @synthesize requestController=_requestController;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources; // @synthesize resources=_resources;
- (void)setupWithLocationManager:(id)arg1;
- (id)userPermissionError;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

