//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNView.h"

@class UIButton, UIImageView, UILabel;

@interface BTNLocationRequestView : BTNView
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIImageView *_headerImageView;
    UILabel *_messageLabel;
    UIButton *_button;
}

+ (id)locationRequestView;
- (void).cxx_destruct;
- (void)awakeFromNib;
@property(nonatomic) __weak UIButton *button; // @synthesize button=_button;
@property(nonatomic) __weak UIImageView *headerImageView; // @synthesize headerImageView=_headerImageView;
@property(nonatomic) __weak UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
- (void)setButtonTitle:(id)arg1;
- (void)setMessage:(id)arg1;
- (void)setPrimaryColor:(id)arg1;
@property(nonatomic) __weak UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
- (void)setTarget:(id)arg1 forAction:(SEL)arg2;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

