//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BTNNotificationObserver.h"
#import "BTNResourceConsumer.h"

@class BTNDiskBackingStore, BTNResourceProvider, NSCache, NSObject<OS_dispatch_queue>, NSString;

@interface BTNLRUCache : NSObject <BTNResourceConsumer, BTNNotificationObserver>
{
    NSString *_cachePath;
    NSObject<OS_dispatch_queue> *_cacheQueue;
    BTNResourceProvider *_resources;
    NSString *_cacheName;
    NSObject<OS_dispatch_queue> *_completionQueue;
    unsigned long long _diskCapacity;
    unsigned long long _maxWriteSize;
    NSCache *_memoryCache;
    BTNDiskBackingStore *_backingStore;
}

- (void).cxx_destruct;
@property(retain, nonatomic) BTNDiskBackingStore *backingStore; // @synthesize backingStore=_backingStore;
@property(readonly, copy, nonatomic) NSString *cacheName; // @synthesize cacheName=_cacheName;
@property(readonly, nonatomic) NSString *cachePath; // @synthesize cachePath=_cachePath;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *cacheQueue; // @synthesize cacheQueue=_cacheQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *completionQueue; // @synthesize completionQueue=_completionQueue;
- (void)configurationDidChangeNotification:(id)arg1;
- (void)dealloc;
@property(nonatomic) unsigned long long diskCapacity; // @synthesize diskCapacity=_diskCapacity;
- (void)evictUntilBytesAvailable:(unsigned long long)arg1;
- (id)init;
- (id)initWithName:(id)arg1 resources:(id)arg2;
- (_Bool)isDataDiskCacheable:(id)arg1;
- (_Bool)isDiskSpaceAvailableForData:(id)arg1;
@property(nonatomic) unsigned long long maxWriteSize; // @synthesize maxWriteSize=_maxWriteSize;
@property(readonly, nonatomic) NSCache *memoryCache; // @synthesize memoryCache=_memoryCache;
- (void)objectForKey:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)objectFromDiskCacheWithKey:(id)arg1;
- (id)objectFromMemoryCacheWithKey:(id)arg1;
- (void)removeAllObjectsWithCompletion:(CDUnknownBlockType)arg1;
- (void)removeObjectForKey:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources; // @synthesize resources=_resources;
- (void)setObject:(id)arg1 forKey:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)startObservingNotifications;
- (void)stopObservingNotifications;
- (_Bool)writeObject:(id)arg1 forKey:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

