//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class NSMutableDictionary, NSString;

@interface BTNLineItem : BTNModelObject
{
    NSString *_identifier;
    long long _amount;
    long long _quantity;
    NSString *_itemDescription;
    NSMutableDictionary *_mutableAttributes;
}

+ (_Bool)canInitWithDictionary:(id)arg1;
+ (id)lineItemWithId:(id)arg1 amount:(long long)arg2;
+ (id)lineItemWithId:(id)arg1 amount:(long long)arg2 quantity:(long long)arg3;
+ (id)lineItemWithId:(id)arg1 amount:(long long)arg2 quantity:(long long)arg3 description:(id)arg4;
- (void).cxx_destruct;
- (void)addAttribute:(id)arg1 forKey:(id)arg2;
@property(readonly, nonatomic) long long amount; // @synthesize amount=_amount;
- (id)attributes;
- (id)dictionaryRepresentation;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithId:(id)arg1 amount:(long long)arg2 quantity:(long long)arg3 description:(id)arg4;
@property(readonly, copy, nonatomic) NSString *itemDescription; // @synthesize itemDescription=_itemDescription;
@property(retain, nonatomic) NSMutableDictionary *mutableAttributes; // @synthesize mutableAttributes=_mutableAttributes;
@property(readonly, nonatomic) long long quantity; // @synthesize quantity=_quantity;
- (void)updateWithRepresentation:(id)arg1;

@end

