//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class BTNImage, BTNLink, BTNText;

@interface BTNListItem : BTNModelObject
{
    BTNText *_titleText;
    BTNText *_subtitleText;
    BTNText *_iconText;
    BTNImage *_iconImage;
    BTNLink *_action;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) BTNLink *action; // @synthesize action=_action;
- (id)dictionaryRepresentation;
@property(readonly, copy, nonatomic) BTNImage *iconImage; // @synthesize iconImage=_iconImage;
@property(readonly, copy, nonatomic) BTNText *iconText; // @synthesize iconText=_iconText;
@property(readonly, copy, nonatomic) BTNText *subtitleText; // @synthesize subtitleText=_subtitleText;
@property(readonly, copy, nonatomic) BTNText *titleText; // @synthesize titleText=_titleText;
- (void)updateWithRepresentation:(id)arg1;

@end

