//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNBaseModalController.h"

@class BTNLocationRequestView, UIColor;

@interface BTNLocationRequestController : BTNBaseModalController
{
    UIColor *_primaryColor;
    BTNLocationRequestView *_locationRequestView;
}

- (void).cxx_destruct;
- (void)configureForDeniedState;
- (void)configureForRequestState;
- (void)grantAction:(id)arg1;
@property(retain, nonatomic) BTNLocationRequestView *locationRequestView; // @synthesize locationRequestView=_locationRequestView;
- (void)openSettingsAction:(id)arg1;
@property(retain, nonatomic) UIColor *primaryColor; // @synthesize primaryColor=_primaryColor;
- (void)trackOpenSettings;
- (void)trackPermissionAllow;
- (void)viewDidLoad;

@end

