//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class NSNumber, NSString;

@interface BTNPrefersApp : BTNModelObject
{
    NSString *_color;
    NSNumber *_defaultState;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *color; // @synthesize color=_color;
@property(readonly, nonatomic) NSNumber *defaultState; // @synthesize defaultState=_defaultState;
- (id)dictionaryRepresentation;
- (void)updateWithRepresentation:(id)arg1;

@end

