//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BTNPreferredActionType : NSObject
{
    NSString *_type;
}

+ (id)actionTypeWithString:(id)arg1;
- (void).cxx_destruct;
- (id)initWithString:(id)arg1;
- (_Bool)isAppType;
- (_Bool)isExternalWebType;
- (_Bool)isInternalWebType;
@property(readonly, copy, nonatomic) NSString *type; // @synthesize type=_type;

@end

