//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BAFJSONRequestSerializer.h"

#import "BTNResourceConsumer.h"

@class BTNResourceProvider, NSString;

@interface BTNRequestSerializer : BAFJSONRequestSerializer <BTNResourceConsumer>
{
    BTNResourceProvider *_resources;
    NSString *_sessionId;
}

+ (id)serializerWithResources:(id)arg1;
- (void).cxx_destruct;
- (id)initWithResources:(id)arg1;
- (id)requestBySerializingRequest:(id)arg1 withParameters:(id)arg2 error:(id *)arg3;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources; // @synthesize resources=_resources;
@property(copy) NSString *sessionId; // @synthesize sessionId=_sessionId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

