//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BAFJSONResponseSerializer.h"

#import "BTNResourceConsumer.h"

@class BTNResourceProvider, NSString;

@interface BTNResponseSerializer : BAFJSONResponseSerializer <BTNResourceConsumer>
{
    BTNResourceProvider *_resources;
}

- (void).cxx_destruct;
- (id)initWithResources:(id)arg1;
- (id)objectsFromResponse:(id)arg1 responseObject:(id)arg2 error:(id *)arg3;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources; // @synthesize resources=_resources;
- (id)responseObjectForResponse:(id)arg1 data:(id)arg2 error:(id *)arg3;
- (_Bool)validateResponse:(id)arg1 data:(id)arg2 error:(id *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

