//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BTNResourceConsumer.h"

@class BTNResourceProvider, NSIndexSet, NSOperationQueue, NSString;

@interface BTNRequestCoordinator : NSObject <BTNResourceConsumer>
{
    BTNResourceProvider *_resources;
    NSIndexSet *_acceptableStatusCodes;
    NSIndexSet *_permanentFailureCodes;
    NSOperationQueue *_requestOperationQueue;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSIndexSet *acceptableStatusCodes; // @synthesize acceptableStatusCodes=_acceptableStatusCodes;
- (void)enqueueOperation:(id)arg1;
- (void)enqueueOperations:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)initWithResources:(id)arg1;
- (_Bool)isValidOperation:(id)arg1;
@property(copy, nonatomic) NSIndexSet *permanentFailureCodes; // @synthesize permanentFailureCodes=_permanentFailureCodes;
- (void)prepareOperation:(id)arg1;
@property(readonly, nonatomic) NSOperationQueue *requestOperationQueue; // @synthesize requestOperationQueue=_requestOperationQueue;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources; // @synthesize resources=_resources;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

