//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "BTNMutableResourceConsumer.h"
#import "BTNResourceConsumer.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class BAFHTTPRequestOperationManager, BTNResourceProvider, NSDictionary, NSError, NSHTTPURLResponse, NSString;

@interface BTNRequestOperation : NSOperation <BTNMutableResourceConsumer, BTNResourceConsumer, NSCoding, NSCopying>
{
    _Bool _isExecuting;
    _Bool _isFinished;
    BTNResourceProvider *_resources;
    NSString *_identifier;
    double _created;
    NSString *_HTTPMethod;
    NSString *_URLString;
    NSDictionary *_parameters;
    NSHTTPURLResponse *_response;
    id _responseObject;
    NSError *_error;
    BAFHTTPRequestOperationManager *_requestManager;
    CDUnknownBlockType _requestCompletionBlock;
}

+ (id)requestWithResources:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *HTTPMethod; // @synthesize HTTPMethod=_HTTPMethod;
@property(readonly, copy, nonatomic) NSString *URLString; // @synthesize URLString=_URLString;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) double created; // @synthesize created=_created;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
- (void)finish;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithCoder:(id)arg1;
- (id)initWithHTTPMethod:(id)arg1 URLString:(id)arg2 parameters:(id)arg3 resources:(id)arg4;
- (id)initWithIdentifier:(id)arg1 created:(double)arg2 HTTPMethod:(id)arg3 URLString:(id)arg4 parameters:(id)arg5 resources:(id)arg6;
- (id)initWithResources:(id)arg1;
- (_Bool)isAsynchronous;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToRequestOperation:(id)arg1;
- (_Bool)isExecuting;
- (_Bool)isFinished;
- (void)main;
@property(copy, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
- (id)parametersForComparison;
@property(copy, nonatomic) CDUnknownBlockType requestCompletionBlock; // @synthesize requestCompletionBlock=_requestCompletionBlock;
@property(retain, nonatomic) BAFHTTPRequestOperationManager *requestManager; // @synthesize requestManager=_requestManager;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources;
@property(retain, nonatomic) NSHTTPURLResponse *response; // @synthesize response=_response;
@property(retain, nonatomic) id responseObject; // @synthesize responseObject=_responseObject;
- (void)setResources:(id)arg1;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

