//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BTNAppDetector, BTNAttributionManager, BTNConfiguration, BTNCore, BTNDebugLogger, BTNEnvironment, BTNEventTracker, BTNExternalActionManager, BTNImageRequestCoordinator, BTNKeychain, BTNLocationManager, BTNReliableRequestCoordinator, BTNRequestCoordinator, BTNRequestManager, BTNSession, BTNURLMatcher, BTNUserDefaults, NSBundle, NSFileManager, NSLocale, NSNotificationCenter, NSNumber, NSString, UIApplication, UIDevice, UIScreen;

@interface BTNResourceProvider : NSObject
{
    BTNCore *_core;
    BTNSession *_session;
    BTNDebugLogger *_logger;
    BTNUserDefaults *_userDefaults;
    BTNEnvironment *_environment;
    BTNKeychain *_keychain;
    BTNConfiguration *_configuration;
    BTNEventTracker *_eventTracker;
    BTNRequestManager *_requestManager;
    BTNRequestCoordinator *_requestCoordinator;
    BTNReliableRequestCoordinator *_reliableRequestCoordinator;
    BTNImageRequestCoordinator *_imageRequestCoordinator;
    BTNLocationManager *_locationManager;
    BTNAttributionManager *_attributionManager;
    BTNExternalActionManager *_externalActionManager;
    BTNAppDetector *_appDetector;
    BTNURLMatcher *_urlMatcher;
    UIApplication *_sharedApplication;
    UIScreen *_mainScreen;
    UIDevice *_currentDevice;
    NSLocale *_currentLocale;
    NSBundle *_mainBundle;
    NSNotificationCenter *_privateNotificationCenter;
    NSNotificationCenter *_defaultNotificationCenter;
    NSFileManager *_fileManager;
    NSString *_localeStringReturnValue;
    NSNumber *_canOpenURLReturnValue;
    NSNumber *_openURLReturnValue;
    NSString *_systemVersionReturnValue;
    NSNumber *_applicationStateReturnValue;
}

- (void).cxx_destruct;
- (id)UUIDString;
- (id)advertisingIdentifier;
@property(retain, nonatomic) BTNAppDetector *appDetector; // @synthesize appDetector=_appDetector;
@property(readonly, copy, nonatomic) NSString *applicationId;
- (long long)applicationState;
@property(copy, nonatomic) NSNumber *applicationStateReturnValue; // @synthesize applicationStateReturnValue=_applicationStateReturnValue;
- (id)appsByFilteringAvailabilityOfApps:(id)arg1 available:(_Bool)arg2;
@property(retain, nonatomic) BTNAttributionManager *attributionManager; // @synthesize attributionManager=_attributionManager;
- (id)availableApps:(id)arg1;
- (_Bool)canOpenURL:(id)arg1;
@property(copy, nonatomic) NSNumber *canOpenURLReturnValue; // @synthesize canOpenURLReturnValue=_canOpenURLReturnValue;
@property(retain, nonatomic) BTNConfiguration *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) __weak BTNCore *core; // @synthesize core=_core;
- (id)country;
- (void)createAppDetector;
- (void)createAttributionManager;
- (void)createConfiguration;
- (void)createEventTracker;
- (void)createExternalActionManager;
- (void)createImageRequestCoordinator;
- (void)createKeychain;
- (void)createLocationManager;
- (void)createPrivateNotificationCenter;
- (void)createReliableRequestCoordinator;
- (void)createRequestCoordinator;
- (void)createRequestManager;
- (void)createURLMatcher;
- (void)createUserDefaults;
@property(retain, nonatomic) UIDevice *currentDevice; // @synthesize currentDevice=_currentDevice;
@property(retain, nonatomic) NSLocale *currentLocale; // @synthesize currentLocale=_currentLocale;
- (id)dateTimeNow;
- (void)dealloc;
@property(retain, nonatomic) NSNotificationCenter *defaultNotificationCenter; // @synthesize defaultNotificationCenter=_defaultNotificationCenter;
@property(retain, nonatomic) BTNEnvironment *environment; // @synthesize environment=_environment;
@property(retain, nonatomic) BTNEventTracker *eventTracker; // @synthesize eventTracker=_eventTracker;
@property(retain, nonatomic) BTNExternalActionManager *externalActionManager; // @synthesize externalActionManager=_externalActionManager;
@property(retain, nonatomic) NSFileManager *fileManager; // @synthesize fileManager=_fileManager;
- (void)handleDefaultCenterNotification:(id)arg1;
@property(retain, nonatomic) BTNImageRequestCoordinator *imageRequestCoordinator; // @synthesize imageRequestCoordinator=_imageRequestCoordinator;
- (id)initEmptyWithDefaultCenter:(id)arg1;
- (id)initWithEnvironment:(id)arg1;
- (id)initWithEnvironment:(id)arg1 defaultCenter:(id)arg2;
- (_Bool)isAdvertisingTrackingEnabled;
- (_Bool)isAppStoreBuild;
- (_Bool)isSimulatorBuild;
- (_Bool)isSmallDevice;
- (_Bool)isSystemVersionGreaterThanOrEqualTo:(id)arg1;
@property(retain, nonatomic) BTNKeychain *keychain; // @synthesize keychain=_keychain;
- (id)localeString;
@property(copy, nonatomic) NSString *localeStringReturnValue; // @synthesize localeStringReturnValue=_localeStringReturnValue;
@property(retain, nonatomic) BTNLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) BTNDebugLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) NSBundle *mainBundle; // @synthesize mainBundle=_mainBundle;
@property(retain, nonatomic) UIScreen *mainScreen; // @synthesize mainScreen=_mainScreen;
- (_Bool)openURL:(id)arg1;
@property(copy, nonatomic) NSNumber *openURLReturnValue; // @synthesize openURLReturnValue=_openURLReturnValue;
- (id)preferredLanguage;
@property(retain, nonatomic) NSNotificationCenter *privateNotificationCenter; // @synthesize privateNotificationCenter=_privateNotificationCenter;
@property(retain, nonatomic) BTNReliableRequestCoordinator *reliableRequestCoordinator; // @synthesize reliableRequestCoordinator=_reliableRequestCoordinator;
@property(retain, nonatomic) BTNRequestCoordinator *requestCoordinator; // @synthesize requestCoordinator=_requestCoordinator;
@property(retain, nonatomic) BTNRequestManager *requestManager; // @synthesize requestManager=_requestManager;
- (id)sdkVersion;
@property(retain, nonatomic) BTNSession *session; // @synthesize session=_session;
@property(retain, nonatomic) UIApplication *sharedApplication; // @synthesize sharedApplication=_sharedApplication;
@property(copy, nonatomic) NSString *systemVersionReturnValue; // @synthesize systemVersionReturnValue=_systemVersionReturnValue;
@property(retain, nonatomic) BTNURLMatcher *urlMatcher; // @synthesize urlMatcher=_urlMatcher;
@property(retain, nonatomic) BTNUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
- (id)systemVersion;
- (id)unavailableApps:(id)arg1;
- (id)unqueryableApps:(id)arg1;
- (long long)userInterfaceIdiom;

@end

