//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface BTNSimulatorInstallView : UIView
{
    CDUnknownBlockType _dismissActionHandler;
}

- (void).cxx_destruct;
- (void)dismissAction:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType dismissActionHandler; // @synthesize dismissActionHandler=_dismissActionHandler;
- (id)init;

@end

