//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNView.h"

@class BTNPreview, UIColor, UIFont, UIImageView, UILabel, UIView;

@interface BTNStandardButtonView : BTNView
{
    _Bool _highlighted;
    UIImageView *_imageView;
    UIView *_labelContainerView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    BTNPreview *_preview;
    double _iconSize;
    double _iconLabelSpacing;
    UIFont *_font;
    UIFont *_titleFont;
    UIFont *_subtitleFont;
    unsigned long long _textCase;
    unsigned long long _titleTextCase;
    unsigned long long _subtitleTextCase;
    UIColor *_tintColor;
    UIColor *_highlightedTintColor;
    UIColor *_titleTextColor;
    UIColor *_subtitleTextColor;
    UIColor *_textColor;
    UIColor *_highlightedTextColor;
    UIFont *_defaultFont;
}

- (void).cxx_destruct;
- (void)configureWithPreview:(id)arg1 iconImage:(id)arg2;
@property(retain, nonatomic) UIFont *defaultFont; // @synthesize defaultFont=_defaultFont;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
- (id)fontWithPriorityFont:(id)arg1;
@property(retain, nonatomic) UIColor *highlightedTextColor; // @synthesize highlightedTextColor=_highlightedTextColor;
@property(retain, nonatomic) UIColor *highlightedTintColor; // @synthesize highlightedTintColor=_highlightedTintColor;
@property(nonatomic) double iconLabelSpacing; // @synthesize iconLabelSpacing=_iconLabelSpacing;
@property(nonatomic) double iconSize; // @synthesize iconSize=_iconSize;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void)initializeView;
@property(nonatomic, getter=isHighlighted) _Bool highlighted; // @synthesize highlighted=_highlighted;
- (_Bool)isVisible;
@property(retain, nonatomic) UIView *labelContainerView; // @synthesize labelContainerView=_labelContainerView;
@property(readonly, nonatomic) BTNPreview *preview; // @synthesize preview=_preview;
- (void)setFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIFont *subtitleFont; // @synthesize subtitleFont=_subtitleFont;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(nonatomic) unsigned long long subtitleTextCase; // @synthesize subtitleTextCase=_subtitleTextCase;
@property(retain, nonatomic) UIColor *subtitleTextColor; // @synthesize subtitleTextColor=_subtitleTextColor;
@property(nonatomic) unsigned long long textCase; // @synthesize textCase=_textCase;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) unsigned long long titleTextCase; // @synthesize titleTextCase=_titleTextCase;
@property(retain, nonatomic) UIColor *titleTextColor; // @synthesize titleTextColor=_titleTextColor;
- (id)stringWithTextCase:(unsigned long long)arg1 text:(id)arg2;
- (id)textColorWithPriorityColor:(id)arg1 defaultColor:(id)arg2;
- (void)updateConstraints;

@end

