//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class NSString;

@interface BTNText : BTNModelObject
{
    NSString *_text;
    NSString *_color;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *color; // @synthesize color=_color;
- (id)dictionaryRepresentation;
@property(readonly, copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void)updateWithRepresentation:(id)arg1;

@end

