//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNBannerViewController.h"

@class NSString;

@interface BTNTextBannerController : BTNBannerViewController
{
    NSString *_titleText;
    NSString *_subtitleText;
    NSString *_highlightedText;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *highlightedText; // @synthesize highlightedText=_highlightedText;
@property(copy, nonatomic) NSString *subtitleText; // @synthesize subtitleText=_subtitleText;
@property(copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
- (void)viewDidLoad;

@end

