//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BTNResourceConsumer.h"

@class BTNResourceProvider, NSString;

@interface BTNURLMatcher : NSObject <BTNResourceConsumer>
{
    BTNResourceProvider *_resources;
}

+ (id)matcherWithResources:(id)arg1;
- (void).cxx_destruct;
- (id)affiliateForHostname:(id)arg1;
- (id)buttonPartnerDomainForURL:(id)arg1;
- (_Bool)canExchangeURL:(id)arg1 error:(id *)arg2;
- (id)hostnameByRemovingWWWFromHostname:(id)arg1;
- (id)initWithResources:(id)arg1;
- (_Bool)isFullLengthPatternMatching:(id)arg1 forString:(id)arg2;
- (_Bool)matchesHostname:(id)arg1;
- (_Bool)matchesHostnameForAffiliateURL:(id)arg1;
- (_Bool)matchesMerchantIdForAffiliateURL:(id)arg1;
- (_Bool)matchesSubdomain:(id)arg1;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources; // @synthesize resources=_resources;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

