//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface BTNView : UIView
{
    _Bool _forceOpacity;
    struct CGSize _currentSize;
}

@property(nonatomic) struct CGSize currentSize; // @synthesize currentSize=_currentSize;
- (void)didAppear;
- (void)didDisappear;
- (void)didMoveToWindow;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initializeView;
- (_Bool)isVisible;
- (void)layoutSubviews;
- (void)setBackgroundColor:(id)arg1;
@property(nonatomic, getter=shouldForceOpacity) _Bool forceOpacity; // @synthesize forceOpacity=_forceOpacity;
- (_Bool)shouldUpdateConstraints;
- (void)updateConstraints;
- (void)willAppear;
- (void)willDisappear;
- (void)willMoveToWindow:(id)arg1;

@end

