//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class NSDictionary;

@interface BTNWebViewAction : BTNModelObject
{
    long long _type;
    NSDictionary *_data;
}

+ (long long)actionTypeForString:(id)arg1;
+ (_Bool)canInitWithDictionary:(id)arg1;
+ (void)load;
+ (id)stringForActionType:(long long)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *data; // @synthesize data=_data;
- (id)dictionaryRepresentation;
- (_Bool)isPostNavigationAction;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
- (void)updateWithRepresentation:(id)arg1;

@end

