//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class BTNCheckoutPreference, BTNText;

@interface BTNWebViewSheet : BTNModelObject
{
    BTNText *_titleText;
    BTNText *_appTitleText;
    BTNText *_appSubtitleText;
    BTNText *_appActionText;
    BTNText *_dismissActionText;
    BTNText *_webActionText;
    BTNCheckoutPreference *_checkoutPreference;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) BTNText *appActionText; // @synthesize appActionText=_appActionText;
@property(readonly, nonatomic) BTNText *appSubtitleText; // @synthesize appSubtitleText=_appSubtitleText;
@property(readonly, nonatomic) BTNText *appTitleText; // @synthesize appTitleText=_appTitleText;
@property(readonly, nonatomic) BTNCheckoutPreference *checkoutPreference; // @synthesize checkoutPreference=_checkoutPreference;
- (id)dictionaryRepresentation;
@property(readonly, nonatomic) BTNText *dismissActionText; // @synthesize dismissActionText=_dismissActionText;
@property(readonly, nonatomic) BTNText *titleText; // @synthesize titleText=_titleText;
- (void)updateWithRepresentation:(id)arg1;
@property(readonly, nonatomic) BTNText *webActionText; // @synthesize webActionText=_webActionText;

@end

