//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BTNResourceConsumer.h"
#import "BTNWebViewSheetDelegate.h"

@class BTNAppAction, BTNResourceProvider, BTNWebViewSheet, NSString, UIColor;

@interface BTNWebViewSheetViewModel : NSObject <BTNWebViewSheetDelegate, BTNResourceConsumer>
{
    _Bool _showProgressBar;
    BTNResourceProvider *_resources;
    long long _pageLoadMaxWaitTime;
    CDUnknownBlockType _appActionHandlerBlock;
    CDUnknownBlockType _webActionHandlerBlock;
    CDUnknownBlockType _dismissActionHandlerBlock;
    CDUnknownBlockType _preferenceChangedHandlerBlock;
    BTNAppAction *_appAction;
    BTNWebViewSheet *_webViewSheet;
}

+ (id)viewModelWithAppAction:(id)arg1 webViewSheet:(id)arg2 resources:(id)arg3;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) BTNAppAction *appAction; // @synthesize appAction=_appAction;
@property(copy, nonatomic) CDUnknownBlockType appActionHandlerBlock; // @synthesize appActionHandlerBlock=_appActionHandlerBlock;
@property(readonly, nonatomic) NSString *appActionText;
@property(readonly, nonatomic) UIColor *appActionTextColor;
@property(readonly, nonatomic) NSString *appSubtitleText;
@property(readonly, nonatomic) UIColor *appSubtitleTextColor;
@property(readonly, nonatomic) NSString *appTitleText;
@property(readonly, nonatomic) UIColor *appTitleTextColor;
@property(readonly, nonatomic) _Bool checkoutPreferencePresent;
@property(copy, nonatomic) CDUnknownBlockType dismissActionHandlerBlock; // @synthesize dismissActionHandlerBlock=_dismissActionHandlerBlock;
@property(readonly, nonatomic) NSString *dismissActionText;
@property(readonly, nonatomic) UIColor *dismissActionTextColor;
- (void)fetchPreviewIconImageForSize:(struct CGSize)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithAppAction:(id)arg1 webViewSheet:(id)arg2 resources:(id)arg3;
@property(nonatomic) long long pageLoadMaxWaitTime; // @synthesize pageLoadMaxWaitTime=_pageLoadMaxWaitTime;
@property(copy, nonatomic) CDUnknownBlockType preferenceChangedHandlerBlock; // @synthesize preferenceChangedHandlerBlock=_preferenceChangedHandlerBlock;
@property(readonly, nonatomic) NSString *preferenceTitleText;
@property(readonly, nonatomic) UIColor *preferenceTitleTextColor;
@property(readonly, nonatomic) UIColor *prefersAppColor;
@property(readonly, nonatomic) _Bool prefersAppDefaultState;
@property(readonly, nonatomic) UIColor *primaryColor;
@property(readonly, nonatomic) UIColor *progressBarColor;
@property(readonly, nonatomic) __weak BTNResourceProvider *resources; // @synthesize resources=_resources;
@property(nonatomic) _Bool showProgressBar; // @synthesize showProgressBar=_showProgressBar;
@property(copy, nonatomic) CDUnknownBlockType webActionHandlerBlock; // @synthesize webActionHandlerBlock=_webActionHandlerBlock;
@property(readonly, nonatomic) NSString *titleText;
@property(readonly, nonatomic) UIColor *titleTextColor;
- (void)updatePrefersAppUserDefaultValue;
@property(readonly, nonatomic) UIColor *webActionDisabledBackgroundColor;
@property(readonly, nonatomic) NSString *webActionText;
@property(readonly, nonatomic) UIColor *webActionTextColor;
@property(readonly, copy, nonatomic) BTNWebViewSheet *webViewSheet; // @synthesize webViewSheet=_webViewSheet;
- (void)webViewSheet:(id)arg1 didChangePreference:(_Bool)arg2;
- (void)webViewSheetDidSelectAppAction:(id)arg1;
- (void)webViewSheetDidSelectDismissAction:(id)arg1;
- (void)webViewSheetDidSelectWebAction:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

