//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class BTNWebViewTrigger, NSArray, NSString;

@interface BTNWebViewCheckpoint : BTNModelObject
{
    NSString *_name;
    BTNWebViewTrigger *_trigger;
    NSArray *_actions;
}

+ (_Bool)canInitWithDictionary:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *actions; // @synthesize actions=_actions;
- (id)dictionaryRepresentation;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) BTNWebViewTrigger *trigger; // @synthesize trigger=_trigger;
- (void)updateWithRepresentation:(id)arg1;

@end

