//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTNModelObject.h"

@class NSString;

@interface BTNWebViewTrigger : BTNModelObject
{
    NSString *_path;
}

+ (_Bool)canInitWithDictionary:(id)arg1;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
- (void)updateWithRepresentation:(id)arg1;

@end

