//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "Button.h"
#import "ButtonDeprecated.h"

@class BTNCore, BTNSession, NSString;

@interface Button : NSObject <Button, ButtonDeprecated>
{
    BTNCore *_core;
}

+ (void)allowButtonToRequestLocationPermission:(_Bool)arg1;
+ (id)sdkVersion;
+ (void)setAutomaticAttributionEnabled:(_Bool)arg1;
+ (void)setDeveloperBuildReportingEnabled:(_Bool)arg1;
+ (id)sharedButton;
- (void).cxx_destruct;
@property(retain, nonatomic) BTNCore *core; // @synthesize core=_core;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)init;
- (id)initWithSystemVersion:(id)arg1;
@property(readonly, copy, nonatomic) BTNSession *session;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

