//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BTNContext, BTNSession, NSDictionary, NSString, NSURL, NSUserActivity;

@protocol Button <NSObject>
- (_Bool)canFetchAppActionWithURL:(NSURL *)arg1;
- (void)configureWithApplicationId:(NSString *)arg1 completion:(void (^)(NSError *))arg2;
- (void)configureWithApplicationId:(NSString *)arg1 userId:(NSString *)arg2 completion:(void (^)(NSError *, NSURL *))arg3;
- (_Bool)continueUserActivity:(NSUserActivity *)arg1;
- (void)fetchAppActionWithButtonId:(NSString *)arg1 context:(BTNContext *)arg2 completion:(void (^)(BTNAppAction *, NSError *))arg3;
- (void)fetchAppActionWithButtonId:(NSString *)arg1 context:(BTNContext *)arg2 publisherReference:(NSString *)arg3 completion:(void (^)(BTNAppAction *, NSError *))arg4;
- (void)fetchAppActionWithMerchantId:(NSString *)arg1 completion:(void (^)(BTNAppAction *, NSError *))arg2;
- (void)fetchAppActionWithMerchantId:(NSString *)arg1 publisherReference:(NSString *)arg2 completion:(void (^)(BTNAppAction *, NSError *))arg3;
- (void)fetchAppActionWithURL:(NSURL *)arg1 completion:(void (^)(BTNAppAction *, NSError *))arg2;
- (void)fetchAppActionWithURL:(NSURL *)arg1 publisherReference:(NSString *)arg2 completion:(void (^)(BTNAppAction *, NSError *))arg3;
- (_Bool)handleURL:(NSURL *)arg1;
- (void)logOut;
- (NSString *)referrerToken;
- (void)reportEventWithName:(NSString *)arg1 properties:(NSDictionary *)arg2;
@property(readonly, copy, nonatomic) BTNSession *session;
- (void)setDebugLoggingEnabled:(_Bool)arg1;
- (void)setUserIdentifier:(NSString *)arg1;
- (void)willDisplayButtonWithId:(NSString *)arg1 context:(BTNContext *)arg2 completion:(void (^)(_Bool))arg3;
@end

