//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol ButtonDeprecated <NSObject>
- (void)reportOrderWithId:(NSString *)arg1 currencyCode:(NSString *)arg2 lineItems:(NSArray *)arg3;
- (void)reportOrderWithValue:(long long)arg1 orderId:(NSString *)arg2 currencyCode:(NSString *)arg3;
@end

