//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class SpecialColumnModel, UIImageView, UILabel;

@interface ColumnCollectionViewCell : UICollectionViewCell
{
    _Bool _isLastOne;
    SpecialColumnModel *_model;
    UIImageView *_imageView;
    UILabel *_nameLabel;
    UILabel *_seeMoreLabel;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) _Bool isLastOne; // @synthesize isLastOne=_isLastOne;
@property(retain, nonatomic) SpecialColumnModel *model; // @synthesize model=_model;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UILabel *seeMoreLabel; // @synthesize seeMoreLabel=_seeMoreLabel;

@end

