//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

@class NSMutableArray, SpecialColumnModel;

@interface ColumnViewController : BaseTableViewController
{
    SpecialColumnModel *_model;
    NSMutableArray *_dataArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
- (void)didReceiveMemoryWarning;
- (id)initWith:(id)arg1;
@property(retain, nonatomic) SpecialColumnModel *model; // @synthesize model=_model;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setNavigationBar;
- (void)setupUI;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

@end

