//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class CommentModel, NSIndexPath, NSMutableArray, UIButton, UIImageView, UILabel;

@interface CommentCell : UITableViewCell
{
    CDUnknownBlockType _showAlert;
    CDUnknownBlockType _turnToUser;
    UILabel *_nameLabel;
    UILabel *_descLabel;
    UIImageView *_iconImageView;
    UIButton *_moreButton;
    UILabel *_timeLabel;
    UIButton *_loveButton;
    NSIndexPath *_indexPath;
    CommentModel *_commentModel;
    long long _lineNum;
    NSMutableArray *_urlArray;
}

+ (double)calculateHeightWith:(id)arg1;
- (void).cxx_destruct;
- (void)awakeFromNib;
- (struct CGRect)calculateFrameWith:(id)arg1 from:(id)arg2;
@property(retain, nonatomic) CommentModel *commentModel; // @synthesize commentModel=_commentModel;
- (void)configCellWithModel:(id)arg1;
- (id)dealWithComment:(id)arg1;
@property(nonatomic) __weak UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(nonatomic) __weak UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
@property(nonatomic) long long lineNum; // @synthesize lineNum=_lineNum;
@property(nonatomic) __weak UIButton *loveButton; // @synthesize loveButton=_loveButton;
- (void)loveButtonClickAction:(id)arg1;
@property(nonatomic) __weak UIButton *moreButton; // @synthesize moreButton=_moreButton;
- (void)moreButtonClickAction:(id)arg1;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(copy, nonatomic) CDUnknownBlockType showAlert; // @synthesize showAlert=_showAlert;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(copy, nonatomic) CDUnknownBlockType turnToUser; // @synthesize turnToUser=_turnToUser;
@property(retain, nonatomic) NSMutableArray *urlArray; // @synthesize urlArray=_urlArray;
- (void)showAttachmentImage:(id)arg1;
- (void)turnToUserPage;

@end

