//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

#import "UITableViewDataSource.h"

@class NSString;

@interface ContentTableView : UITableView <UITableViewDataSource>
{
}

- (void)dealloc;
- (void)didMoveToWindow;
- (void)downloadData;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)loadMoreData;
- (void)setContentOffset:(struct CGPoint)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

