//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSArray, UICollectionView, UICollectionViewFlowLayout, UILabel;

@interface DiscoverHeaderViewController : UIViewController
{
    UICollectionView *_columnCollectionView;
    UICollectionViewFlowLayout *_columnFlowLayout;
    UILabel *_titleLable;
    UILabel *_textLabel;
    UICollectionView *_topicCollectionView;
    UICollectionViewFlowLayout *_topicFlowLayout;
    NSArray *_columnArray;
    NSArray *_topicArray;
}

- (void).cxx_destruct;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@property(retain, nonatomic) NSArray *columnArray; // @synthesize columnArray=_columnArray;
@property(nonatomic) __weak UICollectionView *columnCollectionView; // @synthesize columnCollectionView=_columnCollectionView;
@property(nonatomic) __weak UICollectionViewFlowLayout *columnFlowLayout; // @synthesize columnFlowLayout=_columnFlowLayout;
- (void)configFlowLayout;
- (void)didReceiveMemoryWarning;
- (void)refreshData;
@property(nonatomic) __weak UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(nonatomic) __weak UILabel *titleLable; // @synthesize titleLable=_titleLable;
@property(retain, nonatomic) NSArray *topicArray; // @synthesize topicArray=_topicArray;
@property(nonatomic) __weak UICollectionView *topicCollectionView; // @synthesize topicCollectionView=_topicCollectionView;
@property(nonatomic) __weak UICollectionViewFlowLayout *topicFlowLayout; // @synthesize topicFlowLayout=_topicFlowLayout;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

