//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class TopicModel, UIImageView, UILabel;

@interface DiscoverHeaderTopicCell : UICollectionViewCell
{
    _Bool _isLastOne;
    TopicModel *_model;
    UILabel *_seeMoreLabel;
    UIImageView *_bigImageView;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *bigImageView; // @synthesize bigImageView=_bigImageView;
@property(nonatomic) _Bool isLastOne; // @synthesize isLastOne=_isLastOne;
@property(retain, nonatomic) TopicModel *model; // @synthesize model=_model;
@property(nonatomic) __weak UILabel *seeMoreLabel; // @synthesize seeMoreLabel=_seeMoreLabel;

@end

