//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DownloadsCountsModel : NSObject
{
    NSString *_android;
    NSString *_iphone;
    NSString *_ipad;
    NSString *_windows;
    NSString *_windows_phone;
    NSString *_mac;
    NSString *_ios;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *android; // @synthesize android=_android;
@property(copy, nonatomic) NSString *ios; // @synthesize ios=_ios;
@property(copy, nonatomic) NSString *ipad; // @synthesize ipad=_ipad;
@property(copy, nonatomic) NSString *iphone; // @synthesize iphone=_iphone;
@property(copy, nonatomic) NSString *mac; // @synthesize mac=_mac;
@property(copy, nonatomic) NSString *windows; // @synthesize windows=_windows;
@property(copy, nonatomic) NSString *windows_phone; // @synthesize windows_phone=_windows_phone;

@end

