//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DTRpcConfig, NSMutableDictionary;

@interface DTRpcConfigManager : NSObject
{
    DTRpcConfig *_globalConfig;
    NSMutableDictionary *_operationTypeConfigs;
}

- (void).cxx_destruct;
- (id)configForScope:(int)arg1;
@property(retain, nonatomic) DTRpcConfig *globalConfig; // @synthesize globalConfig=_globalConfig;
- (id)init;
@property(retain, nonatomic) NSMutableDictionary *operationTypeConfigs; // @synthesize operationTypeConfigs=_operationTypeConfigs;
- (id)preferredConfig:(id)arg1;
- (void)setConfig:(id)arg1 forScope:(int)arg2;

@end

