//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class ArticleModel, TopicModel, UIImageView, UILabel;

@interface FavoritedTableViewCell : UITableViewCell
{
    ArticleModel *_article;
    TopicModel *_topic;
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ArticleModel *article; // @synthesize article=_article;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) TopicModel *topic; // @synthesize topic=_topic;

@end

