//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GrowingBarChart.h"

@class GrowingElement, NSArray, NSString, UIView;

@interface GrowingRealtimeBarChartView : GrowingBarChart
{
    _Bool _canClickBar;
    _Bool _autoRequestLineChartWhenBarChartOnlyOneBar;
    CDUnknownBlockType _onLoadFinish;
    NSString *_valueFormatString;
    CDUnknownBlockType _onSaveElement;
    GrowingElement *_element;
    NSArray *_items;
    UIView *_singleBarLineChartView;
}

- (void).cxx_destruct;
- (id)addTitle:(id)arg1 value:(long long)arg2;
- (id)addTitle:(id)arg1 value:(long long)arg2 valueText:(id)arg3 color:(id)arg4 onClick:(CDUnknownBlockType)arg5;
@property(nonatomic) _Bool autoRequestLineChartWhenBarChartOnlyOneBar; // @synthesize autoRequestLineChartWhenBarChartOnlyOneBar=_autoRequestLineChartWhenBarChartOnlyOneBar;
@property(nonatomic) _Bool canClickBar; // @synthesize canClickBar=_canClickBar;
- (void)clearAll;
@property(retain, nonatomic) GrowingElement *element; // @synthesize element=_element;
- (id)getLinecharByElement:(id)arg1 andContent:(id)arg2 onFinish:(CDUnknownBlockType)arg3;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void)loadElement:(id)arg1;
- (void)loadValueCountItems:(id)arg1;
- (_Bool)loadValueIfItemCountOnlyOne;
- (void)onClickIndex:(id)arg1 animated:(_Bool)arg2;
@property(copy, nonatomic) CDUnknownBlockType onLoadFinish; // @synthesize onLoadFinish=_onLoadFinish;
- (void)onLoadFinish:(_Bool)arg1;
@property(copy, nonatomic) CDUnknownBlockType onSaveElement; // @synthesize onSaveElement=_onSaveElement;
@property(retain, nonatomic) UIView *singleBarLineChartView; // @synthesize singleBarLineChartView=_singleBarLineChartView;
@property(copy, nonatomic) NSString *valueFormatString; // @synthesize valueFormatString=_valueFormatString;
- (_Bool)supportClickBarIndex;

@end

