//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GrowingChildContentPanelCellDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSMutableArray, NSString, UICollectionView;

@interface GrowingChildContentPanel : UIView <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, GrowingChildContentPanelCellDelegate>
{
    CDUnknownBlockType _onSaveElement;
    NSMutableArray *_items;
    UICollectionView *_collectionView;
}

- (void).cxx_destruct;
- (void)GrowingChildContentPanelCell:(id)arg1 didClickCloseWithElement:(id)arg2;
- (void)GrowingChildContentPanelCell:(id)arg1 didClickSaveWithElement:(id)arg2 withName:(id)arg3;
- (void)addElement:(id)arg1 image:(id)arg2 name:(id)arg3 withStyle:(long long)arg4;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType onSaveElement; // @synthesize onSaveElement=_onSaveElement;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (unsigned long long)showType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

