//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAShapeLayer, UIColor;

@interface Growing3rdLibUUBar : UIView
{
    float _grade;
    CAShapeLayer *_chartLine;
    UIColor *_barColor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *barColor; // @synthesize barColor=_barColor;
@property(retain, nonatomic) CAShapeLayer *chartLine; // @synthesize chartLine=_chartLine;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) float grade; // @synthesize grade=_grade;
- (id)initWithFrame:(struct CGRect)arg1;

@end

