//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GrowingNode.h"

@class NSString;

@interface GrowingRootNode : NSObject <GrowingNode>
{
}

+ (id)rootNode;
- (id)growingNodeAsyncNativeHandler;
- (id)growingNodeAttachedInfoNode;
- (id)growingNodeAttribute:(id)arg1;
- (id)growingNodeAttribute:(id)arg1 forChild:(id)arg2;
- (id)growingNodeContent;
- (id)growingNodeDataDict;
- (_Bool)growingNodeDonotCircle;
- (_Bool)growingNodeDonotTrack;
- (struct CGRect)growingNodeFrame;
- (void)growingNodeHighLight:(_Bool)arg1 withBorderColor:(id)arg2 andBackgroundColor:(id)arg3;
- (id)growingNodeName;
- (void)growingNodeOutChilds:(id)arg1 outPaths:(id)arg2 filterChildNode:(id)arg3;
- (void)growingNodeOutContainerChilds:(id)arg1 outPaths:(id)arg2 filterChildNode:(id)arg3;
- (id)growingNodeParent;
- (id)growingNodeScreenShot:(id)arg1;
- (id)growingNodeScreenShotWithScale:(double)arg1;
- (_Bool)growingNodeUserInteraction;
- (id)growingNodeWindow;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

