//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GrowingWindowView.h"

#import "GrowingEventManagerObserver.h"

@class GrowingEventListMenuPopView, GrowingImageCache, NSMutableArray, NSString, UIViewController;

@interface GrowingEventListMenu : GrowingWindowView <GrowingEventManagerObserver>
{
    _Bool _showTable;
    GrowingImageCache *_imageCache;
    NSMutableArray *_allEventItems;
    UIViewController *_viewController;
    GrowingEventListMenuPopView *_popView;
}

+ (void)clearAllEvent;
+ (void)hide;
+ (_Bool)isReplay;
+ (_Bool)isStart;
+ (void)setIsReplay:(_Bool)arg1;
+ (void)startTrack;
+ (void)stopTrack;
- (void).cxx_destruct;
- (void)_growingEventManagerWillAddEvent:(id)arg1 thisNode:(id)arg2 triggerNode:(id)arg3 withContext:(id)arg4;
- (id)addItemIntoAllEventsItems:(id)arg1 type:(long long)arg2;
@property(retain, nonatomic) NSMutableArray *allEventItems; // @synthesize allEventItems=_allEventItems;
- (void)growingEventManagerWillAddEvent:(id)arg1 thisNode:(id)arg2 triggerNode:(id)arg3 withContext:(id)arg4;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) GrowingImageCache *imageCache; // @synthesize imageCache=_imageCache;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)lastEventItem;
- (void)popTipWithTitle:(id)arg1 eventType:(long long)arg2;
@property(retain, nonatomic) GrowingEventListMenuPopView *popView; // @synthesize popView=_popView;
- (void)setGrowingEventListItem:(id)arg1 image:(id)arg2;
@property(nonatomic) _Bool showTable; // @synthesize showTable=_showTable;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

