//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class GrowingElement, NSNumber;

@interface GrowingEventListChildItem : NSObject <NSCopying>
{
    long long _eventType;
    GrowingElement *_element;
    NSNumber *_tm;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) GrowingElement *element; // @synthesize element=_element;
@property(nonatomic) long long eventType; // @synthesize eventType=_eventType;
@property(retain, nonatomic) NSNumber *tm; // @synthesize tm=_tm;

@end

