//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class GrowingElement, GrowingImageCacheImage, NSString, UIButton, UILabel, UIView;

@interface GrowingChildContentPanelCellBase : UICollectionViewCell
{
    id <GrowingChildContentPanelCellDelegate> _delegate;
    NSString *_title;
    UILabel *_titleLabel;
    GrowingElement *_element;
    GrowingImageCacheImage *_image;
    UIView *_mainContentView;
    UIView *_chartContentView;
    UIButton *_saveButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *chartContentView; // @synthesize chartContentView=_chartContentView;
- (void)closeClick;
@property(nonatomic) id <GrowingChildContentPanelCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) GrowingElement *element; // @synthesize element=_element;
- (id)elementForSave;
@property(retain, nonatomic) GrowingImageCacheImage *image; // @synthesize image=_image;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)loadElement:(id)arg1 andImage:(id)arg2;
@property(retain, nonatomic) UIView *mainContentView; // @synthesize mainContentView=_mainContentView;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
- (void)saveClick;
- (void)saveElement:(id)arg1 withName:(id)arg2;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

