//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GrowingEventManagerObserver.h"

@class GrowingEventManager, NSString;

@interface GrowingTrackSelfManager : NSObject <GrowingEventManagerObserver>
{
    GrowingEventManager *_trackManager;
    NSString *_domain;
}

+ (void)startTrack;
+ (void)stopTrack;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *domain; // @synthesize domain=_domain;
- (_Bool)growingEventManagerShouldAddEvent:(id)arg1 thisNode:(id)arg2 triggerNode:(id)arg3 withContext:(id)arg4;
- (id)init;
- (void)sendTrackSelfVisitEvent;
@property(retain, nonatomic) GrowingEventManager *trackManager; // @synthesize trackManager=_trackManager;
- (void)start;
- (void)stop;
- (void)updateEventCommentField:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

