//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GrowingAddEventContext.h"

@class GrowingNodeManager, NSMutableArray, NSString;

@interface GrowingNodeManagerEnumerateContext : NSObject <GrowingAddEventContext>
{
    _Bool _stopAll;
    _Bool _stopChilds;
    NSMutableArray *_didEndNodeBlocks;
    GrowingNodeManager *_manager;
}

- (void).cxx_destruct;
- (id)allNodes;
- (id)attributeValueForKey:(id)arg1;
- (id)contextNodes;
@property(retain, nonatomic) NSMutableArray *didEndNodeBlocks; // @synthesize didEndNodeBlocks=_didEndNodeBlocks;
- (id)keyNode;
@property(retain, nonatomic) GrowingNodeManager *manager; // @synthesize manager=_manager;
- (long long)nodeKeyIndex;
- (void)onNodeFinish:(CDUnknownBlockType)arg1;
@property(nonatomic) _Bool stopAll; // @synthesize stopAll=_stopAll;
@property(nonatomic) _Bool stopChilds; // @synthesize stopChilds=_stopChilds;
- (void)skipThisChilds;
- (id)startNode;
- (void)stop;
- (id)xpath;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

