//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "Growing3rdLibSRWebSocketDelegate.h"
#import "GrowingEventManagerObserver.h"

@class Growing3rdLibSRWebSocket, GrowingStatusBar, GrowingWebSocketActionItem, NSMutableArray, NSString, NSTimer;

@interface GrowingWebSocket : NSObject <Growing3rdLibSRWebSocketDelegate, GrowingEventManagerObserver>
{
    NSTimer *_keepAliveTimer;
    Growing3rdLibSRWebSocket *_webSocket;
    GrowingWebSocketActionItem *_rootAction;
    CDUnknownBlockType _onReadyBlock;
    CDUnknownBlockType _onFinishBlock;
    GrowingStatusBar *_statusWindow;
    NSMutableArray *_cachedEvents;
}

+ (double)impressScale;
+ (_Bool)isContainer:(id)arg1;
+ (_Bool)isRunning;
+ (void)retrieveAllElementsAsync:(CDUnknownBlockType)arg1;
+ (void)runWithCircleRoomNumber:(id)arg1 ReadyBlock:(CDUnknownBlockType)arg2 finishBlock:(CDUnknownBlockType)arg3;
+ (void)setNeedUpdateScreen;
+ (id)shareInstance;
+ (void)stop;
- (void).cxx_destruct;
- (void)_setNeedUpdateScreen;
- (void)_stopWithError:(id)arg1;
- (void)addActionItemAtPath:(id)arg1 action:(CDUnknownBlockType)arg2;
- (void)addActions;
- (void)beginKeepAlive;
@property(retain, nonatomic) NSMutableArray *cachedEvents; // @synthesize cachedEvents=_cachedEvents;
- (id)dictForUserAction:(id)arg1;
- (id)dictFromNode:(id)arg1 pageData:(id)arg2 keyIndex:(long long)arg3 xPath:(id)arg4 nodeType:(id)arg5 isContainer:(_Bool)arg6;
- (void)endKeepAlive;
- (void)fillAllViewsForWebCircle:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)getNodeName:(id)arg1 withXPath:(id)arg2 withKeyIndex:(long long)arg3 withContent:(id)arg4 withPage:(id)arg5;
- (id)getViewControllerName:(id)arg1;
- (_Bool)growingEventManagerShouldAddEvent:(id)arg1 triggerNode:(id)arg2 withContext:(id)arg3;
- (void)growingEventManagerWillAddEvent:(id)arg1 thisNode:(id)arg2 triggerNode:(id)arg3 withContext:(id)arg4;
- (id)init;
- (_Bool)isContainer:(id)arg1;
- (_Bool)isRunning;
- (void)keepAlive;
@property(retain, nonatomic) NSTimer *keepAliveTimer; // @synthesize keepAliveTimer=_keepAliveTimer;
@property(copy, nonatomic) CDUnknownBlockType onFinishBlock; // @synthesize onFinishBlock=_onFinishBlock;
@property(copy, nonatomic) CDUnknownBlockType onReadyBlock; // @synthesize onReadyBlock=_onReadyBlock;
- (void)remoteReady;
@property(retain, nonatomic) GrowingWebSocketActionItem *rootAction; // @synthesize rootAction=_rootAction;
- (void)runActionWithJsonObj:(id)arg1;
- (_Bool)runActionWithJsonObj:(id)arg1 atPathItem:(id)arg2 unRunObj:(id *)arg3;
- (void)runWithCircleRoomNumber:(id)arg1 ReadyBlock:(CDUnknownBlockType)arg2 finishBlock:(CDUnknownBlockType)arg3;
- (id)screenShot;
- (void)sendClickOrTouchAction;
- (void)sendJson:(id)arg1;
- (void)sendScreenShot;
- (void)sendScreenShotWithEventType:(id)arg1 optionalTargets:(id)arg2 optionalNodeName:(id)arg3 optionalPageName:(id)arg4 callback:(CDUnknownBlockType)arg5;
- (void)setNeedUpdateScreen;
@property(retain, nonatomic) GrowingStatusBar *statusWindow; // @synthesize statusWindow=_statusWindow;
@property(retain, nonatomic) Growing3rdLibSRWebSocket *webSocket; // @synthesize webSocket=_webSocket;
- (void)stop;
- (void)webSocket:(id)arg1 didCloseWithCode:(long long)arg2 reason:(id)arg3 wasClean:(_Bool)arg4;
- (void)webSocket:(id)arg1 didFailWithError:(id)arg2;
- (void)webSocket:(id)arg1 didReceiveMessage:(id)arg2;
- (void)webSocket:(id)arg1 didReceivePong:(id)arg2;
- (void)webSocketDidOpen:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

