//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GrowingWindowView.h"

#import "UIAlertViewDelegate.h"

@class GROMagnifierView, GrowingHelperMenu, NSArray, NSMapTable, NSMutableArray, NSString, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;

@interface GrowingLocalCircleWindow : GrowingWindowView <UIAlertViewDelegate>
{
    _Bool _isStart;
    _Bool _isShow;
    UIPanGestureRecognizer *_panGest;
    NSMutableArray *_lastItemsMutable;
    UITapGestureRecognizer *_tapGest;
    UIView *_buttonView;
    long long _showCount;
    NSArray *_allTagItems;
    GrowingHelperMenu *_helperMenu;
    NSMapTable *_allMaskViews;
    GROMagnifierView *_magnifierViewForSmallItem;
    struct CGRect _keyboardBounds;
}

+ (void)circleH5Pages:(id)arg1;
+ (void)circlePage;
+ (void)decreaseHiddenCount;
+ (_Bool)hasStartCircle;
+ (void)hidden;
+ (void)increaseHiddenCount;
+ (_Bool)isShow;
+ (id)lookUpShareInstance;
+ (id)shareInstance;
+ (void)show;
+ (void)startCircle;
+ (void)stopCircle;
- (void).cxx_destruct;
- (void)addMagnifierViewForSmallView:(id)arg1 withTouchPoint:(struct CGPoint)arg2;
@property(retain, nonatomic) NSMapTable *allMaskViews; // @synthesize allMaskViews=_allMaskViews;
@property(retain, nonatomic) NSArray *allTagItems; // @synthesize allTagItems=_allTagItems;
@property(retain, nonatomic) UIView *buttonView; // @synthesize buttonView=_buttonView;
- (void)checkView:(id)arg1 withHitPoint:(struct CGPoint)arg2 andResult:(id)arg3;
- (void)circleH5Pages:(id)arg1;
- (void)circlePage;
- (id)createMenuItemByCircleItem:(id)arg1 windowImage:(id)arg2;
- (id)createMenuItemByNode:(id)arg1 doNotTrack:(_Bool)arg2 element:(id)arg3 windowImage:(id)arg4 isH5Tag:(_Bool)arg5;
- (void)delayCirclePoint:(id)arg1;
- (void)didMoveToSuperview;
- (void)didlogout;
- (id)getElementFromNode:(id)arg1;
- (id)getNativePageItem:(id)arg1;
- (_Bool)growingNodeDonotCircle;
@property(retain, nonatomic) GrowingHelperMenu *helperMenu; // @synthesize helperMenu=_helperMenu;
- (void)hideButton;
- (void)hideHelper;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)init;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
@property(nonatomic) _Bool isStart; // @synthesize isStart=_isStart;
@property(nonatomic) struct CGRect keyboardBounds; // @synthesize keyboardBounds=_keyboardBounds;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
@property(retain, nonatomic) NSArray *lastItems;
@property(retain, nonatomic) NSMutableArray *lastItemsMutable; // @synthesize lastItemsMutable=_lastItemsMutable;
@property(retain, nonatomic) GROMagnifierView *magnifierViewForSmallItem; // @synthesize magnifierViewForSmallItem=_magnifierViewForSmallItem;
- (id)nodesForPoint:(struct CGPoint)arg1;
@property(retain, nonatomic) UIPanGestureRecognizer *panGest; // @synthesize panGest=_panGest;
- (void)panGest:(id)arg1;
- (void)removeMagnifier;
- (void)resetWindowFrame;
- (void)setButtonCenter:(struct CGPoint)arg1;
@property(nonatomic) long long showCount; // @synthesize showCount=_showCount;
@property(retain, nonatomic) UITapGestureRecognizer *tapGest; // @synthesize tapGest=_tapGest;
- (void)showButton;
- (void)showHelper;
- (void)showSelectedViewWithWindowImage:(id)arg1 items:(id)arg2;
- (id)takeSnapshotOfMainWindowForTouchPoint:(struct CGPoint)arg1;
- (void)tapGest:(id)arg1;
- (_Bool)thisNodeIsOneRowOfTableView:(id)arg1;
- (void)updateKeyboardFrame:(id)arg1;
- (void)updateSelectedMask:(id)arg1 doNotTrack:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

