//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GrowingImageCache, NSString;

@interface GrowingImageCacheImage : NSObject
{
    NSString *_uuid;
    GrowingImageCache *_cache;
    struct CGSize _imageSize;
}

+ (id)imageWithCache:(id)arg1 image:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) GrowingImageCache *cache; // @synthesize cache=_cache;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
- (void)loadImage:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;

@end

