//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class Growing3rdLibUUBarChart, Growing3rdLibUULineChart;

@interface Growing3rdLibUUChart : UIView
{
    _Bool _showRange;
    int _chartStyle;
    Growing3rdLibUULineChart *_lineChart;
    Growing3rdLibUUBarChart *_barChart;
    id <Growing3rdLibUUChartDataSource> _dataSource;
}

- (void).cxx_destruct;
@property(retain, nonatomic) Growing3rdLibUUBarChart *barChart; // @synthesize barChart=_barChart;
@property int chartStyle; // @synthesize chartStyle=_chartStyle;
@property(nonatomic) id <Growing3rdLibUUChartDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initwithGrowing3rdLibUUChartDataFrame:(struct CGRect)arg1 withSource:(id)arg2 withStyle:(int)arg3;
@property(retain, nonatomic) Growing3rdLibUULineChart *lineChart; // @synthesize lineChart=_lineChart;
@property(nonatomic) _Bool showRange; // @synthesize showRange=_showRange;
- (void)setUpChart;
- (void)showInView:(id)arg1;
- (void)strokeChart;

@end

