//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSLayoutConstraint, UIButton;

@interface HomeColumnViewController : UIViewController
{
    UIButton *_columnButton;
    NSLayoutConstraint *_topMargin;
}

- (void).cxx_destruct;
- (void)clickColumnButtonAction:(id)arg1;
@property(nonatomic) __weak UIButton *columnButton; // @synthesize columnButton=_columnButton;
- (void)didReceiveMemoryWarning;
@property(nonatomic) __weak NSLayoutConstraint *topMargin; // @synthesize topMargin=_topMargin;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

