//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class ArticleModel, NSString, UIButton, UIImageView, UILabel;

@interface HomeTableViewCell : UITableViewCell
{
    _Bool _isFromeHomePage;
    ArticleModel *_model;
    CDUnknownBlockType _showAlert;
    CDUnknownBlockType _turnToUser;
    CDUnknownBlockType _turnToArticle;
    NSString *_commentCount;
    NSString *_likeCount;
    UIImageView *_iconImage;
    UIImageView *_bigImageView;
    UILabel *_nicknameLabel;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UILabel *_timeLabel;
    UIButton *_lickButton;
    UIButton *_commentButton;
    UIButton *_moreButton;
    UIButton *_articleButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIButton *articleButton; // @synthesize articleButton=_articleButton;
- (void)asynchronouslySetFontName:(id)arg1 string:(id)arg2;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *bigImageView; // @synthesize bigImageView=_bigImageView;
- (void)clickArticleButtonAction:(id)arg1;
- (void)clickIconImageAction:(id)arg1;
- (void)clickMoreButtonAction:(id)arg1;
@property(nonatomic) __weak UIButton *commentButton; // @synthesize commentButton=_commentButton;
@property(copy, nonatomic) NSString *commentCount; // @synthesize commentCount=_commentCount;
@property(nonatomic) __weak UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(nonatomic) __weak UIImageView *iconImage; // @synthesize iconImage=_iconImage;
@property(nonatomic) _Bool isFromeHomePage; // @synthesize isFromeHomePage=_isFromeHomePage;
@property(nonatomic) __weak UIButton *lickButton; // @synthesize lickButton=_lickButton;
@property(copy, nonatomic) NSString *likeCount; // @synthesize likeCount=_likeCount;
@property(retain, nonatomic) ArticleModel *model; // @synthesize model=_model;
@property(nonatomic) __weak UIButton *moreButton; // @synthesize moreButton=_moreButton;
@property(nonatomic) __weak UILabel *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
- (void)setDescWith:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(copy, nonatomic) CDUnknownBlockType showAlert; // @synthesize showAlert=_showAlert;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType turnToArticle; // @synthesize turnToArticle=_turnToArticle;
@property(copy, nonatomic) CDUnknownBlockType turnToUser; // @synthesize turnToUser=_turnToUser;

@end

