//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class AdvertisementModel, UIImageView, UIView;

@interface HomeHeaderCell : UICollectionViewCell
{
    AdvertisementModel *_model;
    UIImageView *_bannerImage;
    UIView *_backView;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(nonatomic) __weak UIView *backView; // @synthesize backView=_backView;
@property(nonatomic) __weak UIImageView *bannerImage; // @synthesize bannerImage=_bannerImage;
@property(copy, nonatomic) AdvertisementModel *model; // @synthesize model=_model;

@end

