//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

#import "ArticleShareViewDelegate.h"
#import "LoginViewControllerDelegate.h"
#import "SFSafariViewControllerDelegate.h"
#import "TopTitleViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSMutableArray, NSString, TopTitleView, UIActivityIndicatorView;

@interface HomeTableViewController : BaseTableViewController <UIGestureRecognizerDelegate, TopTitleViewDelegate, LoginViewControllerDelegate, ArticleShareViewDelegate, SFSafariViewControllerDelegate>
{
    _Bool _turnToSafari;
    _Bool _isRefreshing;
    _Bool _isOpenArticleing;
    _Bool _isLoding;
    NSMutableArray *_dataArray;
    TopTitleView *_topTitleView;
    UIActivityIndicatorView *_actiView;
}

- (void).cxx_destruct;
- (void)accusationArticle:(id)arg1;
@property(nonatomic) __weak UIActivityIndicatorView *actiView; // @synthesize actiView=_actiView;
- (void)addPanGestureRecognizer;
- (void)cancelFavoriteArticle:(id)arg1;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
- (void)dealWithURL:(id)arg1;
- (void)dealloc;
- (void)didClickButtonAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)downloadData;
- (void)favoriteArticle:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)homeButtonClick:(id)arg1;
- (void)homeButtonDoubleClick:(id)arg1;
@property(nonatomic) _Bool isLoding; // @synthesize isLoding=_isLoding;
@property(nonatomic) _Bool isOpenArticleing; // @synthesize isOpenArticleing=_isOpenArticleing;
@property(nonatomic) _Bool isRefreshing; // @synthesize isRefreshing=_isRefreshing;
- (void)jumpToPageTop;
- (void)loadMoreData;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)openURLInSafari:(id)arg1;
- (void)pan:(id)arg1;
- (void)pushActivityVC:(id)arg1;
- (void)pushRegistVierController:(id)arg1;
- (void)pushVC:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)setNotification;
@property(nonatomic) __weak TopTitleView *topTitleView; // @synthesize topTitleView=_topTitleView;
@property(nonatomic) _Bool turnToSafari; // @synthesize turnToSafari=_turnToSafari;
- (void)shareArticle:(id)arg1;
- (void)showAlertView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)turnToArticleViewController:(id)arg1 cell:(id)arg2;
- (void)turnToPayArticle:(id)arg1;
- (void)turnToPersionalViewController:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

