//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JPUSHClientController, NSDictionary, NSObject<OS_dispatch_queue>;

@interface JPUSHService : NSObject
{
    JPUSHClientController *_client;
    _Bool _isFromBackground;
    _Bool _isFromUserAction;
    NSObject<OS_dispatch_queue> *_registrationIDqueue;
    _Bool _finishLaunchReceived;
    id <JPUSHRegisterDelegate> _delegate;
    NSDictionary *_launchOptions;
}

+ (void)addNotification:(id)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)beginLogPageView:(id)arg1 duration:(int)arg2;
+ (void)clearAllLocalNotifications;
+ (void)close;
+ (void)commonSetupWithOption:(id)arg1 appKey:(id)arg2 channel:(id)arg3 apsForProduction:(_Bool)arg4 advertisingIdentifier:(id)arg5;
+ (void)crashLogON;
+ (void)deleteLocalNotification:(id)arg1;
+ (void)deleteLocalNotificationWithIdentifierKey:(id)arg1;
+ (id)filterValidTags:(id)arg1;
+ (id)findLocalNotificationWithIdentifier:(id)arg1;
+ (void)findNotification:(id)arg1;
+ (void)handleRemoteNotification:(id)arg1;
+ (void)registerDeviceToken:(id)arg1;
+ (void)registerForRemoteNotificationConfig:(id)arg1 delegate:(id)arg2;
+ (void)registerForRemoteNotificationTypes:(unsigned long long)arg1 categories:(id)arg2;
+ (id)registrationID;
+ (void)registrationIDCompletionHandler:(CDUnknownBlockType)arg1;
+ (void)removeNotification:(id)arg1;
+ (void)resetBadge;
+ (void)setAlias:(id)arg1 callbackSelector:(SEL)arg2 object:(id)arg3;
+ (_Bool)setBadge:(long long)arg1;
+ (void)setDebugMode;
+ (void)setLatitude:(double)arg1 longitude:(double)arg2;
+ (id)setLocalNotification:(id)arg1 alertBody:(id)arg2 badge:(int)arg3 alertAction:(id)arg4 identifierKey:(id)arg5 userInfo:(id)arg6 soundName:(id)arg7;
+ (id)setLocalNotification:(id)arg1 alertBody:(id)arg2 badge:(int)arg3 alertAction:(id)arg4 identifierKey:(id)arg5 userInfo:(id)arg6 soundName:(id)arg7 region:(id)arg8 regionTriggersOnce:(_Bool)arg9 category:(id)arg10;
+ (void)setLocation:(id)arg1;
+ (void)setLogOFF;
+ (void)setTags:(id)arg1 alias:(id)arg2 callbackSelector:(SEL)arg3 object:(id)arg4;
+ (void)setTags:(id)arg1 alias:(id)arg2 callbackSelector:(SEL)arg3 target:(id)arg4;
+ (void)setTags:(id)arg1 alias:(id)arg2 fetchCompletionHandle:(CDUnknownBlockType)arg3;
+ (void)setTags:(id)arg1 aliasInbackground:(id)arg2;
+ (void)setTags:(id)arg1 callbackSelector:(SEL)arg2 object:(id)arg3;
+ (void)setupWithOption:(id)arg1;
+ (void)setupWithOption:(id)arg1 appKey:(id)arg2 channel:(id)arg3 apsForProduction:(_Bool)arg4;
+ (void)setupWithOption:(id)arg1 appKey:(id)arg2 channel:(id)arg3 apsForProduction:(_Bool)arg4 advertisingIdentifier:(id)arg5;
+ (id)sharedService;
+ (void)showLocalNotificationAtFront:(id)arg1 identifierKey:(id)arg2;
+ (void)startLogPageView:(id)arg1;
+ (void)stopLogPageView:(id)arg1;
- (void).cxx_destruct;
- (void)addAppStateNotifications;
- (void)addNotification:(id)arg1;
- (void)applicationDidBecomeActive;
- (void)applicationDidEnterBackground;
- (void)applicationDidFinishLaunch:(id)arg1;
- (void)applicationWillEnterForeground;
- (void)applicationWillResignActive;
- (void)applicationWillTerminate;
- (void)beginLogPageView:(id)arg1 duration:(int)arg2;
- (void)clearAllLocalNotifications;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)crashLogON;
- (void)dealloc;
@property(nonatomic) id <JPUSHRegisterDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteLocalNotification:(id)arg1;
- (void)deleteLocalNotificationWithIdentifierKey:(id)arg1;
- (id)findLocalNotificationWithIdentifier:(id)arg1;
- (void)findNotification:(id)arg1;
@property(nonatomic) _Bool finishLaunchReceived; // @synthesize finishLaunchReceived=_finishLaunchReceived;
- (id)getRegistrationID;
- (void)getRegistrationIDCompletionHandler:(CDUnknownBlockType)arg1;
- (id)getTagAliasInvocationWithCallback:(SEL)arg1 target:(id)arg2;
- (void)handleRemoteNotification:(id)arg1 AtLaunch:(_Bool)arg2;
- (id)init;
- (id)initPushServer;
@property(nonatomic) __weak NSDictionary *launchOptions; // @synthesize launchOptions=_launchOptions;
- (_Bool)loadPushCodeInput:(id)arg1 channel:(id)arg2 isProduction:(_Bool)arg3 advertisingIdentifier:(id)arg4;
- (_Bool)loadPushConfig:(id)arg1;
- (void)removeNotification:(id)arg1;
- (void)reportInactive;
- (void)reportLaunch;
- (void)resetBadge;
- (void)setBadge:(long long)arg1;
- (void)setLatitude:(double)arg1 longitude:(double)arg2;
- (id)setLocalNotification:(id)arg1 alertBody:(id)arg2 badge:(int)arg3 alertAction:(id)arg4 identifierKey:(id)arg5 userInfo:(id)arg6 soundName:(id)arg7 region:(id)arg8 regionTriggersOnce:(_Bool)arg9 category:(id)arg10;
- (void)setLocation:(id)arg1;
- (void)setTags:(id)arg1 alias:(id)arg2 parameters:(id)arg3 type:(unsigned long long)arg4;
- (void)setupClient;
- (void)showLocalNotificationAtFront:(id)arg1 identifierKey:(id)arg2;
- (void)standardCallback:(int)arg1 originalTags:(id)arg2 alias:(id)arg3;
- (void)startLogPageView:(id)arg1;
- (void)stopLogPageView:(id)arg1;
- (void)synchronize;
- (void)updateDeviceToken:(id)arg1;
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)userNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (_Bool)validateCallbackMethod:(id)arg1;

@end

