//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSError, NSMutableArray, NSString, NSTimer;

@interface JPUSHSRVResolver : NSObject
{
    struct _DNSServiceRef_t *_sdRef;
    struct __CFSocket *_sdRefSocket;
    struct __CFRunLoopSource *_rls;
    _Bool _finished;
    NSString *_srvName;
    id <JPUSHSRVResolverDelegate> _delegate;
    NSError *_error;
    NSMutableArray *_resultsMutable;
    NSTimer *_timer;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <JPUSHSRVResolverDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSError *error; // @synthesize error=_error;
- (id)initWithSRVName:(id)arg1;
@property(nonatomic, getter=isFinished) _Bool finished; // @synthesize finished=_finished;
- (void)processRecord:(const void *)arg1 length:(unsigned long long)arg2;
@property(readonly, copy, nonatomic) NSArray *results;
@property(readonly, nonatomic) NSMutableArray *resultsMutable; // @synthesize resultsMutable=_resultsMutable;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(readonly, copy, nonatomic) NSString *srvName; // @synthesize srvName=_srvName;
- (void)start;
- (void)startInternal;
- (void)stop;
- (void)stopWithDNSServiceError:(int)arg1;
- (void)stopWithError:(id)arg1;
- (void)stopWithTimeout;

@end

