//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSThread.h"

@class NSString;

@interface JPUSHThread : NSThread
{
    unsigned int _hasThreadName:1;
    NSString *threadName;
    unsigned int _hasThread:1;
    NSThread *myThread;
    unsigned int _hasType:1;
    unsigned long long _type;
    NSString *_threadName;
}

+ (void)aliveModeinitialize;
+ (id)builder:(unsigned long long)arg1;
+ (id)builderWithPrototype:(id)arg1;
+ (id)defaultAliveModeInstance;
+ (id)defaultNormalModeInstance;
+ (void)normalModeInitialize;
- (void).cxx_destruct;
- (id)builder:(unsigned long long)arg1;
- (void)clientThreadMain;
- (void)close;
- (void)closeMySelf;
- (id)defaultAliveModeInstance;
- (id)defaultNormalModeInstance;
- (_Bool)hasThreadName;
- (_Bool)hasType;
- (id)initWithRunLoopMode:(unsigned long long)arg1;
- (void)invokeMethodWithTarget:(id)arg1 withSEL:(SEL)arg2 withArguments:(id)arg3;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isInitialized;
- (void)setHasThreadName:(_Bool)arg1;
- (void)setHasType:(_Bool)arg1;
@property(retain) NSString *threadName; // @dynamic threadName;
@property unsigned long long type; // @synthesize type=_type;
- (id)toBuilder;

@end

