//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JPUSHReportRequest.h"

@class JPUSHPageFlow;

@interface JPUSHUserActiveReportRequest : JPUSHReportRequest
{
    JPUSHPageFlow *_actives;
    double _sessionStartTime;
    double _sessionCloseTime;
}

- (void).cxx_destruct;
@property(copy, nonatomic) JPUSHPageFlow *actives; // @synthesize actives=_actives;
- (id)init;
- (void)p_addActives;
- (_Bool)packData;
@property(nonatomic) double sessionCloseTime; // @synthesize sessionCloseTime=_sessionCloseTime;
@property(nonatomic) double sessionStartTime; // @synthesize sessionStartTime=_sessionStartTime;
- (void)setReportActives:(id)arg1 sessionStartTime:(double)arg2 sessionCloseTime:(double)arg3;
- (void)setResponseBlock;

@end

