//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JPUSHAddressConfigController : NSObject
{
    _Bool _isDebugMode;
    unsigned short _connectPort;
    NSString *_connectAddress;
    NSString *_reportAddress;
    NSString *_userAddress;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *connectAddress; // @synthesize connectAddress=_connectAddress;
@property(nonatomic) unsigned short connectPort; // @synthesize connectPort=_connectPort;
- (void)defaultDebugAddress;
- (void)defaultReleaseAddress;
- (id)init;
@property(nonatomic) _Bool isDebugMode; // @synthesize isDebugMode=_isDebugMode;
- (void)load;
- (void)parseConfigFile;
- (const char *)propertyType:(id)arg1;
@property(retain, nonatomic) NSString *reportAddress; // @synthesize reportAddress=_reportAddress;
@property(retain, nonatomic) NSString *userAddress; // @synthesize userAddress=_userAddress;
- (void)updateProperty:(void *)arg1 type:(const char *)arg2 withKey:(id)arg3;

@end

