//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JPUSHReportRequest.h"

@class NSMutableDictionary;

@interface JPUSHBadgeNumberReportRequest : JPUSHReportRequest
{
    NSMutableDictionary *_badgeBody;
    _Bool _isAgainSend;
    long long _badgeCount;
}

- (void).cxx_destruct;
@property(nonatomic) long long badgeCount; // @synthesize badgeCount=_badgeCount;
- (_Bool)cacheRequestRequired;
- (id)generateReportRequest;
- (id)init;
@property(nonatomic) _Bool isAgainSend; // @synthesize isAgainSend=_isAgainSend;
- (_Bool)isSendRequestLock;
- (id)p_generateRequestHead;
- (id)packetData;
- (void)setBadgeNumber:(unsigned int)arg1;
- (void)setIsSendRequestLock:(_Bool)arg1;
- (void)setResponseBlock;
- (_Bool)startDelaySend;

@end

