//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JPUSHNetElement.h"

#import "JPUSHJSONProtocol.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class NSMutableData, NSString, NSTimer;

@interface JPUSHRequest : JPUSHNetElement <NSCopying, NSCoding, JPUSHJSONProtocol>
{
    NSMutableData *_packetData;
    unsigned char _controlFlag;
    NSTimer *_ackTimeoutTimer;
}

- (void).cxx_destruct;
- (_Bool)ackOrRespRequired;
- (_Bool)ackOrRespRequiredForVersion1;
@property(nonatomic) __weak NSTimer *ackTimeoutTimer; // @synthesize ackTimeoutTimer=_ackTimeoutTimer;
- (_Bool)canBeQueuedIfNotLogin;
@property(nonatomic) unsigned char controlFlag; // @synthesize controlFlag=_controlFlag;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)getRidID;
- (_Bool)hasHighPriority;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqualToRequest:(id)arg1;
- (_Bool)isExclusive;
- (_Bool)isIMMessageRequest;
- (void)jpush_fromJSONValue:(id)arg1;
- (id)jpush_jsonClassType;
- (id)jpush_toJSON;
- (_Bool)loginRequired;
- (void)onAckTimeout:(id)arg1;
- (_Bool)packData;
- (id)packetData;
- (void)send;
- (void)startAckTimeoutTimer;
- (void)stopAckTimeoutTimer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

