//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JPUSHCacheProtocol.h"
#import "JPUSHJSONProtocol.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface JPUSHMemoryCache : NSObject <JPUSHCacheProtocol, NSCopying, NSCoding, JPUSHJSONProtocol>
{
    _Bool _clearWhenMemoryLow;
    long long _maxCacheCount;
    long long _cachedCount;
    NSMutableArray *_cacheKeys;
    NSMutableDictionary *_cacheObjects;
}

+ (id)shareInstance;
- (void).cxx_destruct;
@property(retain) NSMutableArray *cacheKeys; // @synthesize cacheKeys=_cacheKeys;
@property(retain) NSMutableDictionary *cacheObjects; // @synthesize cacheObjects=_cacheObjects;
@property(nonatomic) long long cachedCount; // @synthesize cachedCount=_cachedCount;
@property(nonatomic) _Bool clearWhenMemoryLow; // @synthesize clearWhenMemoryLow=_clearWhenMemoryLow;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (void)handleNotification:(id)arg1;
- (_Bool)hasObjectForKey:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)jpush_fromJSONValue:(id)arg1;
- (id)jpush_jsonClassType;
- (id)jpush_toJSON;
@property(nonatomic) long long maxCacheCount; // @synthesize maxCacheCount=_maxCacheCount;
- (id)objectForKey:(id)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
- (void)observeNotification:(id)arg1;
- (void)removeAllObjects;
- (void)removeFirstObject;
- (void)removeObject:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)removeObjectsAtIndexes:(struct _NSRange)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)unObserveAllNotifications;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

