//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JPUSHUdpSocket, NSData, NSTimer;

@interface JPUSHUdpPacket : NSObject
{
    int _type;
    NSData *_buffer;
    NSData *_address;
    double _timeout;
    NSTimer *_timeoutTimer;
    JPUSHUdpSocket *_udpSocket;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSData *address; // @synthesize address=_address;
@property(retain, nonatomic) NSData *buffer; // @synthesize buffer=_buffer;
- (id)description;
- (id)initWithType:(int)arg1 data:(id)arg2 address:(id)arg3 timeout:(double)arg4 udpSocket:(id)arg5;
- (void)invalidTimeoutTimer;
@property(nonatomic) double timeout; // @synthesize timeout=_timeout;
@property(nonatomic) int type; // @synthesize type=_type;
- (void)timeoutCallback:(id)arg1;
@property(readonly, nonatomic) __weak NSTimer *timeoutTimer; // @synthesize timeoutTimer=_timeoutTimer;
@property(readonly, nonatomic) __weak JPUSHUdpSocket *udpSocket; // @synthesize udpSocket=_udpSocket;

@end

