//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JPUSHAbstractLogger.h"

@class NSObject<OS_dispatch_source>;

@interface JPUSHAbstractDatabaseLogger : JPUSHAbstractLogger
{
    unsigned long long _saveThreshold;
    double _saveInterval;
    double _maxAge;
    double _deleteInterval;
    _Bool _deleteOnEverySave;
    _Bool _saveTimerSuspended;
    unsigned long long _unsavedCount;
    unsigned long long _unsavedTime;
    NSObject<OS_dispatch_source> *_saveTimer;
    unsigned long long _lastDeleteTime;
    NSObject<OS_dispatch_source> *_deleteTimer;
}

- (void).cxx_destruct;
- (void)createAndStartDeleteTimer;
- (void)createSuspendedSaveTimer;
- (void)db_delete;
- (_Bool)db_log:(id)arg1;
- (void)db_save;
- (void)db_saveAndDelete;
- (void)dealloc;
@property double deleteInterval;
- (void)deleteOldLogEntries;
@property _Bool deleteOnEverySave;
- (void)destroyDeleteTimer;
- (void)destroySaveTimer;
- (void)didAddLogger;
- (void)flush;
- (id)init;
- (void)logMessage:(id)arg1;
@property double maxAge;
- (void)performDelete;
- (void)performSaveAndSuspendSaveTimer;
@property double saveInterval;
- (void)savePendingLogEntries;
@property unsigned long long saveThreshold;
- (void)updateAndResumeSaveTimer;
- (void)updateDeleteTimer;
- (void)willRemoveLogger;

@end

