//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JPUSHResponse.h"

@class NSString;

@interface JPUSHRegistrationResponse : JPUSHResponse
{
    unsigned long long _uid;
    NSString *_password;
    NSString *_registrationID;
}

- (void).cxx_destruct;
- (id)description;
- (void)handleReceipt;
- (id)initWithBuffer:(const char *)arg1 length:(unsigned short)arg2;
@property(readonly, retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(readonly, nonatomic) NSString *registrationID; // @synthesize registrationID=_registrationID;
@property(nonatomic) unsigned long long uid; // @synthesize uid=_uid;

@end

