//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JPUSHKeychain, NSMutableDictionary, NSString, NSTimer;

@interface JPUSHUserDefaultsController : NSObject
{
    NSMutableDictionary *_infoDictionary;
    JPUSHKeychain *_defaultKeychain;
    NSTimer *_delayVerifyUserDefaultsTimer;
    _Bool _isDelayedVerify;
    _Bool _isFirstStart;
    NSString *_lastSucceedConnectionAddress;
    _Bool _verified;
    unsigned int _sisHostIndex;
    NSString *_appKey;
    NSString *_currentDeviceToken;
    NSString *_oldDeviceToken;
    NSString *_openUdid;
    unsigned long long _uid;
    NSString *_password;
    NSString *_registrationID;
}

+ (_Bool)isFirtsStart;
- (void).cxx_destruct;
@property(nonatomic, setter=setIMFlag:) unsigned char IMFlag;
@property(readonly, retain, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(retain, nonatomic) NSString *backupHttpReportAddress; // @dynamic backupHttpReportAddress;
@property(retain, nonatomic) NSString *backupUdpReportAddress; // @dynamic backupUdpReportAddress;
@property(retain, nonatomic) NSString *backupUserReportAddress; // @dynamic backupUserReportAddress;
- (void)clearAllCache;
- (id)createDeviceID;
@property(copy, nonatomic) NSString *currentDeviceToken; // @synthesize currentDeviceToken=_currentDeviceToken;
@property(retain, nonatomic) NSString *defaultConAddress; // @dynamic defaultConAddress;
- (void)delayVerifyUserDefaults;
- (id)getDeviceID;
@property(readonly, nonatomic) NSMutableDictionary *infoDictionary; // @synthesize infoDictionary=_infoDictionary;
- (id)initWithBundleIdentifier:(id)arg1 appkey:(id)arg2;
- (unsigned long long)integerFromStringOrNumber:(id)arg1;
- (_Bool)isAppRegistered;
@property(retain, nonatomic) NSString *lastSucceedConnectionAddress; // @dynamic lastSucceedConnectionAddress;
@property(copy, nonatomic) NSString *oldDeviceToken; // @synthesize oldDeviceToken=_oldDeviceToken;
@property(readonly, copy, nonatomic) NSString *openUdid; // @synthesize openUdid=_openUdid;
@property(readonly, retain, nonatomic) NSString *password; // @synthesize password=_password;
- (void)readContentFromFile:(id)arg1;
- (id)readFromFile;
- (id)readFromKeychain;
@property(readonly, retain, nonatomic) NSString *registrationID; // @synthesize registrationID=_registrationID;
@property(nonatomic) unsigned int sisHostIndex; // @synthesize sisHostIndex=_sisHostIndex;
- (void)setUid:(unsigned long long)arg1 password:(id)arg2 registrationID:(id)arg3;
- (void)setUploadedDeviceToken:(id)arg1;
- (_Bool)synchronize;
- (_Bool)synchronizeCacheFile;
- (_Bool)synchronizeDocumentFile;
- (_Bool)synchronizeTarget:(unsigned long long)arg1;
- (void)transFromOldUserDefaults:(id)arg1;
- (id)transferToStringIfNeed:(id)arg1;
@property(readonly, nonatomic) unsigned long long uid; // @synthesize uid=_uid;
- (_Bool)useDefaultAddress:(id)arg1;
@property(readonly, nonatomic) _Bool verified; // @synthesize verified=_verified;
- (void)verifyUserDefaults;
- (void)verifyUserDefaultsTimeout:(id)arg1;
- (_Bool)writeToFile;

@end

