//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSDictionary, NSString;

@interface JPUSHLogFileInfo : NSObject
{
    NSString *_filePath;
    NSString *_fileName;
    NSDictionary *_fileAttributes;
    NSDate *_creationDate;
    NSDate *_modificationDate;
    unsigned long long _fileSize;
    NSString *filePath;
}

+ (id)logFileWithPath:(id)arg1;
- (void).cxx_destruct;
- (void)addExtendedAttributeWithName:(id)arg1;
@property(readonly, nonatomic) double age; // @dynamic age;
@property(readonly, nonatomic) NSDate *creationDate; // @dynamic creationDate;
- (id)description;
@property(readonly, nonatomic) NSDictionary *fileAttributes; // @dynamic fileAttributes;
@property(readonly, nonatomic) NSString *fileName; // @dynamic fileName;
@property(readonly, nonatomic) NSString *filePath; // @synthesize filePath;
@property(readonly, nonatomic) unsigned long long fileSize; // @dynamic fileSize;
- (_Bool)hasExtendedAttributeWithName:(id)arg1;
- (id)initWithFilePath:(id)arg1;
@property(nonatomic) _Bool isArchived; // @dynamic isArchived;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) NSDate *modificationDate; // @dynamic modificationDate;
- (void)removeExtendedAttributeWithName:(id)arg1;
- (void)renameFile:(id)arg1;
- (void)reset;
- (long long)reverseCompareByCreationDate:(id)arg1;
- (long long)reverseCompareByModificationDate:(id)arg1;

@end

