//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JPUSHLogFormatter.h"

@class JPUSHLoggingContextSet, NSArray, NSString;

@interface JPUSHContextBlacklistFilterLogFormatter : NSObject <JPUSHLogFormatter>
{
    JPUSHLoggingContextSet *_contextSet;
}

- (void).cxx_destruct;
- (void)addToBlacklist:(unsigned long long)arg1;
@property(readonly, copy) NSArray *blacklist;
- (id)formatLogMessage:(id)arg1;
- (id)init;
- (_Bool)isOnBlacklist:(unsigned long long)arg1;
- (void)removeFromBlacklist:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

