//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JPUSHReportRequest.h"

@class JPUSHLocationInfoController;

@interface JPUSHLocationReportRequest : JPUSHReportRequest
{
    JPUSHLocationInfoController *_locationInfoController;
}

- (void).cxx_destruct;
- (id)init;
@property(copy, nonatomic) JPUSHLocationInfoController *locationInfoController; // @synthesize locationInfoController=_locationInfoController;
- (_Bool)p_checkLocationInfoChanged:(id)arg1;
- (_Bool)packData;
- (void)setResponseBlock;

@end

