//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JPUSHPushConfigController : NSObject
{
    _Bool _shouldUploadAdvertisingIdentifier;
    int _configApsEnvironment;
    NSString *_applicationKey;
    NSString *_pushChanel;
    NSString *_advertisingIdentifier;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *advertisingIdentifier; // @synthesize advertisingIdentifier=_advertisingIdentifier;
@property(readonly, nonatomic) NSString *applicationKey; // @synthesize applicationKey=_applicationKey;
@property(readonly, nonatomic) int configApsEnvironment; // @synthesize configApsEnvironment=_configApsEnvironment;
- (_Bool)isValidAppKey:(id)arg1;
- (_Bool)isVerifyIDFAString:(id)arg1;
- (_Bool)loadWithUrl:(id)arg1;
- (id)lowerCase:(id)arg1;
@property(readonly, nonatomic) NSString *pushChanel; // @synthesize pushChanel=_pushChanel;
- (_Bool)setAppKey:(id)arg1 channel:(id)arg2 apsProduction:(_Bool)arg3 advertisingIdentifier:(id)arg4;
- (void)setNewAdvertisingIdentifier:(id)arg1;
@property _Bool shouldUploadAdvertisingIdentifier; // @synthesize shouldUploadAdvertisingIdentifier=_shouldUploadAdvertisingIdentifier;

@end

