//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JPUSHJSONProtocol.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class NSMutableArray, NSString;

@interface JPUSHPageFlow : NSObject <NSCopying, NSCoding, JPUSHJSONProtocol>
{
    NSMutableArray *_pageFlow;
    NSMutableArray *_tempFlow;
    double _duration;
    NSString *_reportDays;
    NSString *_reportTime;
}

- (void).cxx_destruct;
- (void)AddPage:(id)arg1;
- (void)clearFlow;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)jpush_fromJSONValue:(id)arg1;
- (id)jpush_jsonClassType;
- (id)jpush_toJSON;
- (void)p_addNewPage:(id)arg1;
- (void)p_clearPageFlow;
- (void)p_clearTempFlow;
- (void)p_saveTempFlow:(id)arg1;
@property(retain) NSMutableArray *pageFlow; // @synthesize pageFlow=_pageFlow;
- (_Bool)readFromFile;
@property(retain, nonatomic) NSString *reportDays; // @synthesize reportDays=_reportDays;
@property(retain, nonatomic) NSString *reportTime; // @synthesize reportTime=_reportTime;
@property(retain) NSMutableArray *tempFlow; // @synthesize tempFlow=_tempFlow;
- (void)writeToFile;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

