//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JPUSHASLLogCapture : NSObject
{
}

+ (void)aslMessageRecieved:(struct __asl_object_s *)arg1;
+ (void)captureAslLogs;
+ (unsigned long long)captureLevel;
+ (void)configureAslQuery:(struct __asl_object_s *)arg1;
+ (void)initialize;
+ (void)setCaptureLevel:(unsigned long long)arg1;
+ (void)start;
+ (void)stop;

@end

