//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSArray, UILocalNotification;

@interface JPushNotificationIdentifier : NSObject <NSCopying, NSCoding>
{
    _Bool _delivered;
    NSArray *_identifiers;
    UILocalNotification *_notificationObj;
    CDUnknownBlockType _findCompletionHandler;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) _Bool delivered; // @synthesize delivered=_delivered;
- (void)encodeWithCoder:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType findCompletionHandler; // @synthesize findCompletionHandler=_findCompletionHandler;
@property(copy, nonatomic) NSArray *identifiers; // @synthesize identifiers=_identifiers;
- (id)initWithCoder:(id)arg1;
@property(copy, nonatomic) UILocalNotification *notificationObj; // @synthesize notificationObj=_notificationObj;

@end

