//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ArticleShareViewDelegate.h"

@class NSString, UIImageView, UIView;

@interface LongImageViewController : UIViewController <ArticleShareViewDelegate>
{
    UIImageView *_imageView;
    UIView *_toolbar;
}

- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithImage:(id)arg1;
- (void)pushActivityVC:(id)arg1;
- (void)requestPhotosAccess:(CDUnknownBlockType)arg1;
- (void)saveAciton;
- (void)saveImage:(id)arg1 toAlbumWithName:(id)arg2 fin:(CDUnknownBlockType)arg3;
@property(nonatomic) __weak UIView *toolbar; // @synthesize toolbar=_toolbar;
- (void)shareAction;
- (id)syncSaveImageWithPhotos:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

