//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MASG3Constraint.h"

#import "NSCopying.h"

@class MASG3LayoutConstraint, MASG3ViewAttribute, UIView;

@interface MASG3ViewConstraint : MASG3Constraint <NSCopying>
{
    _Bool _hasLayoutRelation;
    _Bool _useAnimator;
    float _layoutPriority;
    MASG3ViewAttribute *_firstViewAttribute;
    MASG3ViewAttribute *_secondViewAttribute;
    UIView *_installedView;
    MASG3LayoutConstraint *_layoutConstraint;
    long long _layoutRelation;
    double _layoutMultiplier;
    double _layoutConstant;
    id _masG3_key;
}

+ (id)installedConstraintsForView:(id)arg1;
- (void).cxx_destruct;
- (void)activate;
- (id)addConstraintWithLayoutAttribute:(long long)arg1;
- (id)and;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)deactivate;
- (CDUnknownBlockType)dividedBy;
- (CDUnknownBlockType)equalToWithRelation;
@property(readonly, nonatomic) MASG3ViewAttribute *firstViewAttribute; // @synthesize firstViewAttribute=_firstViewAttribute;
- (_Bool)hasBeenInstalled;
@property(nonatomic) _Bool hasLayoutRelation; // @synthesize hasLayoutRelation=_hasLayoutRelation;
- (id)initWithFirstViewAttribute:(id)arg1;
- (void)install;
@property(nonatomic) __weak UIView *installedView; // @synthesize installedView=_installedView;
- (_Bool)isActive;
- (CDUnknownBlockType)key;
@property(nonatomic) double layoutConstant; // @synthesize layoutConstant=_layoutConstant;
@property(nonatomic) __weak MASG3LayoutConstraint *layoutConstraint; // @synthesize layoutConstraint=_layoutConstraint;
- (id)layoutConstraintSimilarTo:(id)arg1;
@property(nonatomic) double layoutMultiplier; // @synthesize layoutMultiplier=_layoutMultiplier;
@property(nonatomic) float layoutPriority; // @synthesize layoutPriority=_layoutPriority;
@property(nonatomic) long long layoutRelation; // @synthesize layoutRelation=_layoutRelation;
@property(retain, nonatomic) id masG3_key; // @synthesize masG3_key=_masG3_key;
- (CDUnknownBlockType)multipliedBy;
- (CDUnknownBlockType)priority;
@property(retain, nonatomic) MASG3ViewAttribute *secondViewAttribute; // @synthesize secondViewAttribute=_secondViewAttribute;
- (void)setCenterOffset:(struct CGPoint)arg1;
- (void)setInsets:(struct UIEdgeInsets)arg1;
- (void)setOffset:(double)arg1;
- (void)setSizeOffset:(struct CGSize)arg1;
@property(nonatomic) _Bool useAnimator; // @synthesize useAnimator=_useAnimator;
- (_Bool)supportsActiveProperty;
- (void)uninstall;
- (id)with;

@end

