//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MASG3ConstraintDelegate.h"

@class MASG3Constraint, NSMutableArray, NSString, UIView;

@interface MASG3ConstraintMaker : NSObject <MASG3ConstraintDelegate>
{
    _Bool _updateExisting;
    _Bool _removeExisting;
    UIView *_view;
    NSMutableArray *_constraints;
}

- (void).cxx_destruct;
- (id)addConstraintWithAttributes:(long long)arg1;
- (id)addConstraintWithLayoutAttribute:(long long)arg1;
@property(readonly, nonatomic) CDUnknownBlockType attributes;
@property(readonly, nonatomic) MASG3Constraint *baseline;
@property(readonly, nonatomic) MASG3Constraint *bottom;
@property(readonly, nonatomic) MASG3Constraint *bottomMargin;
@property(readonly, nonatomic) MASG3Constraint *center;
@property(readonly, nonatomic) MASG3Constraint *centerX;
@property(readonly, nonatomic) MASG3Constraint *centerXWithinMargins;
@property(readonly, nonatomic) MASG3Constraint *centerY;
@property(readonly, nonatomic) MASG3Constraint *centerYWithinMargins;
- (id)constraint:(id)arg1 addConstraintWithLayoutAttribute:(long long)arg2;
- (void)constraint:(id)arg1 shouldBeReplacedWithConstraint:(id)arg2;
@property(retain, nonatomic) NSMutableArray *constraints; // @synthesize constraints=_constraints;
@property(readonly, nonatomic) MASG3Constraint *edges;
- (CDUnknownBlockType)group;
@property(readonly, nonatomic) MASG3Constraint *height;
- (id)initWithView:(id)arg1;
- (id)install;
@property(readonly, nonatomic) MASG3Constraint *leading;
@property(readonly, nonatomic) MASG3Constraint *leadingMargin;
@property(readonly, nonatomic) MASG3Constraint *left;
@property(readonly, nonatomic) MASG3Constraint *leftMargin;
@property(nonatomic) _Bool removeExisting; // @synthesize removeExisting=_removeExisting;
@property(readonly, nonatomic) MASG3Constraint *right;
@property(readonly, nonatomic) MASG3Constraint *rightMargin;
@property(nonatomic) _Bool updateExisting; // @synthesize updateExisting=_updateExisting;
@property(nonatomic) __weak UIView *view; // @synthesize view=_view;
@property(readonly, nonatomic) MASG3Constraint *size;
@property(readonly, nonatomic) MASG3Constraint *top;
@property(readonly, nonatomic) MASG3Constraint *topMargin;
@property(readonly, nonatomic) MASG3Constraint *trailing;
@property(readonly, nonatomic) MASG3Constraint *trailingMargin;
@property(readonly, nonatomic) MASG3Constraint *width;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

