//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class ArticleModel, UIButton, UIImageView, UILabel;

@interface MatrixTableViewCell : UITableViewCell
{
    _Bool _isFromeMatrix;
    ArticleModel *_model;
    CDUnknownBlockType _moreButtomClick;
    CDUnknownBlockType _articleButtomClick;
    CDUnknownBlockType _iconButtomClick;
    UIImageView *_iconImage;
    UILabel *_userNameLabel;
    UILabel *_titleLabel;
    UIImageView *_bigImageView;
    UILabel *_timeLabel;
    UIButton *_commentButton;
    UIButton *_loveButton;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType articleButtomClick; // @synthesize articleButtomClick=_articleButtomClick;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *bigImageView; // @synthesize bigImageView=_bigImageView;
- (void)clickArticleButtonAction:(id)arg1;
- (void)clickIconImageAction:(id)arg1;
- (void)clickMoreButtonAction:(id)arg1;
@property(nonatomic) __weak UIButton *commentButton; // @synthesize commentButton=_commentButton;
@property(copy, nonatomic) CDUnknownBlockType iconButtomClick; // @synthesize iconButtomClick=_iconButtomClick;
@property(nonatomic) __weak UIImageView *iconImage; // @synthesize iconImage=_iconImage;
@property(nonatomic) _Bool isFromeMatrix; // @synthesize isFromeMatrix=_isFromeMatrix;
@property(nonatomic) __weak UIButton *loveButton; // @synthesize loveButton=_loveButton;
@property(retain, nonatomic) ArticleModel *model; // @synthesize model=_model;
@property(copy, nonatomic) CDUnknownBlockType moreButtomClick; // @synthesize moreButtomClick=_moreButtomClick;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)setTitleWith:(id)arg1;
@property(nonatomic) __weak UILabel *userNameLabel; // @synthesize userNameLabel=_userNameLabel;

@end

