//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "LoginViewControllerDelegate.h"
#import "MFMailComposeViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UIButton, UIImageView, UILabel, UITableView, UserModel;

@interface MeViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, LoginViewControllerDelegate, MFMailComposeViewControllerDelegate>
{
    UITableView *_tableView;
    NSArray *_titleArray;
    UIButton *_loginButton;
    UIImageView *_avatarImageView;
    UILabel *_nicknameLabel;
    UILabel *_bioLabel;
    UIButton *_editorBuutton;
    UserModel *_user;
    UILabel *_versionNum;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
- (void)bigButtonAction:(id)arg1;
@property(nonatomic) __weak UILabel *bioLabel; // @synthesize bioLabel=_bioLabel;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)editorButtonClickAction:(id)arg1;
@property(nonatomic) __weak UIButton *editorBuutton; // @synthesize editorBuutton=_editorBuutton;
- (void)iconClickAction:(id)arg1;
@property(nonatomic) __weak UIButton *loginButton; // @synthesize loginButton=_loginButton;
- (void)loginButtonClickAction:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
@property(nonatomic) __weak UILabel *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
- (void)pushRegistVierController:(id)arg1;
- (void)sendEmail;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSArray *titleArray; // @synthesize titleArray=_titleArray;
@property(retain, nonatomic) UserModel *user; // @synthesize user=_user;
@property(nonatomic) __weak UILabel *versionNum; // @synthesize versionNum=_versionNum;
- (void)showSendMailErrorAlert;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateUserInfo;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

