//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MJRefreshBackStateFooter.h"

@class UIActivityIndicatorView, UIImageView;

@interface MJRefreshBackNormalFooter : MJRefreshBackStateFooter
{
    UIImageView *_arrowView;
    long long _activityIndicatorViewStyle;
    UIActivityIndicatorView *_loadingView;
}

- (void).cxx_destruct;
@property(nonatomic) long long activityIndicatorViewStyle; // @synthesize activityIndicatorViewStyle=_activityIndicatorViewStyle;
@property(readonly, nonatomic) __weak UIImageView *arrowView;
@property(nonatomic) __weak UIActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
- (void)placeSubviews;
- (void)prepare;
- (void)setState:(long long)arg1;

@end

