//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface MobClickEnvelope : NSObject
{
    NSData *_identityMD5;
    char *_entityMD5;
    NSString *_signatureString;
    NSString *_guidString;
    NSString *_checksum;
    int _timestamp;
    int _serialNum;
    int _length;
    NSData *_signature;
    NSData *_guid;
}

+ (id)sharedInstance;
- (void)buildGUIDWithData:(unsigned char [32])arg1;
- (void)buildSerialNum;
- (void)checkExchangeData;
- (void)dealloc;
- (id)entityData;
- (void)generateChecksum;
@property(retain, nonatomic) NSData *guid; // @synthesize guid=_guid;
- (id)init;
- (_Bool)makeEnvelopeData;
- (id)mergeEntityAndIdentity;
@property(retain, nonatomic) NSData *signature; // @synthesize signature=_signature;
- (void)setSignatureWithData:(id)arg1;
- (id)toEnvelopeWithEntity:(id)arg1;

@end

