//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSOperationQueue, NSString;

@interface MobClickInternal : NSObject
{
    NSOperationQueue *_sendLogQueue;
    NSMutableArray *_terminates;
    NSMutableArray *_events;
    NSMutableArray *_errors;
    NSMutableArray *_ekv;
    NSMutableArray *_tmpContainer;
    NSDictionary *_error_support_info;
    NSString *_sessionID;
    NSMutableArray *_pageItems;
    NSMutableDictionary *_pageItemsHash;
    NSMutableDictionary *_ekvBeginTimes;
    NSMutableDictionary *_eventBeginTimes;
}

+ (void)installUncaughtExceptionHandler;
+ (void)setErrorSupportInfo:(id)arg1;
+ (id)sharedInstance;
- (void)addEvent:(id)arg1 inContainer:(id)arg2;
- (void)archiveCacheToFile;
- (void)archiveObjects:(id)arg1;
- (id)archiveObjectsWithHeader:(_Bool)arg1;
- (id)arrayWithEventType:(int)arg1;
- (void)beginPerformJob;
- (void)buildDummySession;
- (_Bool)checkEventLimit;
- (void)dealloc;
@property(retain) NSMutableArray *ekv; // @synthesize ekv=_ekv;
- (void)ekvBegin:(id)arg1;
- (void)ekvEnd:(id)arg1;
- (void)error:(id)arg1;
@property(retain) NSDictionary *error_support_info; // @synthesize error_support_info=_error_support_info;
@property(retain) NSMutableArray *errors; // @synthesize errors=_errors;
- (void)eventBegin:(id)arg1;
- (void)eventEnd:(id)arg1;
@property(retain) NSMutableArray *events; // @synthesize events=_events;
- (void)generateEnvelopeFile;
- (_Bool)hasJob;
- (id)header;
- (id)init;
- (void)loadCache;
- (id)loadCacheFile;
- (void)loadCacheFromTempContainer;
- (void)removeCacheData;
- (void)removeInstanceMsgs;
- (void)removeSessions;
- (void)saveAndCleanCache;
- (void)saveCrashInfo:(id)arg1;
@property(copy, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
- (void)setEventSessionID:(id)arg1;
@property(retain) NSMutableArray *terminates; // @synthesize terminates=_terminates;
- (void)stopSession:(double)arg1;
- (void)unarchiveErrors:(id)arg1;
- (void)unarchiveEvents:(id)arg1;
- (void)unarchiveObjects:(id)arg1;
- (void)unarchiveSessions:(id)arg1;
- (void)validateEnvelopeFiles:(id)arg1;
- (void)workEvent:(id)arg1;

@end

