//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MobClickSession : NSObject
{
    _Bool _observerRegistered;
    _Bool _appInBackGround;
    _Bool _appBeKilling;
    _Bool _appCrashed;
    int _sessionStatus;
    double _lastLaunchTime;
}

+ (void)profileSignInPUID:(id)arg1;
+ (void)profileSignInPUID:(id)arg1 withProvider:(id)arg2;
+ (void)profileSignOff;
+ (id)sharedInstance;
+ (void)signInPUID:(id)arg1 provider:(id)arg2;
+ (void)startWithAppkey:(id)arg1;
+ (void)startWithAppkey:(id)arg1 reportPolicy:(int)arg2 channelId:(id)arg3;
- (void)appActivate:(id)arg1;
@property(nonatomic) _Bool appBeKilling; // @synthesize appBeKilling=_appBeKilling;
@property(nonatomic) _Bool appCrashed; // @synthesize appCrashed=_appCrashed;
@property(nonatomic) _Bool appInBackGround; // @synthesize appInBackGround=_appInBackGround;
- (void)appInactivate:(id)arg1;
- (void)beginSessionTime;
- (double)endSessionTime;
- (void)ensureSessionLaunch;
@property(nonatomic) double lastLaunchTime; // @synthesize lastLaunchTime=_lastLaunchTime;
@property(nonatomic) _Bool observerRegistered; // @synthesize observerRegistered=_observerRegistered;
@property(nonatomic) int sessionStatus; // @synthesize sessionStatus=_sessionStatus;

@end

