//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData, NSString, NSThread;

@interface MOBFTCPClient : NSObject
{
    CDStruct_e097db04 *_context;
    struct __CFReadStream *_readStream;
    struct __CFWriteStream *_writeStream;
    struct __CFRunLoop *_runloopRef;
    NSThread *_workerThread;
    unsigned int _port;
    NSString *_host;
    NSMutableData *_writeBufferData;
    unsigned long long _writeBufferOffset;
    CDUnknownBlockType _connectedHandler;
    CDUnknownBlockType _disconnectedHandler;
    CDUnknownBlockType _recevieDataHandler;
}

- (void).cxx_destruct;
- (_Bool)connect;
@property(copy, nonatomic) CDUnknownBlockType connectedHandler; // @synthesize connectedHandler=_connectedHandler;
- (void)dealloc;
- (void)disconnect;
@property(copy, nonatomic) CDUnknownBlockType disconnectedHandler; // @synthesize disconnectedHandler=_disconnectedHandler;
@property(copy, nonatomic) NSString *host; // @synthesize host=_host;
- (id)initWithHost:(id)arg1 port:(unsigned int)arg2;
- (void)onConnected:(CDUnknownBlockType)arg1;
- (void)onDisconnected:(CDUnknownBlockType)arg1;
- (void)onReceiveData:(CDUnknownBlockType)arg1;
@property(nonatomic) unsigned int port; // @synthesize port=_port;
@property(copy, nonatomic) CDUnknownBlockType recevieDataHandler; // @synthesize recevieDataHandler=_recevieDataHandler;
- (void)sendData:(id)arg1;
@property(retain, nonatomic) NSMutableData *writeBufferData; // @synthesize writeBufferData=_writeBufferData;
@property(nonatomic) unsigned long long writeBufferOffset; // @synthesize writeBufferOffset=_writeBufferOffset;
- (_Bool)setup;
- (void)writeDataToStream;

@end

