//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSXMLParserDelegate.h"

@class MOBFXmlNode, NSString, NSXMLParser;

@interface MOBFXml : NSObject <NSXMLParserDelegate>
{
    MOBFXmlNode *_rootNode;
    NSXMLParser *_parser;
    MOBFXmlNode *_curNode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MOBFXmlNode *curNode; // @synthesize curNode=_curNode;
- (id)dictionaryValue;
- (id)initWithPath:(id)arg1;
- (id)initWithString:(id)arg1;
@property(retain, nonatomic) NSXMLParser *parser; // @synthesize parser=_parser;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
@property(retain, nonatomic) MOBFXmlNode *rootNode; // @synthesize rootNode=_rootNode;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

