//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MOBFImageObserver, NSDictionary, NSTimer, UIActivityIndicatorView, UIButton, UIImageView;

@interface MOBFAdViewController : UIViewController
{
    NSDictionary *_adInfo;
    NSTimer *_timer;
    UIImageView *_adImageView;
    UIButton *_closeButton;
    UIActivityIndicatorView *_indicatorView;
    CDUnknownBlockType _skipHandler;
    CDUnknownBlockType _openHandler;
    MOBFImageObserver *_imageObserver;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *adImageView; // @synthesize adImageView=_adImageView;
@property(retain, nonatomic) NSDictionary *adInfo; // @synthesize adInfo=_adInfo;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
- (void)closeButtonClickHandler:(id)arg1;
- (void)dealloc;
- (void)delayClose;
@property(retain, nonatomic) MOBFImageObserver *imageObserver; // @synthesize imageObserver=_imageObserver;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
- (id)initWithAdInfo:(id)arg1;
- (void)onOpen:(CDUnknownBlockType)arg1;
- (void)onSkip:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) CDUnknownBlockType openHandler; // @synthesize openHandler=_openHandler;
@property(copy, nonatomic) CDUnknownBlockType skipHandler; // @synthesize skipHandler=_skipHandler;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)updateData;
- (void)viewDidLoad;

@end

