//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableString, NSString;

@interface MQPTrackModel : NSObject <NSCoding>
{
    NSString *_logTime;
    NSString *_orderInfo;
    NSString *_appInfo;
    NSString *_sdkInfo;
    NSString *_tidInfo;
    NSString *_devInfo;
    NSMutableString *_errorTrack;
}

- (void).cxx_destruct;
- (void)addErrorTrack:(id)arg1;
@property(copy, nonatomic) NSString *appInfo; // @synthesize appInfo=_appInfo;
- (id)appendTracks:(id)arg1 withTrack:(id)arg2;
- (id)date;
- (id)description;
@property(copy, nonatomic) NSString *devInfo; // @synthesize devInfo=_devInfo;
- (void)encodeWithCoder:(id)arg1;
@property(copy, nonatomic) NSMutableString *errorTrack; // @synthesize errorTrack=_errorTrack;
- (id)fetchAppInfo;
- (id)fetchDevInfo;
- (id)fetchOrderInfo:(id)arg1;
- (id)fetchSdkInfo;
- (id)fetchTidInfo;
- (id)getTrackLogData;
- (id)initWithCoder:(id)arg1;
- (id)initWithOrderInfo:(id)arg1;
@property(copy, nonatomic) NSString *logTime; // @synthesize logTime=_logTime;
@property(copy, nonatomic) NSString *orderInfo; // @synthesize orderInfo=_orderInfo;
@property(copy, nonatomic) NSString *sdkInfo; // @synthesize sdkInfo=_sdkInfo;
@property(copy, nonatomic) NSString *tidInfo; // @synthesize tidInfo=_tidInfo;
- (_Bool)shouldUpload;

@end

