//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSString, UIButton, UICollectionView, UICollectionViewFlowLayout, UIView;

@interface MyFavoritedViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource>
{
    UICollectionView *_collectionView;
    UICollectionViewFlowLayout *_flowLayout;
    UIView *_channel;
    UIView *_bottomLine;
    UIButton *_selectButton;
}

- (void).cxx_destruct;
- (void)addChannelView;
- (void)addCollectionView;
@property(nonatomic) __weak UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(nonatomic) __weak UIView *channel; // @synthesize channel=_channel;
- (void)channelButtonClick:(id)arg1;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)didReceiveMemoryWarning;
@property(nonatomic) __weak UICollectionViewFlowLayout *flowLayout; // @synthesize flowLayout=_flowLayout;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
@property(nonatomic) __weak UIButton *selectButton; // @synthesize selectButton=_selectButton;
- (void)setupUI;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

