//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "FavoritedTableViewControllerDelegate.h"

@class FavoritedTableViewController, NSString;

@interface MyFavoritedViewControllerCell : UICollectionViewCell <FavoritedTableViewControllerDelegate>
{
    NSString *_channel;
    CDUnknownBlockType _callback;
    FavoritedTableViewController *_contentVC;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(copy, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(retain, nonatomic) FavoritedTableViewController *contentVC; // @synthesize contentVC=_contentVC;
- (void)favoritedViewControllerPush:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

