//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ArticleModel, CommentModel, UserModel;

@protocol NotificationTableViewDelegate <NSObject>
- (void)pushViewControllerWith:(ArticleModel *)arg1 user:(UserModel *)arg2 commentID:(CommentModel *)arg3;
@end

