//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "TTTAttributedLabelDelegate.h"

@class NSString, NotificationModel, TTTAttributedLabel, UIButton, UIImageView, UILabel;

@interface NotificationTableViewCell : UITableViewCell <TTTAttributedLabelDelegate>
{
    NotificationModel *_model;
    CDUnknownBlockType _turnToStandard;
    CDUnknownBlockType _turnToHome;
    CDUnknownBlockType _turnToMatrix;
    CDUnknownBlockType _feedback;
    CDUnknownBlockType _turnToArticle;
    CDUnknownBlockType _turnToComment;
    CDUnknownBlockType _turnToUser;
    CDUnknownBlockType _updateStatu;
    UIImageView *_typeImageView;
    UILabel *_contentLabel;
    UILabel *_descLabel;
    UILabel *_timeLabel;
    long long _articleIntex;
    UIButton *_button;
    TTTAttributedLabel *_ttLabel;
    TTTAttributedLabel *_descTTLabel;
    unsigned long long _comment_type;
    long long _commentIntex;
}

- (void).cxx_destruct;
- (void)addButtonWithFrame:(struct CGRect)arg1 action:(SEL)arg2;
@property(nonatomic) long long articleIntex; // @synthesize articleIntex=_articleIntex;
- (void)articleViewController;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)awakeFromNib;
@property(nonatomic) __weak UIButton *button; // @synthesize button=_button;
- (struct CGRect)calculateFrameWith:(id)arg1 from:(id)arg2;
@property(nonatomic) long long commentIntex; // @synthesize commentIntex=_commentIntex;
- (void)commentViewController;
@property(nonatomic) unsigned long long comment_type; // @synthesize comment_type=_comment_type;
@property(nonatomic) __weak UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(nonatomic) __weak UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(nonatomic) __weak TTTAttributedLabel *descTTLabel; // @synthesize descTTLabel=_descTTLabel;
- (void)descTTlabelAddtarget:(id)arg1 withTarget:(id)arg2:(id)arg3 comment:(id)arg4 name:(id)arg5;
@property(copy, nonatomic) CDUnknownBlockType feedback; // @synthesize feedback=_feedback;
- (void)feedbackView;
- (void)homeView;
- (void)matrixView;
@property(retain, nonatomic) NotificationModel *model; // @synthesize model=_model;
- (void)setDesc:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak TTTAttributedLabel *ttLabel; // @synthesize ttLabel=_ttLabel;
@property(copy, nonatomic) CDUnknownBlockType turnToArticle; // @synthesize turnToArticle=_turnToArticle;
@property(copy, nonatomic) CDUnknownBlockType turnToComment; // @synthesize turnToComment=_turnToComment;
@property(copy, nonatomic) CDUnknownBlockType turnToHome; // @synthesize turnToHome=_turnToHome;
@property(copy, nonatomic) CDUnknownBlockType turnToMatrix; // @synthesize turnToMatrix=_turnToMatrix;
@property(copy, nonatomic) CDUnknownBlockType turnToStandard; // @synthesize turnToStandard=_turnToStandard;
@property(copy, nonatomic) CDUnknownBlockType turnToUser; // @synthesize turnToUser=_turnToUser;
@property(nonatomic) __weak UIImageView *typeImageView; // @synthesize typeImageView=_typeImageView;
@property(copy, nonatomic) CDUnknownBlockType updateStatu; // @synthesize updateStatu=_updateStatu;
- (void)standardView;
- (void)ttlabelAddtarget:(id)arg1 withTarget:(id)arg2:(id)arg3 comment:(id)arg4 name:(id)arg5;
- (void)updateReadStatus;
- (void)userHomeViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

