//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@class NSString;

@interface NSDate (Objc)
+ (id)ssp_dateStringWithDelta:(double)arg1;
+ (id)ssp_sharedCalendar;
+ (id)ssp_sharedDateFormatter;
@property(readonly, nonatomic) NSString *ssp_dateDescription;
@property(readonly, nonatomic) NSString *ssp_privateLetterDescription;
@end

