//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (BTNISO8601)
+ (id)BTN_ISO8601DateFormatter;
+ (id)BTN_dateFromISO8601String:(id)arg1;
+ (void)BTN_setTimeZone:(id)arg1;
- (id)BTN_ISO8601String;
@end

