//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Regular)
- (id)firstMatchWithPattern:(id)arg1;
- (id)matchesWithPattern:(id)arg1;
- (struct _NSRange)ssp_firstRangeByReuglarWithPattern:(id)arg1;
- (id)ssp_firstStringByRegularWithPattern:(id)arg1;
- (id)ssp_matchesRangeByReularWithPattern:(id)arg1;
- (id)ssp_matchesStringByReularWithPattern:(id)arg1;
@end

