//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface OrderModel : NSObject
{
    NSString *_ID;
    NSString *_ordercode;
    NSString *_created_at;
    NSString *_status;
    NSString *_pay_at;
    NSString *_amount;
    NSString *_outofpocket;
    NSString *_name;
    NSString *_pay_type;
}

+ (id)modelCustomPropertyMapper;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *ID; // @synthesize ID=_ID;
@property(retain, nonatomic) NSString *amount; // @synthesize amount=_amount;
@property(retain, nonatomic) NSString *created_at; // @synthesize created_at=_created_at;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *ordercode; // @synthesize ordercode=_ordercode;
@property(retain, nonatomic) NSString *outofpocket; // @synthesize outofpocket=_outofpocket;
@property(retain, nonatomic) NSString *pay_at; // @synthesize pay_at=_pay_at;
@property(retain, nonatomic) NSString *pay_type; // @synthesize pay_type=_pay_type;
@property(retain, nonatomic) NSString *status; // @synthesize status=_status;

@end

