//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ContentTableView.h"

#import "UITableViewDataSource.h"

@class NSMutableArray, NSString, UIActivityIndicatorView, UILabel;

@interface PersonalArticleListViewController : ContentTableView <UITableViewDataSource>
{
    NSString *_ID;
    NSString *_name;
    UIActivityIndicatorView *_actiView;
    id <PersonalArticleListViewControllerDelegate> _pushDelegate;
    NSMutableArray *_dataArray;
    UILabel *_tipLabel;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
@property(nonatomic) __weak UIActivityIndicatorView *actiView; // @synthesize actiView=_actiView;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
- (void)didMoveToWindow;
- (void)downloadData;
- (id)init;
- (void)loadMoreData;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) __weak id <PersonalArticleListViewControllerDelegate> pushDelegate; // @synthesize pushDelegate=_pushDelegate;
@property(nonatomic) __weak UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

