//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ActivityListViewControllerDelegate.h"
#import "ArticleShareViewDelegate.h"
#import "LoginViewControllerDelegate.h"
#import "PersonalArticleListViewControllerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDelegate.h"

@class ActivityListViewController, AuthorModel, ContentScrollView, ContractProductViewController, NSArray, NSString, PersonalArticleListViewController, TitleBar, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UIView, UserModel;

@interface PersonalHomeViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, ActivityListViewControllerDelegate, PersonalArticleListViewControllerDelegate, ArticleShareViewDelegate, LoginViewControllerDelegate>
{
    UserModel *_user;
    AuthorModel *_author;
    ContentScrollView *_scrollView;
    ActivityListViewController *_table1;
    PersonalArticleListViewController *_table2;
    ContractProductViewController *_table3;
    UIView *_tableViewHeadView;
    UIView *_headBackView;
    TitleBar *_titleBarView;
    double _headViewHeight;
    UIImageView *_avatarImageView;
    UILabel *_nicknameLabel;
    UIImageView *_markImageView;
    UILabel *_bioLabel;
    UILabel *_city;
    UILabel *_wordCount;
    UILabel *_likedCount;
    UIButton *_weiboButton;
    UIButton *_weixinButotn;
    UIButton *_githubButton;
    UIButton *_twitterButton;
    NSArray *_articleArray;
    NSString *_ID;
    NSString *_weiboID;
    NSString *_githubID;
    NSString *_twitterID;
    UIActivityIndicatorView *_actiView;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void)accusationArticle:(id)arg1;
@property(nonatomic) __weak UIActivityIndicatorView *actiView; // @synthesize actiView=_actiView;
@property(retain, nonatomic) NSArray *articleArray; // @synthesize articleArray=_articleArray;
@property(retain, nonatomic) AuthorModel *author; // @synthesize author=_author;
@property(nonatomic) __weak UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
- (void)back:(id)arg1;
@property(nonatomic) __weak UILabel *bioLabel; // @synthesize bioLabel=_bioLabel;
@property(nonatomic) __weak UILabel *city; // @synthesize city=_city;
- (id)dealWithWordCount:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)favoriteArticle:(id)arg1;
@property(nonatomic) __weak UIButton *githubButton; // @synthesize githubButton=_githubButton;
@property(copy, nonatomic) NSString *githubID; // @synthesize githubID=_githubID;
@property(nonatomic) __weak UIView *headBackView; // @synthesize headBackView=_headBackView;
@property(nonatomic) double headViewHeight; // @synthesize headViewHeight=_headViewHeight;
- (id)initWithUser:(id)arg1;
@property(nonatomic) __weak UILabel *likedCount; // @synthesize likedCount=_likedCount;
@property(nonatomic) __weak UIImageView *markImageView; // @synthesize markImageView=_markImageView;
@property(nonatomic) __weak UILabel *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
- (void)pushActivityVC:(id)arg1;
- (void)pushRegistVierController:(id)arg1;
- (void)pushViewControllerWith:(id)arg1 author:(id)arg2 isAlert:(_Bool)arg3;
- (void)pushViewControllerWith:(id)arg1 user:(id)arg2 author:(id)arg3 commentID:(id)arg4;
@property(nonatomic) __weak ContentScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)sendMessageTo;
@property(nonatomic) __weak ActivityListViewController *table1; // @synthesize table1=_table1;
@property(nonatomic) __weak PersonalArticleListViewController *table2; // @synthesize table2=_table2;
@property(nonatomic) __weak ContractProductViewController *table3; // @synthesize table3=_table3;
@property(retain, nonatomic) UIView *tableViewHeadView; // @synthesize tableViewHeadView=_tableViewHeadView;
@property(nonatomic) __weak TitleBar *titleBarView; // @synthesize titleBarView=_titleBarView;
@property(nonatomic) __weak UIButton *twitterButton; // @synthesize twitterButton=_twitterButton;
@property(copy, nonatomic) NSString *twitterID; // @synthesize twitterID=_twitterID;
@property(retain, nonatomic) UserModel *user; // @synthesize user=_user;
@property(nonatomic) __weak UIButton *weiboButton; // @synthesize weiboButton=_weiboButton;
@property(copy, nonatomic) NSString *weiboID; // @synthesize weiboID=_weiboID;
@property(nonatomic) __weak UIButton *weixinButotn; // @synthesize weixinButotn=_weixinButotn;
@property(nonatomic) __weak UILabel *wordCount; // @synthesize wordCount=_wordCount;
- (void)setupContentView;
- (void)setupHeadView;
- (void)shareArticle:(id)arg1;
- (void)showAlertView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)turnToGithubProfile;
- (void)turnToTwitterProfile;
- (void)turnToWeiboProfile;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

