//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSOperationQueue, NSURL;

@interface PingppHttpClient : NSObject
{
    NSOperationQueue *_operationQueue;
    unsigned long long _requestContentType;
    double _timeoutInterval;
    NSURL *_baseURL;
    NSMutableDictionary *_mutableHTTPRequestHeaders;
}

+ (id)JSONStringForObject:(id)arg1;
+ (id)errorFromPingppResponse:(id)arg1;
+ (id)pingppUserAgentDetails;
+ (id)sharedClient;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *HTTPRequestHeaders;
- (void)POST:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
- (void)clearHTTPRequestHeaders;
- (void)createChargeWithData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;
- (id)initWithURLString:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *mutableHTTPRequestHeaders; // @synthesize mutableHTTPRequestHeaders=_mutableHTTPRequestHeaders;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(nonatomic) unsigned long long requestContentType; // @synthesize requestContentType=_requestContentType;
@property(nonatomic) double timeoutInterval; // @synthesize timeoutInterval=_timeoutInterval;
- (void)setValue:(id)arg1 forHTTPHeaderField:(id)arg2;
- (id)valueForHTTPHeaderField:(id)arg1;

@end

