//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PingppUtil : NSObject
{
}

+ (id)IDFAString;
+ (id)IDFVString;
+ (id)UUIDString;
+ (void)alertMessage:(id)arg1 vc:(id)arg2;
+ (void)alertMessage:(id)arg1 vc:(id)arg2 confirm:(CDUnknownBlockType)arg3 cancel:(CDUnknownBlockType)arg4;
+ (void)alertMessage:(id)arg1 vc:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (id)channelSet;
+ (void)debugLog:(id)arg1;
+ (id)getCurrentRootViewController;
+ (id)getParametersFromString:(id)arg1;
+ (id)getScreenShotWithViewController:(id)arg1;
+ (id)getURLScheme;
+ (_Bool)isAlipayAppInstalled;
+ (_Bool)isWxAppInstalled;
+ (id)jsonEncodedDataForDictionary:(id)arg1;
+ (id)jsonEncodedDataForObject:(id)arg1;
+ (id)jsonEncodedStringForObject:(id)arg1;
+ (id)md5Str:(id)arg1;
+ (_Bool)openURLString:(id)arg1;
+ (id)queryStringByDictionary:(id)arg1;
+ (id)queryStringByDictionary:(id)arg1 urlencode:(_Bool)arg2;
+ (id)queryStringByObject:(id)arg1 urlencode:(_Bool)arg2 parentKey:(id)arg3;
+ (id)scaleImage:(id)arg1 toSize:(struct CGSize)arg2;
+ (void)setDebugMode:(_Bool)arg1;
+ (id)stringByReplacingSnakeCaseWithCamelCase:(id)arg1;
+ (id)stringByURLEncoding:(id)arg1;

@end

