//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "LoginViewControllerDelegate.h"
#import "SFSafariViewControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class NSDictionary, NSLayoutConstraint, NSString, UIImageView, UILabel, UITextField;

@interface PlatformRegistViewController : UIViewController <UITextFieldDelegate, LoginViewControllerDelegate, SFSafariViewControllerDelegate>
{
    _Bool _turnToSafari;
    NSDictionary *_userInfo;
    UIImageView *_avatarImageView;
    UITextField *_emailTextField;
    UITextField *_nicknameTextField;
    UITextField *_passwordTextField;
    NSLayoutConstraint *_top;
    NSLayoutConstraint *_mid;
    NSLayoutConstraint *_bottom;
    UILabel *_tipLabel;
    UILabel *_userProtical;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) __weak NSLayoutConstraint *bottom; // @synthesize bottom=_bottom;
- (void)didReceiveMemoryWarning;
@property(nonatomic) __weak UITextField *emailTextField; // @synthesize emailTextField=_emailTextField;
- (void)loginAction:(id)arg1;
@property(nonatomic) __weak NSLayoutConstraint *mid; // @synthesize mid=_mid;
- (void)nextstepAction:(id)arg1;
@property(nonatomic) __weak UITextField *nicknameTextField; // @synthesize nicknameTextField=_nicknameTextField;
@property(nonatomic) __weak UITextField *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
- (void)pushRegistVierController:(id)arg1;
@property(nonatomic) __weak UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(nonatomic) __weak NSLayoutConstraint *top; // @synthesize top=_top;
@property(nonatomic) _Bool turnToSafari; // @synthesize turnToSafari=_turnToSafari;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) __weak UILabel *userProtical; // @synthesize userProtical=_userProtical;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)userProticolTap:(id)arg1;
- (_Bool)validateEmail:(id)arg1;
- (_Bool)validateNickname:(id)arg1;
- (_Bool)validatePassword:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

