//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

#import "UITableViewDataSource.h"

@class NSMutableArray, NSString, UIActivityIndicatorView, UILabel;

@interface PrivateLetterTableView : UITableView <UITableViewDataSource>
{
    _Bool _update;
    _Bool _haveTo;
    _Bool _isLoad;
    CDUnknownBlockType _haveToRead;
    NSMutableArray *_dataArray;
    UILabel *_label;
    UIActivityIndicatorView *_actiView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIActivityIndicatorView *actiView; // @synthesize actiView=_actiView;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
- (void)dealloc;
- (void)didMoveToWindow;
- (void)downloadData;
@property(nonatomic) _Bool haveTo; // @synthesize haveTo=_haveTo;
@property(copy, nonatomic) CDUnknownBlockType haveToRead; // @synthesize haveToRead=_haveToRead;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isLoad; // @synthesize isLoad=_isLoad;
@property(nonatomic) __weak UILabel *label; // @synthesize label=_label;
- (void)setContentOffset:(struct CGPoint)arg1;
@property(nonatomic) _Bool update; // @synthesize update=_update;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

