//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, PrivateLetterModel, UIImageView, UILabel;

@interface PrivateLetterTableViewCell : UITableViewCell
{
    _Bool _showBit;
    NSString *_name;
    PrivateLetterModel *_model;
    UIImageView *_iconImage;
    UIImageView *_bitImage;
    UILabel *_nameLabel;
    UIImageView *_markImage;
    UILabel *_timeLabel;
    UILabel *_descLabel;
    NSString *_mark;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *bitImage; // @synthesize bitImage=_bitImage;
- (id)dealCreated_at:(id)arg1;
@property(nonatomic) __weak UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(nonatomic) __weak UIImageView *iconImage; // @synthesize iconImage=_iconImage;
@property(copy, nonatomic) NSString *mark; // @synthesize mark=_mark;
@property(nonatomic) __weak UIImageView *markImage; // @synthesize markImage=_markImage;
@property(retain, nonatomic) PrivateLetterModel *model; // @synthesize model=_model;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) _Bool showBit; // @synthesize showBit=_showBit;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;

@end

