//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QNRecorderDelegate.h"

@class NSString;

@interface QNFileRecorder : NSObject <QNRecorderDelegate>
{
    _Bool _encode;
    NSString *_directory;
}

+ (id)fileRecorderWithFolder:(id)arg1 encodeKey:(_Bool)arg2 error:(id *)arg3;
+ (id)fileRecorderWithFolder:(id)arg1 error:(id *)arg2;
+ (id)pathJoin:(id)arg1 path:(id)arg2;
+ (void)removeKey:(id)arg1 directory:(id)arg2 encodeKey:(_Bool)arg3;
- (void).cxx_destruct;
- (id)del:(id)arg1;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *directory; // @synthesize directory=_directory;
@property _Bool encode; // @synthesize encode=_encode;
- (id)get:(id)arg1;
- (id)initWithFolder:(id)arg1 encodeKey:(_Bool)arg2;
- (id)pathOfKey:(id)arg1;
- (id)set:(id)arg1 data:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

