//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QNNetworkInfo : NSObject
{
    int _networkConnection;
    int _provider;
}

+ (id)getIp;
+ (_Bool)isNetworkChanged;
+ (id)noNet;
+ (id)normal;
- (id)init:(int)arg1 provider:(int)arg2;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToInfo:(id)arg1;
@property(readonly, nonatomic) int networkConnection; // @synthesize networkConnection=_networkConnection;
@property(readonly, nonatomic) int provider; // @synthesize provider=_provider;

@end

