//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSProgress, NSURLSessionUploadTask;

@interface QNProgessDelegate : NSObject
{
    CDUnknownBlockType _progressBlock;
    NSProgress *_progress;
    NSURLSessionUploadTask *_task;
    CDUnknownBlockType _cancelBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
- (id)initWithProgress:(CDUnknownBlockType)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(retain, nonatomic) NSURLSessionUploadTask *task; // @synthesize task=_task;
- (void)valueChange:(id)arg1;

@end

