//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface QNServiceAddress : NSObject
{
    NSString *_address;
    NSArray *_ips;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *address; // @synthesize address=_address;
- (id)init:(id)arg1 ips:(id)arg2;
@property(readonly, nonatomic) NSArray *ips; // @synthesize ips=_ips;

@end

