//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MJRefreshHeader.h"

@class UIActivityIndicatorView;

@interface RefreshHeader : MJRefreshHeader
{
    UIActivityIndicatorView *_indView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIActivityIndicatorView *indView; // @synthesize indView=_indView;
- (void)placeSubviews;
- (void)prepare;

@end

