//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "LoginViewControllerDelegate.h"
#import "SFSafariViewControllerDelegate.h"
#import "TTTAttributedLabelDelegate.h"
#import "UITextFieldDelegate.h"

@class NSString, TTTAttributedLabel, UIButton, UILabel, UITextField;

@interface RegistViewController : UIViewController <UITextFieldDelegate, LoginViewControllerDelegate, SFSafariViewControllerDelegate, TTTAttributedLabelDelegate>
{
    _Bool _turnToSafari;
    UITextField *_emailTextField;
    UITextField *_nicknameTextField;
    UITextField *_passwordTextfield;
    UILabel *_tipLabel;
    UILabel *_userProticol;
    UIButton *_onepasswordButton;
    TTTAttributedLabel *_ttLabel;
}

- (void).cxx_destruct;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)didReceiveMemoryWarning;
@property(nonatomic) __weak UITextField *emailTextField; // @synthesize emailTextField=_emailTextField;
- (void)loginUseAccount:(id)arg1;
- (void)netxstepButtonClick:(id)arg1;
@property(nonatomic) __weak UITextField *nicknameTextField; // @synthesize nicknameTextField=_nicknameTextField;
@property(nonatomic) __weak UIButton *onepasswordButton; // @synthesize onepasswordButton=_onepasswordButton;
- (void)passwordButtonCilck:(id)arg1;
@property(nonatomic) __weak UITextField *passwordTextfield; // @synthesize passwordTextfield=_passwordTextfield;
- (void)pushRegistVierController:(id)arg1;
@property(nonatomic) __weak UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(nonatomic) __weak TTTAttributedLabel *ttLabel; // @synthesize ttLabel=_ttLabel;
@property(nonatomic) _Bool turnToSafari; // @synthesize turnToSafari=_turnToSafari;
@property(nonatomic) __weak UILabel *userProticol; // @synthesize userProticol=_userProticol;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)userProticolTap:(id)arg1;
- (_Bool)validateEmail:(id)arg1;
- (_Bool)validateNickname:(id)arg1;
- (_Bool)validatePassword:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

