//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, UILabel, UITextField;

@interface RetrievalPasswordViewController : UIViewController
{
    NSString *_email;
    UILabel *_emailLabel;
    UITextField *_verifyCodeTextField;
    UITextField *_pwdTextField;
    UITextField *_repwdTextField;
}

- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(nonatomic) __weak UILabel *emailLabel; // @synthesize emailLabel=_emailLabel;
@property(nonatomic) __weak UITextField *pwdTextField; // @synthesize pwdTextField=_pwdTextField;
@property(nonatomic) __weak UITextField *repwdTextField; // @synthesize repwdTextField=_repwdTextField;
@property(nonatomic) __weak UITextField *verifyCodeTextField; // @synthesize verifyCodeTextField=_verifyCodeTextField;
- (void)sureAction:(id)arg1;
- (_Bool)validatePassword:(id)arg1;
- (void)viewDidLoad;

@end

