//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSString, SearchResultTableViewController;

@interface SearchResultCell : UICollectionViewCell
{
    long long _type;
    NSString *_keyWord;
    SearchResultTableViewController *_tabVC;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(copy, nonatomic) NSString *keyWord; // @synthesize keyWord=_keyWord;
@property(retain, nonatomic) SearchResultTableViewController *tabVC; // @synthesize tabVC=_tabVC;
@property(nonatomic) long long type; // @synthesize type=_type;

@end

