//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, PrivateLetterFrameModel, UIButton, UIImageView, UILabel;

@interface SessionTableViewCell : UITableViewCell
{
    PrivateLetterFrameModel *_msgF;
    NSString *_avatar;
    UILabel *_lblTime;
    UIImageView *_iconView;
    UIButton *_btnText;
}

+ (id)msgCellWithTableView:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
- (void)awakeFromNib;
@property(nonatomic) __weak UIButton *btnText; // @synthesize btnText=_btnText;
- (id)dealCreated_at:(id)arg1;
@property(nonatomic) __weak UIImageView *iconView; // @synthesize iconView=_iconView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) __weak UILabel *lblTime; // @synthesize lblTime=_lblTime;
@property(retain, nonatomic) PrivateLetterFrameModel *msgF; // @synthesize msgF=_msgF;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSubViewData;
- (void)setSubViewFrame;

@end

