//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "LoginViewControllerDelegate.h"

@class NSString, UILabel, UISwitch, UserModel;

@interface SettingsTableViewController : UITableViewController <LoginViewControllerDelegate>
{
    _Bool _isLogin;
    UILabel *_totalSize;
    UISwitch *_emailSwitch;
    UISwitch *_messageSwitch;
    UserModel *_user;
}

- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
@property(nonatomic) __weak UISwitch *emailSwitch; // @synthesize emailSwitch=_emailSwitch;
@property(nonatomic) _Bool isLogin; // @synthesize isLogin=_isLogin;
- (void)mailNotificationSwitchChange:(id)arg1;
- (void)messageOnValueChange:(id)arg1;
@property(nonatomic) __weak UISwitch *messageSwitch; // @synthesize messageSwitch=_messageSwitch;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)pushLoginViewController;
- (void)pushRegistVierController:(id)arg1;
@property(nonatomic) __weak UILabel *totalSize; // @synthesize totalSize=_totalSize;
@property(retain, nonatomic) UserModel *user; // @synthesize user=_user;
- (id)sizeStrWith:(unsigned long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

