//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSDKLog.h"

@class NSString;

@interface SSDKApiLog : SSDKLog
{
    unsigned long long _platformType;
    NSString *_api;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *api; // @synthesize api=_api;
- (void)getLogContent:(CDUnknownBlockType)arg1;
- (id)initWithPlatform:(unsigned long long)arg1 api:(id)arg2;
@property(nonatomic) unsigned long long platformType; // @synthesize platformType=_platformType;

@end

