//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UILabel;

@interface SSpaiHUD : UIView
{
    UILabel *_label;
    UIActivityIndicatorView *_actiView;
}

+ (id)activityIndicator;
+ (id)defaultSSpaiHUD;
+ (void)dismiss;
+ (void)dismissActivityIndicator;
+ (id)shareSSpaiHUD;
+ (void)showActivityIndicator;
+ (void)showWithStatus:(id)arg1;
+ (void)showWithStatusNotDismiss:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) __weak UIActivityIndicatorView *actiView; // @synthesize actiView=_actiView;
@property(nonatomic) __weak UILabel *label; // @synthesize label=_label;
- (void)setShadowColor:(id)arg1 shadowOffset:(struct CGSize)arg2 shadowOpacity:(double)arg3 shadowRadius:(double)arg4;
- (void)setText:(id)arg1;
- (void)setTextColor:(id)arg1;

@end

