//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UINavigationController;

@interface SspFullScreenPopGestureRecognizerDelegate : NSObject <UIGestureRecognizerDelegate>
{
    UINavigationController *_navigationController;
}

- (void).cxx_destruct;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
@property(nonatomic) __weak UINavigationController *navigationController; // @synthesize navigationController=_navigationController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

