//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SSPGooglePlusShareNaviViewController, SSPGooglePlusShareViewController, UIWindow;

@interface SSPGooglePlusShareController : NSObject
{
    NSString *_text;
    NSString *_url;
    CDUnknownBlockType _resultHandler;
    UIWindow *_window;
    UIWindow *_lastWindow;
    SSPGooglePlusShareViewController *_shareViewController;
    SSPGooglePlusShareNaviViewController *_shareNavi;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithText:(id)arg1 url:(id)arg2;
@property(retain, nonatomic) UIWindow *lastWindow; // @synthesize lastWindow=_lastWindow;
- (void)onResult:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) CDUnknownBlockType resultHandler; // @synthesize resultHandler=_resultHandler;
@property(retain, nonatomic) SSPGooglePlusShareNaviViewController *shareNavi; // @synthesize shareNavi=_shareNavi;
@property(retain, nonatomic) SSPGooglePlusShareViewController *shareViewController; // @synthesize shareViewController=_shareViewController;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)share;

@end

