//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMOBFPlugin.h"

@class NSMutableSet, NSString;

@interface SSPRenrenProxy : NSObject <IMOBFPlugin>
{
    NSMutableSet *_authCallbackSet;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableSet *authCallbackSet; // @synthesize authCallbackSet=_authCallbackSet;
- (_Bool)authorize:(id)arg1;
- (_Bool)handleOpenURL:(id)arg1;
- (id)init;
- (void)load:(id)arg1;
- (void)registerAuthMethod;
- (void)registerHandleSSOCallbackMethod;
- (void)registerSetupApp;
- (void)rennLoginCancelded;
- (void)rennLoginDidFailWithError:(id)arg1;
- (void)rennLoginSuccess;
- (void)setupAppId:(id)arg1 appKey:(id)arg2 secretKey:(id)arg3;
- (void)unload;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

