//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIPopoverControllerDelegate.h"

@class NSString, SSUIPageView;

@interface SSUIiPadShareActionSheetViewController : UIViewController <UIPopoverControllerDelegate>
{
    CDUnknownBlockType _clickHandle;
    CDUnknownBlockType _cancelHandle;
    long long _itemsCount;
    SSUIPageView *_pageView;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType cancelHandle; // @synthesize cancelHandle=_cancelHandle;
@property(copy, nonatomic) CDUnknownBlockType clickHandle; // @synthesize clickHandle=_clickHandle;
- (id)initWithItems:(id)arg1;
@property(nonatomic) long long itemsCount; // @synthesize itemsCount=_itemsCount;
@property(retain, nonatomic) SSUIPageView *pageView; // @synthesize pageView=_pageView;
- (long long)preferredStatusBarStyle;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)showInView:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

