//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSUIBaseShareContentEditor.h"

@class SSUIiPhoneEditorWindow;

@interface SSUIiPhoneShareContentEditor : SSUIBaseShareContentEditor
{
    SSUIiPhoneShareContentEditor *_selfRef;
    SSUIiPhoneEditorWindow *_shareContentWindow;
}

- (void).cxx_destruct;
- (void)dismiss;
@property(retain, nonatomic) SSUIiPhoneShareContentEditor *selfRef; // @synthesize selfRef=_selfRef;
@property(retain, nonatomic) SSUIiPhoneEditorWindow *shareContentWindow; // @synthesize shareContentWindow=_shareContentWindow;
- (void)show;

@end

