//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@interface SSUIiPadEditorWindow : UIWindow
{
    UIWindow *_lastUserWindow;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType cancelHandler;
- (void)dismiss;
- (id)init;
@property(copy, nonatomic) CDUnknownBlockType submitHandler;
- (void)showWithContent:(id)arg1 image:(id)arg2 platformTypes:(id)arg3;

@end

