//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, UIImage;

@interface TopicModel : NSObject
{
    _Bool _favorited;
    UIImage *_image;
    NSString *_title;
    NSString *_intro;
    NSString *_banner;
    NSString *_custom_url;
    NSString *_ID;
    NSString *_created_at;
    NSString *_articles_count;
    NSString *_favorites_count;
    NSString *_views_count;
    NSString *_released_at;
    NSArray *_application;
    NSArray *_tags;
}

+ (void)loadModelWithParameters:(id)arg1 Finished:(CDUnknownBlockType)arg2;
+ (void)loadNewModelWithParameters:(id)arg1 Finished:(CDUnknownBlockType)arg2;
+ (id)modelContainerPropertyGenericClass;
+ (id)modelCustomPropertyMapper;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
@property(retain, nonatomic) NSArray *application; // @synthesize application=_application;
@property(copy, nonatomic) NSString *articles_count; // @synthesize articles_count=_articles_count;
@property(copy, nonatomic) NSString *banner; // @synthesize banner=_banner;
@property(copy, nonatomic) NSString *created_at; // @synthesize created_at=_created_at;
@property(copy, nonatomic) NSString *custom_url; // @synthesize custom_url=_custom_url;
@property(nonatomic) _Bool favorited; // @synthesize favorited=_favorited;
@property(copy, nonatomic) NSString *favorites_count; // @synthesize favorites_count=_favorites_count;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *intro; // @synthesize intro=_intro;
@property(copy, nonatomic) NSString *released_at; // @synthesize released_at=_released_at;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *views_count; // @synthesize views_count=_views_count;

@end

