//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, TopicModel, UIImage, UIImageView, UILabel;

@interface TopicHeaderView : UIView
{
    TopicModel *_topic;
    CDUnknownBlockType _showAlert;
    id <TopicHeaderViewDelegate> _delegate;
    UIImage *_image;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    NSArray *_dataArray;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(retain, nonatomic) NSArray *dataArray; // @synthesize dataArray=_dataArray;
@property(nonatomic) __weak id <TopicHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) CDUnknownBlockType showAlert; // @synthesize showAlert=_showAlert;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) TopicModel *topic; // @synthesize topic=_topic;

@end

