//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class AppModel, UIButton, UIImageView, UILabel;

@interface TopicHeaderCell : UICollectionViewCell
{
    AppModel *_model;
    UIImageView *_appIconImage;
    UILabel *_nameLabel;
    UILabel *_platformLabel;
    UIButton *_downLoadButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIImageView *appIconImage; // @synthesize appIconImage=_appIconImage;
- (void)awakeFromNib;
@property(nonatomic) __weak UIButton *downLoadButton; // @synthesize downLoadButton=_downLoadButton;
- (void)downLoadButtonAction:(id)arg1;
@property(retain, nonatomic) AppModel *model; // @synthesize model=_model;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UILabel *platformLabel; // @synthesize platformLabel=_platformLabel;

@end

