//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@interface UIApplication (ButtonSDK)
+ (_Bool)BTN_isAssociatedDomainReportingEnabled;
+ (void)BTN_setAssociatedDomainReportingEnabled:(_Bool)arg1;
- (id)BTN_URLSchemes;
- (id)BTN_URLSchemesInBundle:(id)arg1;
- (id)BTN_associatedDomains;
- (id)BTN_associatedDomainsFromString:(id)arg1;
- (long long)BTN_buildType;
- (long long)BTN_buildTypeFromEmbeddedMobileProvisionString:(id)arg1;
- (id)BTN_buildTypeString;
- (id)BTN_buildTypeStringForBuildType:(long long)arg1;
- (id)BTN_bundleSeedIdentifier;
- (id)BTN_bundleSeedIdentifierForKeychainAttributes:(id)arg1;
- (void)BTN_clearCachedBuildType;
- (void)BTN_clearCachedQueryableSchemes;
- (void)BTN_clearCachedURLSchemes;
- (long long)BTN_computedStatusBarStyle;
- (_Bool)BTN_isDevelopmentBuild;
- (_Bool)BTN_isNewInstall;
- (_Bool)BTN_isNewInstallAsDeterminedByFileAttributes:(id)arg1;
- (_Bool)BTN_isSandboxBuild;
- (_Bool)BTN_isSandboxBuildCheckingBundle:(id)arg1;
- (_Bool)BTN_isSimulatorBuild;
- (id)BTN_keychainEntryAttributes;
- (_Bool)BTN_queriesScheme:(id)arg1;
- (id)BTN_queryableSchemes;
- (id)BTN_queryableSchemesInBundle:(id)arg1;
- (void)BTN_setBuildType:(long long)arg1;
- (void)BTN_setQueryableSchemes:(id)arg1;
@end

