//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (ButtonSDK)
- (_Bool)BTN_isSimulator;
- (_Bool)BTN_localNotificationsEnabled;
- (_Bool)BTN_locationPermissionGranted;
- (_Bool)BTN_locationPermissionRequested;
- (id)BTN_permissionsRepresentation;
- (id)BTN_platform;
- (_Bool)BTN_remoteNotificationsEnabled;
@end

