//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class BTNImageRequestCoordinator, NSURL;

@interface UIImageView (BTNImageLoading)
@property(retain, nonatomic) BTNImageRequestCoordinator *BTN_imageLoader;
- (void)BTN_setImageWithURL:(id)arg1;
- (void)BTN_setImageWithURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) NSURL *BTN_url;
@end

