//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Objc)
+ (id)ssp_imageWithColor:(id)arg1 size:(struct CGSize)arg2;
+ (id)ssp_singleDotImageWithColor:(id)arg1;
- (void)ssp_asyncCreatCircleImageWithSize:(struct CGSize)arg1 color:(id)arg2 callBack:(CDUnknownBlockType)arg3;
- (id)ssp_changeImageWithSize:(struct CGSize)arg1 color:(id)arg2;
- (id)ssp_creatCircleImageWithSize:(struct CGSize)arg1 color:(id)arg2;
@end

