//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@class UIPanGestureRecognizer;

@interface UINavigationController (Objc)
+ (void)load;
- (id)ssp_fullScreenPopGestureRecognizerDelegate;
@property(readonly, nonatomic) UIPanGestureRecognizer *ssp_popGestureRecognizer;
- (void)ssp_pushViewController:(id)arg1 animated:(_Bool)arg2;
@end

