//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIView;

@interface UITableViewCell (HYBMasonryAutoCellHeight)
+ (double)hyb_heightForTableView:(id)arg1 config:(CDUnknownBlockType)arg2;
+ (double)hyb_heightForTableView:(id)arg1 config:(CDUnknownBlockType)arg2 cache:(CDUnknownBlockType)arg3;
@property(nonatomic) double hyb_bottomOffsetToCell;
@property(retain, nonatomic) UIView *hyb_lastViewInCell;
- (double)private_hyb_heightForTableView:(id)arg1;
@end

