//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (WBTSizes)
- (void)setWbsdkBottom:(double)arg1;
- (void)setWbsdkCenterX:(double)arg1;
- (void)setWbsdkCenterY:(double)arg1;
- (void)setWbsdkHeight:(double)arg1;
- (void)setWbsdkLeft:(double)arg1;
- (void)setWbsdkOrigin:(struct CGPoint)arg1;
- (void)setWbsdkRight:(double)arg1;
- (void)setWbsdkSize:(struct CGSize)arg1;
- (void)setWbsdkTop:(double)arg1;
- (void)setWbsdkWidth:(double)arg1;
- (double)wbsdkBottom;
- (double)wbsdkCenterX;
- (double)wbsdkCenterY;
- (double)wbsdkHeight;
- (double)wbsdkLeft;
- (struct CGPoint)wbsdkOrigin;
- (double)wbsdkRight;
- (struct CGRect)wbsdkScreenFrame;
- (double)wbsdkScreenViewX;
- (double)wbsdkScreenViewY;
- (struct CGSize)wbsdkSize;
- (double)wbsdkTTScreenX;
- (double)wbsdkTTScreenY;
- (double)wbsdkTop;
- (double)wbsdkWidth;
- (id)wbsdk_ancestorOrSelfWithClass:(Class)arg1;
- (struct CGRect)wbsdk_convertFrameToWindow:(id)arg1;
- (id)wbsdk_descendantOrSelfWithClass:(Class)arg1;
- (struct CGRect)wbsdk_expandedFrame:(struct CGRect)arg1 withHorizontalOffset:(double)arg2;
- (struct CGRect)wbsdk_expandedFrame:(struct CGRect)arg1 withOffset:(double)arg2;
- (struct CGRect)wbsdk_expandedFrame:(struct CGRect)arg1 withVerticalOffset:(double)arg2;
- (id)wbsdk_imageFromView;
- (id)wbsdk_imageFromViewInRect:(struct CGRect)arg1;
- (id)wbsdk_imageFromViewWithLowResolution;
- (id)wbsdk_imageFromViewWithLowResolutionInRect:(struct CGRect)arg1;
- (struct CGPoint)wbsdk_offsetFromView:(id)arg1;
- (void)wbsdk_removeAllSubviews;
- (id)wbsdk_viewController;
- (id)wbsdk_viewForAnimation;
@end

