//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class NSArray, UIViewController;

@interface UIWindow (Growing)
- (id)GROW_timestamp;
- (_Bool)_growingHook_isVisiableVC:(id)arg1;
- (void)growingHook_addVisiableController:(id)arg1;
@property(readonly, nonatomic) UIViewController *growingHook_curViewController;
@property(readonly, nonatomic) NSArray *growingHook_curViewControllers;
- (id)growingHook_curViewControllersVar;
- (id)growingHook_didAppearVCShells;
- (void)growingHook_removeVisiableController:(id)arg1;
- (void)growingHook_setNeedUpdateCurViewControllers;
- (id)growingHook_setNeedUpdateVisiableVC;
- (id)growingHook_setRootViewController;
- (void)growingHook_updateVisiableVC;
- (void)setGrowingHook_curViewControllersVar:(id)arg1;
- (void)setGrowingHook_setNeedUpdateVisiableVC:(id)arg1;
- (void)setGrowingHook_setRootViewController:(id)arg1;
@end

