//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, UMTIdTracking;

@interface UMPayloadBuild : NSObject
{
    UMTIdTracking *_idTracking;
    NSMutableDictionary *_jsonObject;
    NSMutableDictionary *_body;
    NSMutableDictionary *_ekvs;
    NSMutableDictionary *_gkvs;
}

+ (id)generateImprintChecksum:(id)arg1;
+ (id)imprintPropertyValueWithKey:(id)arg1;
+ (id)sharedInstance;
+ (void)updateImprint:(id)arg1;
+ (_Bool)validateImprintChecksum:(id)arg1;
- (void).cxx_destruct;
- (void)addEvent:(id)arg1;
- (void)buildBodySeg;
- (void)buildCCEvents;
- (void)buildErrors;
- (void)buildEvents;
- (void)buildHeaderSeg;
- (void)buildIdTracking;
- (void)buildSessions;
- (void)generateIdTracking;
- (id)init;
- (id)payloadData;
- (void)saveIdTracking;
- (_Bool)verifyResponseData:(id)arg1;

@end

