//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "UMTBase.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface UMTIdTracking : NSObject <UMTBase, NSCoding>
{
    NSMutableDictionary *__snapshots;
    NSMutableArray *__journals;
    NSString *__checksum;
    _Bool __snapshots_isset;
    _Bool __journals_isset;
    _Bool __checksum_isset;
}

@property(retain, nonatomic, getter=checksum, setter=setChecksum:) NSString *checksum;
- (_Bool)checksumIsSet;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithSnapshots:(id)arg1 journals:(id)arg2 checksum:(id)arg3;
@property(retain, nonatomic, getter=journals, setter=setJournals:) NSMutableArray *journals;
- (_Bool)journalsIsSet;
- (void)read:(id)arg1;
@property(retain, nonatomic, getter=snapshots, setter=setSnapshots:) NSMutableDictionary *snapshots;
- (_Bool)snapshotsIsSet;
- (void)unsetChecksum;
- (void)unsetJournals;
- (void)unsetSnapshots;
- (void)validate;
- (void)write:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

