//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "UMTBase.h"

@class NSString;

@interface UMTIdSnapshot : NSObject <UMTBase, NSCoding>
{
    NSString *__identity;
    long long __ts;
    int __version;
    _Bool __identity_isset;
    _Bool __ts_isset;
    _Bool __version_isset;
}

- (void)dealloc;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic, getter=identity, setter=setIdentity:) NSString *identity;
- (_Bool)identityIsSet;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithIdentity:(id)arg1 ts:(long long)arg2 version:(int)arg3;
- (void)read:(id)arg1;
@property(nonatomic, getter=ts, setter=setTs:) long long ts;
@property(nonatomic, getter=version, setter=setVersion:) int version;
- (_Bool)tsIsSet;
- (void)unsetIdentity;
- (void)unsetTs;
- (void)unsetVersion;
- (void)validate;
- (_Bool)versionIsSet;
- (void)write:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

