//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextFieldDelegate.h"
#import "UPKeyboardDelegate.h"

@class NSString, UPKeyboard, UPLableCell, UPLineView, UPTextField;

@interface UPBaseCell : UIView <UPKeyboardDelegate, UITextFieldDelegate>
{
    UPTextField *mTextField;
    UPKeyboard *mKeyboard;
    long long mMaxLen;
    UIView *mBGView;
    UPLableCell *mLabelCell;
    UPLableCell *mTipCell;
    NSString *mName;
    NSString *mPlaceHolder;
    _Bool _needDeviceEncryption;
    _Bool _readOnly;
    UPLineView *_topLine;
    UPLineView *_bottomLine;
    id <UITextFieldDelegate><UPTextFieldDelegate> mDelegate;
    NSString *mRegexP;
}

- (void).cxx_destruct;
- (void)addBGViewAtY:(double)arg1;
- (void)dealloc;
- (void)deleteClick;
- (void)doneClick;
- (id)initWithFrame:(struct CGRect)arg1 content:(id)arg2 delegate:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1 content:(id)arg2 delegate:(id)arg3 lineFlag:(_Bool)arg4;
- (id)initWithFrame:(struct CGRect)arg1 content:(id)arg2 delegate:(id)arg3 lineFlag:(_Bool)arg4 leftTitle:(id)arg5;
- (_Bool)isEmpty;
- (_Bool)isLegalLength;
- (_Bool)isReadOnly;
- (id)keyboard;
@property(nonatomic) __weak id <UITextFieldDelegate><UPTextFieldDelegate> mDelegate; // @synthesize mDelegate;
@property(retain, nonatomic) NSString *mName; // @synthesize mName;
@property(retain, nonatomic) NSString *mPlaceHolder; // @synthesize mPlaceHolder;
@property(retain, nonatomic) NSString *mRegexP; // @synthesize mRegexP;
- (long long)maxLength;
- (id)param;
- (id)paramWithString:(id)arg1;
- (void)setLabelColor:(id)arg1;
- (void)setLabelFont:(id)arg1;
- (void)setLabelText:(id)arg1;
- (void)setLeftTitle:(id)arg1;
- (void)setNeedsDeviceEncryption;
- (void)setText:(id)arg1;
- (void)setTextFieldDelegate:(id)arg1;
- (void)shouldReadOnly:(_Bool)arg1;
- (id)text;
- (void)textChanged:(id)arg1;
- (id)textField;
- (id)value;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

