//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDictionary, UIButton, UPLabel;

@interface UPCheckBoxView : UIView
{
    _Bool _editable;
    UIButton *mCheckBox;
    UPLabel *mLabel;
    long long mXOffSet;
    double _boxHeight;
    _Bool mSelected;
    id boxDelegate;
    NSDictionary *_boxContent;
}

- (void).cxx_destruct;
- (void)addCheckBox;
- (void)addFunctionLabel:(id)arg1;
- (void)addLabel;
@property(retain, nonatomic) NSDictionary *boxContent; // @synthesize boxContent=_boxContent;
@property(nonatomic) __weak id boxDelegate; // @synthesize boxDelegate;
- (void)checkBoxHref;
- (id)checkBoxParams;
- (void)checkboxClick:(id)arg1;
- (void)dealloc;
- (id)errorInfo;
- (id)initWithFrame:(struct CGRect)arg1 content:(id)arg2 delegate:(id)arg3;
@property(nonatomic) _Bool mSelected; // @synthesize mSelected;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end

