//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPBaseViewController.h"

#import "UPCheckBoxDelegate.h"
#import "UPPullListViewDelegate.h"

@class NSDictionary, NSString, UPCheckBoxView;

@interface UPEntrustViewController : UPBaseViewController <UPPullListViewDelegate, UPCheckBoxDelegate>
{
    _Bool _canGetFollowRules;
    UPCheckBoxView *_licenseBox;
    NSDictionary *_entrustActionButton;
}

- (void).cxx_destruct;
- (double)addEntrustElements:(double)arg1;
- (void)addNavigationBar;
- (void)addSubViews;
- (void)buttonCancelClicked;
- (void)buttonOKClicked;
- (void)checkBox:(id)arg1;
- (void)comunicateToUPMPDidFailWithErrorType:(long long)arg1 error:(id)arg2;
- (void)comunicateToUPMPDidSucceedWithEvent:(long long)arg1;
- (void)dealloc;
- (void)initActions;
- (void)nextAction:(id)arg1;
- (void)pullListAnimationDidStart:(double)arg1;
- (void)pushViewControllerToPayingViewController;
- (void)releaseActions;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

