//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData, NSTimer, NSURLConnection, UPServiceURL;

@interface UPHttpsConnect : NSObject
{
    NSMutableData *mRecvData;
    NSURLConnection *mURLConnection;
    NSTimer *mTimeOut;
    _Bool mFinished;
    long long _serviceType;
    UPServiceURL *_serviceURL;
    id <UPHttpsConnectDelegate> delegate;
}

+ (void)releaseInstance;
+ (id)shareInstance;
- (void).cxx_destruct;
- (void)cancelConnection;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <UPHttpsConnectDelegate> delegate; // @synthesize delegate;
- (void)handleTimeOut:(id)arg1;
- (id)init;
- (void)postMessage:(id)arg1;
- (void)stopConnection;
- (void)stopTimer;

@end

