//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPJsonBase.h"

#import "UPJsonParser.h"
#import "UPJsonWriter.h"

@class UPJsonParser, UPJsonWriter;

@interface UPJson : UPJsonBase <UPJsonParser, UPJsonWriter>
{
    UPJsonParser *jsonParser;
    UPJsonWriter *jsonWriter;
}

- (void)dealloc;
- (id)fragmentWithString:(id)arg1 error:(id *)arg2;
@property _Bool humanReadable;
- (id)init;
- (unsigned long long)maxDepth;
- (id)objectWithString:(id)arg1;
- (id)objectWithString:(id)arg1 allowScalar:(_Bool)arg2 error:(id *)arg3;
- (id)objectWithString:(id)arg1 error:(id *)arg2;
- (void)setMaxDepth:(unsigned long long)arg1;
@property _Bool sortKeys;
- (id)stringWithFragment:(id)arg1 error:(id *)arg2;
- (id)stringWithObject:(id)arg1;
- (id)stringWithObject:(id)arg1 allowScalar:(_Bool)arg2 error:(id *)arg3;
- (id)stringWithObject:(id)arg1 error:(id *)arg2;

@end

