//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPBaseViewController.h"

#import "UPListViewDelegate.h"
#import "UPPayChannelViewDataSource.h"
#import "UPPayChannelViewDelegate.h"
#import "UPPullListViewDelegate.h"

@class NSArray, NSMutableArray, NSString, UIView, UPDefaultCardView, UPLableCell, UPListView, UPNewBankCardCell, UPPayChannelView;

@interface UPOrderInfoViewController : UPBaseViewController <UPPullListViewDelegate, UPPayChannelViewDelegate, UPPayChannelViewDataSource, UPListViewDelegate>
{
    _Bool mExitPlugin;
    _Bool mNewCard;
    long long _shouldDeletedCardId;
    double _subviewOriginY;
    double _scrollViewHeight;
    double mPointY;
    UIView *mSubView;
    UPPayChannelView *mPayChannelView;
    UPLableCell *mPayType;
    UPNewBankCardCell *mBankCell;
    UPDefaultCardView *_defaultCardView;
    UPListView *_listView;
    _Bool _onlySupportCardMedium;
    _Bool _supportAccountPayMode;
    long long _commCardIndex;
    NSMutableArray *_payChannels;
    long long _isRootViewController;
    NSArray *_loginRules;
    NSMutableArray *_bindCardDescriptions;
    long long payMode;
}

- (void).cxx_destruct;
- (double)addCommCardView:(struct CGRect)arg1 onView:(id)arg2;
- (void)addNavigationBar;
- (void)addOnlySupportCardMediumView;
- (void)addSubViews;
- (void)addSubViewsWithAccount;
- (void)addSubViewsWithCommCards;
- (void)addSubViewsWithMerchantCard;
- (void)addSubViewsWithNewCard;
- (void)buttonCancelClicked;
- (void)buttonOKClicked;
- (void)cancelAction:(id)arg1;
- (id)checkUserInfoError;
- (void)comunicateToUPMPDidFailWithErrorType:(long long)arg1 error:(id)arg2;
- (void)comunicateToUPMPDidSucceedWithEvent:(long long)arg1;
- (void)dealloc;
- (void)deleteCommCard:(id)arg1;
- (void)didChoosedChannelAtIndex:(long long)arg1;
- (_Bool)didHasMerchantPan:(id)arg1;
- (void)didPayChannelViewFinishedLayout:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithType:(long long)arg1 isRoot:(_Bool)arg2;
- (void)listView:(id)arg1 DidSelectedAtIndex:(long long)arg2;
- (void)listViewDidDeletedAtIndex:(long long)arg1;
- (void)makeDatas;
- (void)nextAction:(id)arg1;
- (long long)numberOfSectionsInPayChannelView;
@property(nonatomic) long long payMode; // @synthesize payMode;
- (void)pullListAnimationDidStart:(double)arg1;
- (void)pushViewControllerToEntrustViewController;
- (void)pushViewControllerToPayingViewController;
- (void)pushViewToAccountPay;
- (void)pushViewToDirectPay;
- (void)pushViewToInputViewController;
- (void)pushViewToUserInfoViewController;
- (void)refreshCommCard;
- (void)removeSubViews;
- (void)shouldDismissCommCardList;
- (void)showBindCardsList;
- (void)showFindPwd;
- (void)showReg;
- (void)showSupportedBank;
- (id)titleOfSectionsAtIndex:(long long)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

