//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDictionary, UPLableCell;

@interface UPOrderItemCell : UIView
{
    UPLableCell *_keyLabel;
    UPLableCell *_valueLabel;
    NSDictionary *orderContent;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 content:(id)arg2;
@property(retain, nonatomic) NSDictionary *orderContent; // @synthesize orderContent;
- (void)resetFrame;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

@end

