//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, UIButton, UILabel, UPLableCell;

@interface UPPayChannelView : UIView
{
    double _viewHeight;
    UPLableCell *_title;
    UIButton *_newCardChannel;
    UIButton *_accountChannel;
    UIButton *_viPosChannel;
    NSMutableArray *_imageArray;
    id <UPPayChannelViewDelegate> _delegate;
    id <UPPayChannelViewDataSource> _dataSource;
    UILabel *_label;
}

- (void).cxx_destruct;
- (double)addChannels:(double)arg1;
- (double)addLabel:(double)arg1;
@property(nonatomic) id <UPPayChannelViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)dealloc;
@property(nonatomic) __weak id <UPPayChannelViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (void)layoutSubviews;
- (void)reloadPayChannels;
- (void)removeTitleFromSuperView;
- (void)selectedAction:(id)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

@end

