//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPBaseCell.h"

@class NSMutableString, UPTextField;

@interface UPPasswordCell : UPBaseCell
{
    NSMutableString *_securityPin;
    UPTextField *pTextField;
}

- (void).cxx_destruct;
- (void)deleteClick;
- (id)initWithFrame:(struct CGRect)arg1 content:(id)arg2 delegate:(id)arg3;
- (_Bool)isLegalLength;
- (id)param;
- (void)textChanged:(id)arg1;

@end

