//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPBaseViewController.h"

#import "UPPromotionTabBarViewDelegate.h"

@class NSDictionary, NSString, UIButton, UITapGestureRecognizer, UIView, UPPromotionContentView, UPPromotionTabBarViewController;

@interface UPPromotionPannelViewController : UPBaseViewController <UPPromotionTabBarViewDelegate>
{
    UIButton *closeButton;
    UIView *maskView;
    UITapGestureRecognizer *maskGesture;
    UIView *pannelView;
    NSDictionary *myContentDic;
    _Bool firstGetPoints;
    _Bool firstOpenPannel;
    float pannelHeight;
    int scoreRequestCount;
    UPPromotionTabBarViewController *_myTabBar;
    UPPromotionContentView *_myContentView;
    id <UPPromotionPannelViewDelegate> _myController;
    NSString *_uuid;
}

- (void).cxx_destruct;
- (void)closeAction;
- (void)comunicateToUPMPDidFailWithErrorType:(long long)arg1 error:(id)arg2;
- (void)comunicateToUPMPDidSucceedWithEvent:(long long)arg1 data:(id)arg2;
- (void)couponFormatErr:(id)arg1;
- (void)couponViewVerify:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)getCoupon:(id)arg1 andElement:(id)arg2;
- (void)getScore:(id)arg1 andUUID:(id)arg2;
- (id)initWithContent:(id)arg1;
@property(retain, nonatomic) UPPromotionContentView *myContentView; // @synthesize myContentView=_myContentView;
@property(nonatomic) __weak id <UPPromotionPannelViewDelegate> myController; // @synthesize myController=_myController;
@property(retain, nonatomic) UPPromotionTabBarViewController *myTabBar; // @synthesize myTabBar=_myTabBar;
- (void)panelViewSelectCoupon:(id)arg1;
- (void)promotionTabBarSelect:(unsigned long long)arg1;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void)showPannel;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

