//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UPPReachability : NSObject
{
    _Bool _reachableOnWWAN;
    CDUnknownBlockType _reachableBlock;
    CDUnknownBlockType _unreachableBlock;
    struct __SCNetworkReachability *_reachabilityRef;
    struct dispatch_queue_s *_reachabilitySerialQueue;
    id _reachabilityObject;
}

+ (id)reachabilityForInternetConnection;
+ (id)reachabilityForLocalWiFi;
+ (id)reachabilityWithAddress:(const struct sockaddr_in *)arg1;
+ (id)reachabilityWithHostname:(id)arg1;
- (void).cxx_destruct;
- (_Bool)connectionRequired;
- (id)currentReachabilityFlags;
- (int)currentReachabilityStatus;
- (id)currentReachabilityString;
- (void)dealloc;
- (id)initWithReachabilityRef:(struct __SCNetworkReachability *)arg1;
- (_Bool)isConnectionOnDemand;
- (_Bool)isConnectionRequired;
- (_Bool)isInterventionRequired;
- (_Bool)isReachable;
- (_Bool)isReachableViaWWAN;
- (_Bool)isReachableViaWiFi;
- (_Bool)isReachableWithFlags:(unsigned int)arg1;
- (void)reachabilityChanged:(unsigned int)arg1;
- (unsigned int)reachabilityFlags;
@property(retain, nonatomic) id reachabilityObject; // @synthesize reachabilityObject=_reachabilityObject;
@property(nonatomic) struct __SCNetworkReachability *reachabilityRef; // @synthesize reachabilityRef=_reachabilityRef;
@property(nonatomic) struct dispatch_queue_s *reachabilitySerialQueue; // @synthesize reachabilitySerialQueue=_reachabilitySerialQueue;
@property(copy, nonatomic) CDUnknownBlockType reachableBlock; // @synthesize reachableBlock=_reachableBlock;
@property(nonatomic) _Bool reachableOnWWAN; // @synthesize reachableOnWWAN=_reachableOnWWAN;
@property(copy, nonatomic) CDUnknownBlockType unreachableBlock; // @synthesize unreachableBlock=_unreachableBlock;
- (_Bool)startNotifier;
- (void)stopNotifier;

@end

