//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSArray, NSMutableArray, UPLineView;

@interface UPPromotionTabBarViewController : UIViewController
{
    NSMutableArray *tabButtonArray;
    UPLineView *cursorline;
    NSArray *tabNameArr;
    unsigned long long _selectIndex;
    id <UPPromotionTabBarViewDelegate> _myDelegate;
}

- (void).cxx_destruct;
- (void)addbutionsStyle1;
- (void)buttonAction:(id)arg1;
- (void)deselectButtons;
- (void)didReceiveMemoryWarning;
- (id)initWithButtonNames:(id)arg1;
@property(nonatomic) __weak id <UPPromotionTabBarViewDelegate> myDelegate; // @synthesize myDelegate=_myDelegate;
- (void)selectButtonAtIndex:(unsigned long long)arg1;
@property(nonatomic) unsigned long long selectIndex; // @synthesize selectIndex=_selectIndex;
- (void)viewDidLoad;

@end

