//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class NSArray, NSMutableDictionary, UIView, UPLabel, UPPromotionCouponView;

@interface UPPromotionContentView : UIScrollView
{
    NSMutableDictionary *myListControllers;
    NSArray *myContentDics;
    UPPromotionCouponView *couponView;
    UIView *loadingView;
    UPLabel *_myLabel;
}

- (void).cxx_destruct;
- (void)addSubviews;
- (void)deselectAllListView;
- (void)hideScoreMessage;
- (id)initWithFrame:(struct CGRect)arg1 andContent:(id)arg2;
- (void)refreshCouponViewWithData:(id)arg1;
- (void)refreshScoreListWithData:(id)arg1;
- (void)selectListViewDefaultCell:(id)arg1;
- (void)showNoCoupon:(id)arg1;
- (void)showScoreMessage:(id)arg1;
- (void)showWalletMessage:(id)arg1 atTabIndex:(int)arg2;

@end

