//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSArray;

@interface UPPromotionListViewController : UITableViewController
{
    struct CGRect _myFrame;
    NSArray *_myDataSource;
    long long _selectedIndex;
}

- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) NSArray *myDataSource; // @synthesize myDataSource=_myDataSource;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
- (void)tableReload;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;

@end

