//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UPPullListViewDelegate.h"

@class NSArray, NSString, UIActivityIndicatorView, UITableView, UIView, UPLabel;

@interface UPSucceedViewController : UPBaseViewController <UPPullListViewDelegate, UITableViewDataSource, UITableViewDelegate>
{
    UPLabel *_tempPayInfoLabel;
    UIView *_successInfoView;
    UPLabel *_successTitleLabel;
    UPLabel *_successLabel;
    UIActivityIndicatorView *_indicator;
    UPLabel *_waitLabel;
    UITableView *_tableView;
    NSArray *promotions;
}

- (void).cxx_destruct;
- (void)addAdBar;
- (void)addNavigationBar;
- (void)addSubViews;
- (double)addTemporaryPay:(double)arg1;
- (id)atrributedStringFromInfo:(id)arg1;
- (void)comunicateToUPMPDidFailWithErrorType:(long long)arg1 error:(id)arg2;
- (void)comunicateToUPMPDidSucceedWithEvent:(long long)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (double)makeLuckView;
- (double)makeOldPaySuccessInfo;
- (double)makePaySuccessInfo;
- (void)makeTableViewAtY:(double)arg1;
- (void)nextAction:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) NSArray *promotions; // @synthesize promotions;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

