//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UPTalkingDataManager : NSObject
{
}

+ (_Bool)isTrack;
+ (void)trackEvent:(id)arg1;
+ (void)trackEvent:(id)arg1 withParameters:(id)arg2;
+ (void)trackPageBegin:(id)arg1;
+ (void)trackPageEnd:(id)arg1;

@end

