//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPBaseViewController.h"

#import "UPListViewDelegate.h"

@class NSMutableArray, NSString, UIView, UPDefaultCardView, UPListView, UPNewBankCardCell, UPPaymentElementsView, UPPromotionView;

@interface UPUserInfoViewController : UPBaseViewController <UPListViewDelegate>
{
    UPPaymentElementsView *_userInfoView;
    UIView *_indicatorView;
    UIView *_mainView;
    _Bool _noBindCards;
    _Bool mExitPlugin;
    _Bool _isUPMP;
    _Bool _handleModifyPhone;
    long long _selectedCardIndex;
    long long _indexBeforeSelected;
    UPDefaultCardView *_defaultCardView;
    UPPromotionView *_promotionView;
    UPListView *_cardListView;
    UPNewBankCardCell *_cardInputCell;
    NSMutableArray *_bindCardDescriptions;
    NSString *_savedPromotion;
}

- (void).cxx_destruct;
- (double)addCardListViewWithOriginY:(double)arg1;
- (double)addCardRules:(id)arg1 originY:(double)arg2;
- (double)addIndicatorViewWithOriginY:(double)arg1;
- (void)addNavigationBar;
- (void)addSubViews;
- (double)addUserInfosViewWithOriginY:(double)arg1;
- (void)buttonCancelClicked;
- (void)buttonOKClicked;
- (void)cancelAction:(id)arg1;
- (void)comunicateToUPMPDidFailWithErrorType:(long long)arg1 error:(id)arg2;
- (void)comunicateToUPMPDidSucceedWithEvent:(long long)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)initLocalDatas;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)listView:(id)arg1 DidSelectedAtIndex:(long long)arg2;
- (double)makeInputAtY:(double)arg1;
- (double)makeInstalmentViewAtY:(double)arg1;
- (double)makePromotionViewAtY:(double)arg1;
- (void)modifyAction:(id)arg1;
- (void)nextAction:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)postCommonCmd:(id)arg1;
- (void)promotionAndInstalmentCooperate:(id)arg1;
- (void)promotionRealPayAmountChange;
- (void)promotionView:(id)arg1 WillChangeFrameWithOffset:(double)arg2;
- (void)promotionViewOpenUrl:(id)arg1 andTitle:(id)arg2;
- (void)pullListAnimationDidStart:(double)arg1;
- (void)pushViewControllerToEntrustViewController;
- (void)pushViewControllerToPayingViewController;
- (void)pushViewToBindUrlViewContriller;
- (void)pushViewToInputViewController;
- (void)pushViewToSuccessViewContriller;
- (void)refreshCardRulesView;
- (void)releaseLocalDatas;
- (void)resetFrameOfView:(id)arg1 withYOffset:(double)arg2;
- (void)showBindCardsList;
- (double)showNoCardInfoAtY:(double)arg1;
- (void)showSupportedBank;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

