//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString, UTDIDKeychainItemWrapper, UTDIDPersistentFile;

@interface UTDIDPersistentConf : NSObject
{
    UTDIDKeychainItemWrapper *mKeyChainWrapper;
    UTDIDPersistentFile *mPersistentFile;
    NSMutableDictionary *mDict;
    NSString *mIdentifier;
    _Bool mIsModified;
    _Bool mAlwaysSyncWhenCommit;
}

+ (id)initWithIdentifier:(id)arg1;
- (void).cxx_destruct;
- (void)clear;
- (void)commit;
- (void)create:(id)arg1;
- (void)initData;
@property _Bool mAlwaysSyncWhenCommit; // @synthesize mAlwaysSyncWhenCommit;
- (id)objectForKey:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)reset;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)syncData;
- (void)syncToKC:(id)arg1;
- (void)syncToPF:(id)arg1;

@end

