//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WBDataTransferObject.h"

@class NSDictionary, NSString;

@interface WBBaseResponse : WBDataTransferObject
{
    NSString *requestID;
    NSString *responseID;
    long long statusCode;
    NSDictionary *requestUserInfo;
}

+ (id)mappedObjectWithDictionary:(id)arg1;
+ (void)nothing;
+ (id)objectFromPasteboardWithID:(id)arg1 sdkVersion:(id)arg2;
+ (id)response;
+ (id)transferType;
- (void).cxx_destruct;
- (id)init;
- (void)loadFromDictionary:(id)arg1;
- (id)objectID;
- (void)removeFromPasteboard;
@property(retain, nonatomic) NSString *requestID; // @synthesize requestID;
@property(retain, nonatomic) NSDictionary *requestUserInfo; // @synthesize requestUserInfo;
@property(retain, nonatomic) NSString *responseID; // @synthesize responseID;
- (void)setObjectID:(id)arg1;
@property(nonatomic) long long statusCode; // @synthesize statusCode;
- (void)storeToDictionary:(id)arg1;
- (id)validateAfterReceive;
- (id)validateBeforeSend;

@end

