//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, WeiboSDK3rdApp;

@interface WBDataTransferObject : NSObject
{
    _Bool shouldOpenWeiboAppInstallPageIfNotInstalled;
    NSDictionary *userInfo;
    WeiboSDK3rdApp *app;
    NSString *sdkVersion;
}

+ (id)UUID;
+ (id)mappedObjectWithDictionary:(id)arg1;
+ (id)objectFromPasteboardWithID:(id)arg1 sdkVersion:(id)arg2;
+ (id)open3rdAppSchemeWithID:(id)arg1 appKey:(id)arg2;
+ (id)openWeiboAppSchemeWithID:(id)arg1;
+ (id)pasteboardNameWithID:(id)arg1;
+ (void)removeFromPasteboardWithID:(id)arg1;
+ (id)transferType;
+ (id)unSupportedObjectFromPasteboard;
- (void).cxx_destruct;
@property(retain, nonatomic) WeiboSDK3rdApp *app; // @synthesize app;
- (_Bool)canBeReceived;
- (_Bool)canBeSent;
- (id)init;
- (void)loadFromDictionary:(id)arg1;
- (id)objectID;
- (id)open3rdAppSchemeWithAppKey:(id)arg1;
- (id)openWeiboAppScheme;
- (id)pasteboardName;
- (void)removeFromPasteboard;
@property(retain, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion;
- (void)setObjectID:(id)arg1;
@property(nonatomic) _Bool shouldOpenWeiboAppInstallPageIfNotInstalled; // @synthesize shouldOpenWeiboAppInstallPageIfNotInstalled;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo;
- (void)storeToDictionary:(id)arg1;
- (id)transferObjectsForPasteboard;
- (id)validate;
- (id)validateAfterReceive;
- (id)validateBeforeSend;
- (id)validateUserInfo;

@end

