//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface WBImageObject : NSObject
{
    NSData *imageData;
}

+ (id)dictionaryWithImageObject:(id)arg1;
+ (id)imageObjectWithDictionary:(id)arg1;
+ (id)object;
- (void).cxx_destruct;
- (id)image;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData;
- (id)validate;

@end

