//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UITextFieldDelegate.h"
#import "WBCountryCodeViewControllerDelegate.h"
#import "WBHttpRequestDelegate.h"
#import "WBSDKTTTAttributedLabelDelegate.h"

@class NSString, NSTimer, UIButton, UIImageView, UILabel, UIScrollView, WBSDKPhoneCountryView, WBSDKProgressHUD, WBSDKTTTAttributedLabel, WBSDKTextField;

@interface WBMessageRegisterViewController : UIViewController <WBHttpRequestDelegate, UITextFieldDelegate, WBCountryCodeViewControllerDelegate, UIGestureRecognizerDelegate, WBSDKTTTAttributedLabelDelegate>
{
    UIScrollView *_backgroundScrollView;
    WBSDKPhoneCountryView *_countryView;
    UILabel *tipsLabel;
    UILabel *serviceLabel;
    UIImageView *_textFieldBackgroudImageView;
    WBSDKTextField *_phoneNumberTextField;
    WBSDKTextField *_verifyCodeTextField;
    UILabel *_toastMessageLabel;
    UIButton *_loginButton;
    UIButton *_sendVerifyCodeButton;
    long long _resendTime;
    NSTimer *_resendCodeTimer;
    WBSDKProgressHUD *hud;
    WBSDKTTTAttributedLabel *_stipulationLabel;
}

- (void).cxx_destruct;
- (void)SendVerify;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)changeTime;
- (_Bool)checkIsPhoneNumber;
- (void)configSubviewsFrame;
- (void)countryBtnClick;
- (void)countryCodeDidSelect:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)getVerifyCode;
- (void)initLoginButton;
- (void)initStipulations;
- (void)initTextField;
- (void)initToastMessageLabel;
- (void)initVerifyCodeButton;
- (id)initWithTitle:(id)arg1;
- (_Bool)isEmptyOrWhitespace:(id)arg1;
- (_Bool)isPureInt:(id)arg1;
- (void)keyboardChangedNotification:(id)arg1;
- (void)keyboardDidShowNotification:(id)arg1;
- (void)keyboardHide:(id)arg1;
- (void)keyboardWillHideNotification:(id)arg1;
- (void)keyboardWillShowNotification:(id)arg1;
- (void)openPrivacyProtocolH5;
- (void)openUseProtocolH5;
- (void)presentedVCBackButtonClicked;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)request:(id)arg1 didFinishLoadingWithResult:(id)arg2;
@property(retain, nonatomic) WBSDKTTTAttributedLabel *stipulationLabel; // @synthesize stipulationLabel=_stipulationLabel;
- (void)setupSubviews;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldValueDidChanged:(id)arg1;
- (void)toastDisplayWithMessage:(id)arg1 isError:(_Bool)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

