//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WBSDKBasicWebViewController.h"

@class NSDictionary;

@interface WBSDKNormalWebViewController : WBSDKBasicWebViewController
{
    id <WBSDKNormalWebRequestDelegate> _delegate;
    NSDictionary *_resultResponseInfo;
}

- (void).cxx_destruct;
- (void)closeBtnClicked;
- (void)dealloc;
@property(retain, nonatomic) id <WBSDKNormalWebRequestDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didFinishAndPassDataToUser;
- (void)didReceiveWithResponseInfo:(id)arg1;
@property(retain, nonatomic) NSDictionary *resultResponseInfo; // @synthesize resultResponseInfo=_resultResponseInfo;
- (id)urlRequestFromWeiboSDKRequest:(id)arg1 andExtraPara:(id)arg2;
- (_Bool)wbsdk_webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;

@end

