//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WBBaseResponse.h"

@class NSDate, NSString, WBAuthorizeResponse;

@interface WBSDKAppRecommendResponse : WBBaseResponse
{
    WBAuthorizeResponse *_authResponse;
    NSString *_userID;
    NSString *_accessToken;
    NSDate *_expirationDate;
    NSString *_refreshToken;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property(retain, nonatomic) WBAuthorizeResponse *authResponse; // @synthesize authResponse=_authResponse;
- (_Bool)canBeReceived;
- (_Bool)canBeSent;
@property(retain, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(retain, nonatomic) NSString *refreshToken; // @synthesize refreshToken=_refreshToken;
@property(retain, nonatomic) NSString *userID; // @synthesize userID=_userID;

@end

