//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel;

@interface WBSDKWebViewErrorView : UIView
{
    UIButton *_retryButton;
    UIView *_buttonsContainer;
    UIButton *_closeButton;
    UILabel *_descriptionLabel;
    UIImageView *_imageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *buttonsContainer; // @synthesize buttonsContainer=_buttonsContainer;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
- (void)hide;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layout;
- (void)layoutSubviews;
@property(retain, nonatomic) UIButton *retryButton; // @synthesize retryButton=_retryButton;
- (void)showError:(id)arg1;

@end

