//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WBSDKDBObjectAccessDelgate.h"

@class NSDate, NSDictionary, NSString;

@interface WBSDKStatisticsRecord : NSObject <WBSDKDBObjectAccessDelgate>
{
    NSString *_aid;
    NSString *_eventID;
    NSString *_pageID;
    NSDictionary *_userInfo;
    NSDate *_time;
    double _duration;
    long long _recordType;
}

+ (void)createTableIfNeeded:(id)arg1;
+ (void)deleteInDB:(id)arg1 fromTime:(double)arg2 toTime:(double)arg3;
+ (id)objectFromRS:(id)arg1;
+ (id)recordWithEventID:(id)arg1 pageID:(id)arg2 userInfo:(id)arg3 recordType:(long long)arg4;
+ (id)selectDB:(id)arg1 fromTime:(double)arg2 toTime:(double)arg3;
+ (id)tableName;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *aid; // @synthesize aid=_aid;
- (void)deleteInDB:(id)arg1;
@property(readonly, copy) NSString *description;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(copy, nonatomic) NSString *eventID; // @synthesize eventID=_eventID;
- (id)init;
- (id)initWithEventID:(id)arg1 pageID:(id)arg2 userInfo:(id)arg3 recordType:(long long)arg4;
- (void)insertToDataBase:(id)arg1;
- (void)loadFromRS:(id)arg1;
@property(copy, nonatomic) NSString *pageID; // @synthesize pageID=_pageID;
@property(nonatomic) long long recordType; // @synthesize recordType=_recordType;
@property(copy, nonatomic) NSDate *time; // @synthesize time=_time;
@property(copy, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
- (id)uniqueID;
- (void)updateDB:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

