//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, WBSDKFMDatabase;

@interface WBSDKDBManager : NSObject
{
    WBSDKFMDatabase *db;
    NSObject<OS_dispatch_queue> *io_queue;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedManager;
- (void).cxx_destruct;
- (void)beginTransaction;
- (void)closeDataBase;
- (id)databaseObjectsWithResultSet:(id)arg1 class:(Class)arg2;
@property(retain, nonatomic) WBSDKFMDatabase *db; // @synthesize db;
- (void)dealloc;
- (void)endTransaction;
- (id)init;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *io_queue; // @synthesize io_queue;
- (void)openDataBase;
- (void)readDatabaseBlockInTransaction:(CDUnknownBlockType)arg1;
- (void)writeDatabaseBlockInTransaction:(CDUnknownBlockType)arg1;

@end

