//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WeiboSDK : NSObject
{
}

+ (id)activityViewController;
+ (void)beginLogEvent:(id)arg1;
+ (void)beginLogEvent:(id)arg1 onPageView:(id)arg2 withUserInfo:(id)arg3;
+ (void)beginLogPageView:(id)arg1;
+ (id)callbackSchemePrefix;
+ (_Bool)canAccessPrivatePasteboard;
+ (id)deprecatedWeiboAppSupportMaxSDKVersion;
+ (void)didReceiveUnSupportedRequest:(id)arg1;
+ (void)didReceiveUnSupportedResponse:(id)arg1;
+ (void)directlySendResponseToCurrentApp:(id)arg1;
+ (void)enableDebugMode:(_Bool)arg1;
+ (void)endLogEvent:(id)arg1;
+ (void)endLogEvent:(id)arg1 onPageView:(id)arg2 withUserInfo:(id)arg3;
+ (void)endLogPageView:(id)arg1;
+ (void)event:(id)arg1;
+ (void)event:(id)arg1 onPageView:(id)arg2 withUserInfo:(id)arg3;
+ (void)firstStart;
+ (void)forceUploadRecords;
+ (id)getSDKVersion;
+ (id)getWeiboAid;
+ (id)getWeiboAppInstallUrl;
+ (id)getWeiboAppSupportMaxSDKVersion;
+ (id)getWeiboSDKUA;
+ (_Bool)handleOpenURL:(id)arg1 delegate:(id)arg2;
+ (id)hashKey;
+ (void)internalEvent:(id)arg1 withStartTime:(id)arg2;
+ (void)inviteFriend:(id)arg1 withUid:(id)arg2 withToken:(id)arg3 delegate:(id)arg4 withTag:(id)arg5;
+ (_Bool)isCanPayInWeiboApp;
+ (_Bool)isCanSSOAndShareInWeiboApp;
+ (_Bool)isCanSSOInWeiboApp;
+ (_Bool)isCanShareInWeiboAPP;
+ (_Bool)isEmptyOrWhitespace:(id)arg1;
+ (_Bool)isWeiboAppFullSupportQuickAuth;
+ (_Bool)isWeiboAppInstalled;
+ (void)logOutWithToken:(id)arg1 delegate:(id)arg2 withTag:(id)arg3;
+ (void)messageRegister:(id)arg1;
+ (_Bool)openAppWithTransferObject:(id)arg1;
+ (_Bool)openWeiboApp;
+ (id)pasteboardWithName:(id)arg1 create:(_Bool)arg2;
+ (id)queryDictionaryOfURLQuery:(id)arg1 usingEncoding:(unsigned long long)arg2;
+ (id)queryValueWithName:(id)arg1 urlString:(id)arg2;
+ (id)registedAppsPasteboardName;
+ (_Bool)registerApp:(id)arg1;
+ (_Bool)registerAppWithApp:(id)arg1;
+ (_Bool)registerAppWithAppKey:(id)arg1;
+ (void)removePasteboardWithName:(id)arg1;
+ (id)requestUserInfoCache;
+ (_Bool)sendRequest:(id)arg1;
+ (_Bool)sendResponse:(id)arg1;
+ (id)serializeURLString:(id)arg1 withParams:(id)arg2;
+ (void)setChannelID:(id)arg1;
+ (void)setStatisticsEnabled:(_Bool)arg1;
+ (void)setStatisticsLogEnabled:(_Bool)arg1;
+ (void)setUploadFrequecy:(double)arg1;
+ (void)setVersion:(id)arg1;
+ (_Bool)unregisterApp;
+ (id)wbsdk_platform;

@end

