//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKWebViewConfiguration.h"

@interface WKWebViewConfiguration (ButtonSDKVersion)
- (_Bool)BTN_canModifyUserAgent;
- (void)BTN_updateWithSDKVersion:(id)arg1;
- (id)BTN_updatedAppNameByAddingButtonSuffix:(id)arg1 sdkVersion:(id)arg2;
@end

