//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WXOMTAStore : NSObject
{
    struct dispatch_queue_s *task_queue;
    struct sqlite3 *db;
    unsigned int numStoredEvents;
}

+ (id)getInstance;
- (void)close;
- (void)closeDB;
- (void)deleteDB;
- (void)deleteEvents:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (struct sqlite3 *)getDB;
- (id)getMtaOpenUDID;
- (unsigned int)getStoredEventsNum;
- (id)init;
- (void)initDB;
- (void)launch;
- (void)loadCachedEvents:(id)arg1;
- (void)loadConfig:(CDUnknownBlockType)arg1;
- (id)loadUser;
- (void)sendCachedEvents:(int)arg1;
- (void)storeConfig:(id)arg1;
- (void)storeEvent:(id)arg1 hasTrySent:(_Bool)arg2 CB:(CDUnknownBlockType)arg3;
- (void)storeUser:(id)arg1;
- (unsigned int)storedEventCount;
- (int)updateDatabase:(const char *)arg1;
- (void)updateEvents:(id)arg1 status:(unsigned int)arg2;
- (void)updateSendFailedEvents:(id)arg1;

@end

