//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXOMTAEvent.h"

#import "WXOMTAEventProtocol.h"

@class NSArray, NSDictionary, NSString;

@interface WXOMTACustomEvent : WXOMTAEvent <WXOMTAEventProtocol>
{
    unsigned int _duration;
    NSString *_eventID;
    NSArray *_args;
    NSDictionary *_kvs;
}

@property(retain, nonatomic) NSArray *args; // @synthesize args=_args;
- (void)dealloc;
@property unsigned int duration; // @synthesize duration=_duration;
- (void)encode:(id)arg1;
@property(retain, nonatomic) NSString *eventID; // @synthesize eventID=_eventID;
- (int)getType;
- (id)init;
@property(retain, nonatomic) NSDictionary *kvs; // @synthesize kvs=_kvs;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

