//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YLUniMemoryData : NSObject
{
    _Bool _isSessionOpened;
    _Bool _isInitialized;
    _Bool _isExceptionReportEnabled;
    _Bool _isDataSending;
    _Bool _isOffline;
    _Bool _isSignalReportEnabled;
    unsigned long long _bgTask;
    NSString *_currentPage;
    NSString *_sessionId;
    long long _sessionStartTime;
    long long _sessionEndTime;
    NSString *_appKey;
    NSString *_channelId;
    NSString *_appVersionCode;
    NSString *_appVersionName;
    double _latitude;
    double _longitude;
    NSString *_lastPage;
    long long _lastLaunchTime;
    long long _lastAppListTime;
    long long _lastProecessTime;
    NSString *_savedIp;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedTDMemoryData;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(retain, nonatomic) NSString *appVersionCode; // @synthesize appVersionCode=_appVersionCode;
@property(retain, nonatomic) NSString *appVersionName; // @synthesize appVersionName=_appVersionName;
- (void)archiveToFile;
@property(nonatomic) unsigned long long bgTask; // @synthesize bgTask=_bgTask;
@property(retain, nonatomic) NSString *channelId; // @synthesize channelId=_channelId;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSString *currentPage; // @synthesize currentPage=_currentPage;
- (id)init;
@property(nonatomic) _Bool isDataSending; // @synthesize isDataSending=_isDataSending;
@property(nonatomic) _Bool isExceptionReportEnabled; // @synthesize isExceptionReportEnabled=_isExceptionReportEnabled;
@property(nonatomic) _Bool isInitialized; // @synthesize isInitialized=_isInitialized;
@property(nonatomic) _Bool isOffline; // @synthesize isOffline=_isOffline;
@property(nonatomic) _Bool isSessionOpened; // @synthesize isSessionOpened=_isSessionOpened;
@property(nonatomic) _Bool isSignalReportEnabled; // @synthesize isSignalReportEnabled=_isSignalReportEnabled;
@property(nonatomic) long long lastAppListTime; // @synthesize lastAppListTime=_lastAppListTime;
@property(nonatomic) long long lastLaunchTime; // @synthesize lastLaunchTime=_lastLaunchTime;
@property(retain, nonatomic) NSString *lastPage; // @synthesize lastPage=_lastPage;
@property(nonatomic) long long lastProecessTime; // @synthesize lastProecessTime=_lastProecessTime;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *savedIp; // @synthesize savedIp=_savedIp;
@property(nonatomic) long long sessionEndTime; // @synthesize sessionEndTime=_sessionEndTime;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) long long sessionStartTime; // @synthesize sessionStartTime=_sessionStartTime;
- (void)unarchiveFromFile;

@end

