//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSStreamDelegate.h"

@class NSArray, NSMutableData, NSString, NSThread;

@interface YLUniHttpRequest : NSObject <NSStreamDelegate>
{
    struct __CFURL *_url;
    struct __CFHTTPMessage *_request;
    struct __CFReadStream *_readStream;
    _Bool _isSecure;
    _Bool _isConnection;
    NSArray *_certificates;
    long long _statusCode;
    NSMutableData *_receivedData;
    id _userInfo;
    id _reserved;
    id _delegate;
    NSThread *_sourceThread;
}

+ (id)pinnedCertificates;
+ (id)requestWithString:(id)arg1 httpMethod:(id)arg2;
- (void).cxx_destruct;
- (void)addValue:(id)arg1 forHTTPHeaderField:(id)arg2;
- (void)cancel;
@property(retain, nonatomic) NSArray *certificates; // @synthesize certificates=_certificates;
- (void)dealloc;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (unsigned long long)httpBodySize;
- (id)initWithURLString:(id)arg1 httpMethod:(id)arg2;
@property(readonly, nonatomic) _Bool isConnection; // @synthesize isConnection=_isConnection;
@property(readonly, nonatomic) NSMutableData *receivedData; // @synthesize receivedData=_receivedData;
@property(retain, nonatomic) id reserved; // @synthesize reserved=_reserved;
- (void)sendFailed;
- (void)sendRequest;
- (void)sendSuccess;
- (void)setHTTPBody:(id)arg1;
@property(nonatomic) __weak NSThread *sourceThread; // @synthesize sourceThread=_sourceThread;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
- (void)startAsyncSend;
- (id)startSyncSend:(long long *)arg1;
@property(readonly, nonatomic) long long statusCode; // @synthesize statusCode=_statusCode;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

