//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class YLUniAppException, YLUniInitProfile, YLUniSession;

@interface YLUniMessage : NSObject
{
    int _msgType;
    YLUniSession *_session;
    YLUniInitProfile *_initProfile;
    YLUniAppException *_appException;
}

- (void).cxx_destruct;
@property(retain, nonatomic) YLUniAppException *appException; // @synthesize appException=_appException;
@property(retain, nonatomic) YLUniInitProfile *initProfile; // @synthesize initProfile=_initProfile;
- (void)messagePack:(struct msgpack_packer *)arg1;
@property(nonatomic) int msgType; // @synthesize msgType=_msgType;
@property(retain, nonatomic) YLUniSession *session; // @synthesize session=_session;

@end

