//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YLUniAppProfile : NSObject
{
    _Bool _isCracked;
    NSString *_appPackageName;
    NSString *_appVersionName;
    NSString *_appVersionCode;
    long long _startTime;
    NSString *_sdkVersion;
    NSString *_partnerId;
    long long _installationTime;
    long long _purchaseTime;
    long long _appStoreID;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appPackageName; // @synthesize appPackageName=_appPackageName;
@property(nonatomic) long long appStoreID; // @synthesize appStoreID=_appStoreID;
@property(retain, nonatomic) NSString *appVersionCode; // @synthesize appVersionCode=_appVersionCode;
@property(retain, nonatomic) NSString *appVersionName; // @synthesize appVersionName=_appVersionName;
@property(nonatomic) long long installationTime; // @synthesize installationTime=_installationTime;
@property(nonatomic) _Bool isCracked; // @synthesize isCracked=_isCracked;
- (void)messagePack:(struct msgpack_packer *)arg1;
@property(retain, nonatomic) NSString *partnerId; // @synthesize partnerId=_partnerId;
@property(nonatomic) long long purchaseTime; // @synthesize purchaseTime=_purchaseTime;
@property(retain, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(nonatomic) long long startTime; // @synthesize startTime=_startTime;

@end

